tpm2-software/tpm2-tools

sapi-tools/common.cpp
sapi-tools/tpm2_quote.cpp

fix a typo about function saveTpmContextToFile(... ) in file common.cpp,
the included header file arpa/inet.h in tpm2_quote.cpp is no need on _WIN32.

fix a typo in common.cpp and remove a header file in tpm2_quote

---

sapi-tools/Makefile.am
sapi-tools/common.cpp

This header was included in the common.cpp file but as far as I can
tell, none of the tools code acutally uses anything from it.
This resolves #14

Remove depenedency on the resourcemgr header from the TPM2.0-TSS repo.

---

sapi-tools/common.cpp

This file no longer pulls in the TCTI_MAGIC / TCTI_VERSION. It is also
not a standard tss2 header so it will go away soon. These are values
come from a TCTI implementation and so we get them from the respective
TCTI headers instead now.
This resolves #19

common: Do not include tpm2sapi/tss2_sapi_util.h

---

Makefile.am

The order of these libraries is significant when linking 'as-needed'.
This resolves #31

build: Move libcommon.a to the front of LDADD.

---

configure.ac

build: Detect required TSS2 and TCTI headers.

---

.gitignore
ChangeLog
Makefile.am
configure.ac
src/rc-decode.c
src/rc-decode.h
src/tpm2_rc_decode.c
test/tpm2-rc-decode_unit.c
test/tpm2-rc-entry_unit.c

This replaces #78. It includes 3 commits, each adding a component of the TPM_RC decode stuff.

TPM_RC decode tool

---

manual
src/tpm2_listpcrs.cpp
test/test_tpm2_listpcrs.sh

Add -s option to show all the assigned PCR banks/algorithms.
Add -L option to show selected pcr values in selected banks.
Update the no option case to show all avaiable banks' pcr values instead of show all the hardcoded banks.
Rewrite most of the code to optimize the running speed.

tpm2_listpcrs: add options -L and -s

---

ChangeLog
Makefile.am
configure.ac

This makes the dependence on libcmocka optional.

configure.ac: Allow for the unit tests to be enabled selectively.

---

src/tpm2_evictcontrol.cpp
src/tpm2_getmanufec.cpp
src/tpm2_getpubak.cpp
src/tpm2_getpubek.cpp
test/test_tpm2_hmac.sh
test/test_tpm2_sign.sh

Fixed below issues:
1. some test scripts will check the output of some tools for correction check. Some checks were based on some output with typo, now the typo in the code was fixed, but the test scripts was missed.
2. the commit adding -X option for most tools introduced some password input usage issues, which caused that the handle password might be used for owner or endorse password.
3. tpm2_evictcontrol -h will export samples with bad object handles.

A series of bug fixes

---

ChangeLog
manual
src/tpm2_takeownership.cpp

On production version platform, the platform auth is usually set by
BIOS and not available to applications. So change to do clearing via
giving LOCKOUT auth/password.

tpm2_takeownership: update option -c to use lockout password to clear

---

.gitignore

.gitignore: Ignore tpm2_listpersistent and tpm2_nvreadlock binaries.

---

.travis.yml

Use a a protocol that is not susceptable to man-in-the-
middle attacks for downloading a binary to the CI server.

travis: correct wget over http

---

test/.gitignore

Only worry about shell scripts, unit tests, test fixtures,
the readme and the gitignore file itself.  and ignore the
test artifacts that end up in this directory.

tests: gitignore addition

---

Makefile.am
man/tpm2_listpersistent.8.in
src/tpm2_listpersistent.c

This one was very straight forward. After removing the duplicate options
processing code ... there wasn't any left. The main function was reduced
to effectively a single function call. This commit just removes 'main'
outright and turns the 'listPersistent' into the 'execute_tool'
function. There are also a few cleanups made to the manpage.

tpm2_listpersistent: Port to use common infrastructure.

---

src/tpm2_listpersistent.c
src/tpm2_load.c

These were bugs hidden by compiling with the socket TCTI enabled and
thus the common module enabled.

Fix build errors from last 2 commits.

---

.travis.yml

Installing the tools is a crutch and one that will back fire if we ever
want to automate builds for multiple configurations.
This resolves #179

.travis.yml: Remove `make install` in favor of PATH manipulation.

---

scripts/utils/intelEKcert2PemDer.sh

Adding this as a resolution to Issue#142.
Script to strip manufacturer (Intel) metadata from EK cert, to convert it into standard PEM/DER format.

Adding utility to convert TPM manufacturer's EK cert to standard PEM/DER format 

---

.travis.yml

Check build for different configure options to avoid code check-in breaking
certain configure options.
Fixing #178.

Update .travis.yml to add a few additional builds

---

src/string-bytes.c
src/string-bytes.h
src/tpm2_createprimary.c

getSizeUintXX and getSizeUintXXHex routines were very similair.
Refactor them to use strtoul(), and allow strtoul to handle the base.
Also, call the 32 bit variant from the 16 and just check for overflow.
Mark the old interfaces as deprecated, since there are a TON of callers and
convert them on later porting/refactoring endeavors.

string-bytes: re-implement string to value routines

---

bootstrap

This is the preferred method and much more simple than calling each
autotool in succession.

bootstrap: Replace manual invocation of autotools with autoreconf.

---

man/tcti-environment.troff
man/tcti-options.troff

These warnings can be output for the tpm2_create command:
MANPATH=$(pwd)/man man --warnings=all tpm2_create > /dev/null
<standard input>:109: warning: missing `)' (got `\{')
<standard input>:114: warning: missing `)' (got `\{')
<standard input>:137: warning: missing `)' (got `\{')
<standard input>:141: warning: missing `)' (got `\{')

man: Add closing parenthesis in troff conditional for TCTI opts / env.

---

src/options.h

Fix:
==28639== Invalid read of size 1
==28639==    at 0x4C31F93: strcmp (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28639==    by 0x4020CC: tcti_type_from_name (options.c:85)
==28639==    by 0x40260E: get_common_opts (options.c:300)
==28639==    by 0x401A0A: main (main.c:57)
==28639==  Address 0x3 is not stack'd, malloc'd or (recently) free'd
This occurs when searching the tcti_map_table for a match. The
tcti_map_table and the bounding enum N_TCTI was mismtached, as the
enum entry has a 0 value causing all accesses to be off by one.
Since there were no useres of TCTI_0, remove.
Fixes: #222

options: fix memory corruption

---

lib/files.c

When the interface was changed to pass-by-value versus
pointers, BE_MACRO was not updated properly. Correct this
to suppress the warning:
../lib/files.c: In function ‘files_read_16’:
../lib/files.c:251:1: warning: passing argument 1 of ‘string_bytes_endian_convert_16’ makes integer from pointer without a cast [enabled by default]
FILE_READ(16);
Fixes #237

files: fix BE_CONVERT macro

---

tools/tpm2_evictcontrol.c

Passing -P to tpm2_evictcontrol exits immediately because of mishandling the
return value of password_util_copy_password.
Fixes #249

tpm2_evictcontrol: fix bug in password handling

---

tools/tpm2_send_command.c

Use 'z' for size_t, not 'l'. This problem only manifests on 32bit
systems where size_t is not a long int. This is why the 'z' length
modifier exists.

tpm2_send_command: Fix bad length specifiers in LOG_* statements.

---

man/tpm2_getrandom.8.in
test/system/test_smoking.sh
test/system/test_tpm2_getrandom.sh
test/system/test_tpm2_getrandom_func.sh
tools/tpm2_getrandom.c

Make argument options optional for tpm2_getrandom. Size is a required
argument, so make it a required positional arg. Now, the only option
is -o or --output, which optionally specifies an output file. If an
output file is specified, it writes all output to that file, else
it prints hex values of the bytes to the terminal.
Fixes 251
This patch requires a significant version bump as this version of
tpm2_getrandom is not "api" compatable with older versions.

tpm2_getrandom: update help and simplify interface

---

README.md

The list of tools wasn;t rendering correctly on github, even through "grip"
rendered it properly. Also, it didn't provide any relevant information and
required upkeep for new/deleted tools. Remove it.

README.md: drop list of tools

---

tools/tpm2_getmanufec.c

hash is only going have a valid value if SHA256_Final
completes successfully, so free and set to null in
error paths.

tpm2_getmanufec: free hash in error paths of HashEKPublicKey

---

test/system/test_tpm2_getmanufec.sh

The script exercises the offline provisioning option with a test endorsement key which has a corresponding certificate that will be retrieved from the manufacturer backend.

Adding test script to sanitize PRs on tpm2_getmanufec tool

---

bootstrap

The bootstrap script hard-codes the autoreconf binary. This hard-coding
makes it unfeasible to run in a sandboxed environment where those
binaries are located at non-standard paths. Typically in makefiles,
binaries can be overwritten through environment variables.
This change adjusts the bootstrap script to honor the AUTORECONF
variable if present in the environment but is able to fall back to the
previous default if not.

bootstrap: make autoreconf configurable via environment

---

Makefile.am
lib/pcr.c
lib/pcr.h
lib/tpm_hash.c
lib/tpm_hash.h
man/tpm2_createpolicy.8.in
test/system/test_all.sh
test/system/test_tpm2_createpolicy.sh
tools/tpm2_createpolicy.c

Adding tpm2_createpolicy tool for creating simple assertion policy with pcr.
Adding the unit test as well that should calculate the policy digest with pcr index 0

Adding tpm2_createpolicy tool for creating simple assertion policy with pcr

---

test/system/test_tpm2_encryptdecrypt.sh

Check whether the command encryptdecrypt is supported by the device before testing it

Rework encryptdecrypt test

---

configure.ac

On my hardened gentoo system _FORTIFY_SOURCE is already defined,
thus it makes sense to undefine it first then define it, not vice
versa.
Signed-off-by: Peter Huewe <peterhuewe@gmx.de>

configure: Undefine FORTIFY_SOURCE first, then define it

---

tools/tpm2_listpcrs.c

commit c2586d4116b29436baa6608c5c3a222aae8bf193 use TPM2_GetCapability to determine PCRs to read for two cases: tpm2_listpcrs & tpm2_listpcrs -g 0xXXX, but the cases using -L will still cause unexpected result if give disabled or unsupported pcr banks.
First, keep the list of available PCRs in the global context after the first call to TPM2_GetCapability by get_banks() and then reuse the list in init_pcr_selection().
Then reuse the list of available PCRs to check and filter out unsupported pcr banks: give a warning message and then skip unsupported banks.

listpcrs: filter -L input with list of available PCRs

---

test/system/test_all.sh
tools/tpm2_getmanufec.c

We would get spotty build failures caused by tpm2_getmanufec
failing. Calgrind reported issues with b64 decode.
That code assumed the pointer returned by openssl bio routines
was NULL terminated, and that is not the case and strlen was
reading past the end.
Properly terminate the b64 decoded string.

tpm2_getmanufec: fix memory issues

---

INSTALL
lib/tpm_kdfa.c
tools/main.c
tools/tpm2_dump_capability.c

Hello,
These commits fixes some compile errors I found when building tpm2.0-tools on a Fedora 26 machine.
The first commit is just a cleanup for a left over comment in INSTALL about the src directory that no longer exists, the second commit fixes some build warnings due GCC7 complaining about not having explicit comments for case blocks falling through the next one in switch statements and the last commit adds some #ifdefery to cope with the recent API changes in the OpenSSL 1.1.0 library.
Best regards,
Javier

Fix build issues with GCC7 and OpenSSL 1.1.0

---

man/tpm2_createprimary.8.in

Commit 1627714b83e0 ("tpm2_createprimary: Port to the new options /
context infrastructure.") ported tpm2_createprimary tool to the new
common options infrastructure, so it removed the options that were
already present such as -d, --debugLevel since there's a common -V,
--verbose option.
But the man page stills lists -d, --debugLevel as valid option for
this tool, which is not only wrong but also confusing since common
have a -d, --device option when building --with-tcti-device=yes.

man: delete wrong option from tpm2_createprimary man page

---

tools/tpm2_unseal.c

The tpm2_unseal tool doesn't write to the output file only the data that
was sealed, but instead writes the whole TPM2B_SENSITIVE_DATA structure
as filled by Tss2_Sys_Unseal().
That means that the buffer size is prefixed and the data is padded up to
MAX_SYM_DATA with zeros.
$ echo foobar > secret.data
$ hexdump -C -v secret.data
00000000  66 6f 6f 62 61 72 0a                              |foobar.|
00000007
After sealing and unsealing the data using the tpm2.0-tools:
$ hexdump -C -v usl_ctx_load_out_0x0004_0x0001-0x000B_0x0008
00000000  07 00 66 6f 6f 62 61 72  0a 00 00 00 00 00 00 00  |..foobar........|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 …

tpm2_unseal: fix unsealed data object serialization

---

tools/tpm2_listpcrs.c

Commit 828f0d6e851b ("tpm2_listpcrs: use dymaic tcti/sapi") besides porting
to the execute_tool() interface, did some refactoring. But unfortunately it
broke the tool command line options parsing since it uses the optopt global
variable instead of the value returned by the getopt_long() function.
Since optopt stores the last known option, the tool only works properly if
a single command line option is used:
$ tpm2_listpcrs -o pcrs.bin -L 0x4:9
Argument error: pcrs.bin
Please type "tpm2_listpcrs -h" get the usage!
$ tpm2_listpcrs -L 0x4:9
Bank/Algorithm: TPM_ALG_SHA1(0x0004)
PCR_09: 78 74 96 d6 81 50 84 ab 6b 50 69 4f 29 1c 99 b1 d6 a4 f5 28
Fixes: 828f0d6e851b ("tpm2_listpcrs: use dymaic tcti/sapi")

tpm2_listpcrs: fix command line options parsing

---

test/system/test_tpm2_createpolicy.sh

The test does the same for both the SHA1 and SHA256 algorithms
so it can be simplified and the duplicated code removed.
While being there, add a variable for the PCR index instead of
using a constat value. This makes the test easier to read.

test_tpm2_createpolicy.sh: simplify test by removing duplicated code

---

man/tpm2_createprimary.8.in

The SHA256 algorithm is mentioned twice, the -g 0xD option is for SHA512.

man: fix hash algorithm listed for tpm2_createprimary -g 0xD option

---

lib/files.c

If the frwite in writex or fread in readx was interrupted more than once, the index into data would be incorrect on the second and subsequent interrupts. This fixes the potential issue by keeping track of the correct index.

Fix potential issue if readx/writex get interrupted more than once

---

lib/files.c
lib/files.h
man/tpm2_create.8.in
tools/tpm2_create.c

It may be important to never store sensitive data in the file system, but the tpm2_create tool only allows to pass a data to be sealed as a file using the -I option.
So this pull request adds support for tpm2_create to read the data to be sealed from the standard input instead.

Allow tpm2_create to read data to be sealed from stdin

---

man/tpm2_unseal.8.in
tools/tpm2_unseal.c

This pull request is similar to commit 686951ed0b30 ("tpm2_create: allow read data to be sealed from the standard input"), the idea is to do the same for tpm2_unseal so the sensible data never is stored.
The first commit is just a cleanup, but makes the logic simpler for the second commit since we just test if ctx->outFilePath has been set to know if the user passed the -o option.

Allow tpm2_unseal to write the unsealed data to stdout

---

test/system/test_tpm2_unseal.sh

The commit 780c3bcdd8ec ("tpm2_unseal: print a success message if the test
finish successfully") originally was using the bash if command construct,
but was modified when merged to have the command inside brackets and match
the rest of the script.
Unfortunately commands can't be inside [] since they are used only to test
conditional expressions and not command exit code. This leads to following
error when executing the test:
./test_tpm2_unseal.sh: line 78: [: too many arguments
So take the commands out of the if statement and instead use an expression
to test the latest command exit code. This also matches what's done in the
rest of the script.

test_tpm2_unseal: fix invalid conditional expression

---

man/tpm2_createprimary.8.in
test/system/test_tpm2_createprimary_all.sh
tools/tpm2_createprimary.c

This commit should enable creating primary objects with authorization based on policies with an option to enforce policy.

Adding option to create primary objects with policy based authorization

---

tools/tpm2_activatecredential.c
tools/tpm2_akparse.c
tools/tpm2_certify.c
tools/tpm2_create.c
tools/tpm2_encryptdecrypt.c
tools/tpm2_evictcontrol.c
tools/tpm2_getmanufec.c
tools/tpm2_getpubak.c
tools/tpm2_getpubek.c
tools/tpm2_getrandom.c
tools/tpm2_hash.c
tools/tpm2_load.c
tools/tpm2_loadexternal.c
tools/tpm2_nvwrite.c
tools/tpm2_quote.c
tools/tpm2_readpublic.c
tools/tpm2_rsadecrypt.c
tools/tpm2_rsaencrypt.c
tools/tpm2_sign.c
tools/tpm2_unseal.c
tools/tpm2_verifysignature.c

This contains fixes for all the remaining offenders of issue #260. The only file that I didn't fix was tpm2_createpolicy.c to avoid creating a conflict for @idesai, since he has a pending pull request refactoring that file.

Fix remaining tools doing unnecessary options arguments copies

---

man/tpm2_unseal.8.in
test/system/test_tpm2_unseal.sh
test/unit/test_string_bytes.c
tools/tpm2_activatecredential.c
tools/tpm2_akparse.c
tools/tpm2_dictionarylockout.c
tools/tpm2_encryptdecrypt.c
tools/tpm2_evictcontrol.c
tools/tpm2_getmanufec.c
tools/tpm2_getpubak.c
tools/tpm2_getpubek.c
tools/tpm2_getrandom.c
tools/tpm2_hash.c
tools/tpm2_listpcrs.c
tools/tpm2_listpersistent.c
tools/tpm2_loadexternal.c
tools/tpm2_makecredential.c
tools/tpm2_nvdefine.c
tools/tpm2_nvread.c
tools/tpm2_nvreadlock.c
tools/tpm2_nvrelease.c
tools/tpm2_nvwrite.c
tools/tpm2_readpublic.c
tools/tpm2_rsadecrypt.c
tools/tpm2_rsaencrypt.c
tools/tpm2_sign.c
tools/tpm2_takeownership.c
tools/tpm2_unseal.c
tools/tpm2_verifysignature.c

This pull request adds support for tpm2_unseal to authenticate using a PCR policy so objects can be unsealed only when a PCR policy is satisfied.
The first commit is just a cleanup, the second is the one that adds the support and the third one extends the test_tpm2_unseal.sh test case to cover the object creation and unsealing using a PCR policy for auth.

Allow  tpm2_unseal to unseal an object using a PCR policy for authentication

---

lib/log.c
lib/log.h
tools/tpm2_getmanufec.c

This is the correction of [pull request 357](https://github.com/01org/tpm2.0-tools/pull/357). Since the commit message had to be corrected, I ve decided to close the previous pull-request and create a new one:
- Considering remarks of @martinezjavier  and @williamcroberts 
- Correcting the commit message

Fixing compiler warnings with GCC 4.7.2

---

tools/tpm2_create.c
tools/tpm2_createprimary.c

In tpm2_create & tpm2_createprimary, if -L option was not specified
to initialize authPolicy, the authPolicy size of inPublic will be
random value and may cause sysapi context insufficient error.
Signed-off-by: Gang Wei <gang.wei@intel.com>

Fix uninitialized inPublic.t.publicArea.authPolicy

---

Makefile.am
lib/tpm2_nv_util.c
lib/tpm2_nv_util.h
lib/tpm2_util.h
man/tpm2_nvdefine.8.in
test/system/test_tpm2_nv.sh
test/unit/test_tpm2_nv_util.c
tools/tpm2_certify.c
tools/tpm2_nvdefine.c
tools/tpm2_nvlist.c
tools/tpm2_nvread.c
tools/tpm2_nvwrite.c
tools/tpm2_readpublic.c
tools/tpm2_takeownership.c

This replaces PR #359 and adds to it.
This starts to get rid of specifying the attributes for nv indexes during nvdefine in raw numerical format.
I still need to modify tom2_nvdefine to use it, and update it's man page.
- Unit tests are in place for the new attribute keyword parser.
- System test is in place for writing a big nvindex.
- System tests in place for using nice names.
- System tests in place for verifying that nvread reads the same bytes as nvwrite.
- nvread output is in xxd -r compatible format.
- nvread -s is no longer needed.

Idesai tpm2 nvwrite size fix and add nice-name handling for nv attributes

---

lib/files.c
lib/files.h
test/unit/test_files.c
tools/tpm2_createpolicy.c
tools/tpm2_hash.c
tools/tpm2_sign.c
tools/tpm2_verifysignature.c

Without this change, the compiler complains about a comparison between signed and unsigned integer expressions (filesize != expected_pcr_input_file_size) and aborts the compilation (due to Werror). Since expected_pcr_input_file_size exists only to be compared to filesize, its type can simply be changed to match that of filesize.

Use identical types in comparison

---

Makefile.am
lib/tpm2_policy.c
lib/tpm2_policy.h
test/system/test_tpm2_unseal.sh
tools/tpm2_createpolicy.c
tools/tpm2_unseal.c

This pull request does some refactor on build_policy() so the function is generic and can be moved to PCR lib to be reused by other tools. For start it's used by tpm2_unseal but I believe it can also be used by other tools (e.g: tpm2_nvread that needs the same as mentioned in issue #348).
By using build_policy(), the raw PCR hashes file is parsed correctly so this set also fixes issue #364.
To easy reviewing, I've tried to split the changes in as many logical steps as possible so each patch does only one thing.

Refactor build_policy() and reuse it from tpm2_unseal tool (and also fix issue #364)

---

man/tpm2_create.8.in
tools/tpm2_create.c

The TCG specification is clear that only the TPM_ALG_KEYEDHASH algorithm
can be used when the user provides part of the the sensitive data.
The tpm2_create tool behaves according to the specification, but it may
not be clear to the users why it fails, unless are already familiar with
the specs. Make the tool gracefully fail and also add a note to man page.
Fixes: #369

tpm2_create: check if keyed-hash algorithm was used when sealing data

---

test/system/test_tpm2_nv.sh

TPM_PT_NV_INDEX_MAX contains the maximum NV index size that is supported by a TPM. Larger values will always be rejected.
With this change, the test should be compatible with all TPM implementations, which is especially relevant for #335.

Use maximum supported size for large file size test

---

test/system/test_tpm2_quote.sh

The qualifying data in a TPM2_Quote call may not be larger than the maximum size of a digest.
Contributes to #335.

Restrict nonce length to TPM_PT_MAX_DIGEST

---

man/tpm2_getmanufec.8.in
test/system/test_tpm2_getmanufec.sh
tools/tpm2_getmanufec.c

Currently, the -E option will fail when -E is not specified:
$ tpm2_getmanufec -g 0x01 -O -N -U -f test_ek.pub -S https://ekop.intel.com/ekcertservice/
...
ERROR: Could not open file for writing: "(null)"
Make -E option, optional by making the default stdout. This requires
modifying the tool to stop outputing other information to sdout,
which is currently unused output in the test suite.
Make the information only output when verbose is enabled, this
includes curl verbose information.
Update errors and warnings to go to stderr.
Fixes: 361

tpm2_getmanufec: handle output more gracefully

---

lib/tpm2_nv_util.c
lib/tpm2_nv_util.h
lib/tpm2_policy.c
lib/tpm2_util.c
lib/tpm2_util.h
test/unit/test_string_bytes.c
test/unit/test_tpm2_nv_util.c
tools/tpm2_nvdefine.c
tools/tpm2_nvlist.c

Instead of outputting the raw hex, which sucks for humans, output a nice name formatted nv attribute list. Add numerous tests to the unit testing library and update tpm2_nvlist.
Inspired by #348 
Example:
Old Output:
```
1 NV indexes defined.
0. NV Index: 0x1500016
{
Hash algorithm(nameAlg):11
The Index attributes(attributes):0xa000a
The size of the data area(dataSize):32
Authorization Policy for R/W/D:
}
```
New Output:
```
1 NV indexes defined.
0. NV Index: 0x1500016
{
Hash algorithm(nameAlg):11
attributes: ownerwrite|policywrite|ownerread|policyread(0xa000a)
The size of the data area(dataSize):32
Authorization Policy for R/W/D:
}
```

NV Attribute friendly name output

---

man/tpm2_pcrlist.8.in
manual

The algorithm word was misspelled in a couple of places, fix it.

manual: fix typo for algorithm

---

test/unit/test_tpm2_alg_util.c

Now that PR: https://github.com/01org/tpm2-tss/pull/494
is merged, fix up the tests to stop having to convert
the expanded macro values to a hex string via snprintf.
Now the macros can be stringified and used directly.

test: tpm2_alg_util clean up

---

man/tpm2_create.8.in
man/tpm2_createprimary.8.in

The manual pages for the tpm2_create and tpm2_createprimary tools are
missing a line break between options, which makes harder to read them.

manual: add missing line breaks in tpm2_{create,createprimary} pages

---

Makefile.am

sbin is for critical startup utilities. tpm2-tools should
be in regular bin.
Verified by setting DESTDIR=~/tmp and that make install sends
it to /tmp/usr/local/bin.
Fixes: #404

autotools: move tools from sbin to bin

---

lib/files.c
lib/files.h
tools/tpm2_activatecredential.c
tools/tpm2_certify.c
tools/tpm2_create.c
tools/tpm2_encryptdecrypt.c
tools/tpm2_evictcontrol.c
tools/tpm2_hmac.c
tools/tpm2_load.c
tools/tpm2_quote.c
tools/tpm2_readpublic.c
tools/tpm2_rsadecrypt.c
tools/tpm2_rsaencrypt.c
tools/tpm2_sign.c
tools/tpm2_unseal.c
tools/tpm2_verifysignature.c

The coding standard document says that a function that is exported should
be prefixed with the source file (or object module) name it was defined.
But file_load_tpm_context_from_file() is using file as prefix instead of
files. This is trivial but since there is a bug filled for this, fix it.
Fixes: #367
Reported-by: 刘群 <qunliu@zyhx-group.com>

lib: Rename file_load_tpm_context_from_file() to follow coding standard

---

tools/tpm2_dump_capability.c

value needs to be converted to float before doing the division, otherwise the minor version will be truncated to zero.

tpm2_dump_capability: Display specification minor version correctly

---

.ci/coveralls-upload.sh
.ci/travis-build-and-run-tests.sh
.travis.yml

Coveralls was not being updated as ENABLE_COVERAGE was exported in
a seperate environment and not preserved when invoking the coveralls
upload script. Move the coveralls upload invocation within that
environment.

coveralls: fix uploads

---

CHANGELOG

A new option was added to supress the tools output, but a note was not
added to the CHANGELOG.

CHANGELOG: Document that new --quiet option was added

---

Makefile.am
man/alg-common.troff
man/alg-notes-common.troff
man/tpm2_akparse.8.in
man/tpm2_getpubak.8.in
man/tpm2_getpubek.8.in
man/tpm2_quote.8.in

For new users it is helpful to know which key lengths and parameters are
actually produced by tpm2_getpub*, also what kind of data is output for
public key portions and by tpm2_akparse.

man pages: include some clarifications and fix some typos

---

man/tpm2_hash.8.in

The commit 6388831 ("tpm2_hash: drop -I option") changed tpm2_hash tool
to get the data to hash from either the standard input or a file. So it
remove the -I option.
But forgot to update the example in the man page. While being there, do
as other examples in man pages and show a specific command instead of a
generic one.
Fixes: #441

tpm2_hash: Drop -I option in man page example

---

test/system/test_all.sh
test/system/test_tpm2_pcrevent.sh

This pull request contains two small fixes for tests. The first commit removes a duplicate in test_all.sh for test_tpm2_evictcontrol.sh and the second one fixes an issue that causes test_tpm2_pcrevent.sh to fail when not executed from test_all.sh

A couple of fixes for tests

---

Makefile.am
configure.ac

The md2man-roff tool is required to generate roff man pages from markdown
for some tools, but this may not be available on some systems. Instead of
making the build to fail, just don't attempt to generate these man pages.
Fixes: #447
Reported-by: Philip Tricca <philip.b.tricca@intel.com>

build: Don't generate man pages from markdown if md2man-roff isn't found

---

test/system/test_all.sh
test/system/test_tpm2_getrandom_func.sh

While porting the tpm2_getrandom tool to the new options parsing logic, I noticed that the test_tpm2_getrandom_func.sh has been broken for some time due a silly typo.
This pull request fix this issue and also adds the test to the test_all.sh coverage.

A couple of fixes for tpm2_getrandom tests

---

test/system/test_tpm2_getrandom_func.sh

The tpm2_getrandom_func test leaves a lot of temporary files around,
make sure those are cleaned up correctly when the script exits.

tpm2_getrandom: cleanup temporary files created by test

---

Makefile.am
lib/tpm2_options.c
tools/tpm2_listpersistent.c
tools/tpm2_load.c
tools/tpm2_loadexternal.c
tools/tpm2_makecredential.c
tools/tpm2_nvdefine.c
tools/tpm2_nvlist.c
tools/tpm2_nvread.c
tools/tpm2_nvreadlock.c
tools/tpm2_nvrelease.c
tools/tpm2_nvwrite.c
tools/tpm2_tool.c

This is yet another set of tools ported to the new option handling code. While porting this I noticed that my previous ports had some issues:
* I wrongly removed the LOG_ERR() usage in the .on_option handlers because I misunderstood that were not safe to use at some point (but only LOG_INFO and tpm2_tool_output shouldn't be use there).
* I forgot to remove the <getopt.h> header inclusion that's not needed anymore since tools now include "tpm2_options.h".
* Didn't check if tools really needed the sapi_context to be in the context struct. In most cases just the tpm2_tool_onrun() function should pass it to the functions that interact with the TPM.
I'll fix those and propose a patch on top of tpm2-option-revamp.
BTW, I notice a couple of bugs in tpm2_{option,tools}.c so I provide a fix up as …

Another set of tools ported to the new option handling

---

test/system/test_tpm2_nv.sh

The test TPM_PT_NV_INDEX_MAX fixed TPM2 property to know the NV index data
area maximum size:
$ tpm2_dump_capability -c properties-fixed | grep TPM_PT_NV_INDEX_MAX | sed -r -e 's/.*(0x[0-9a-f]+)/\1/g'
0x00000800
And then passes this value to the head command as a -c option argument:
$ base64 /dev/urandom | head -c 0x00000800
head: invalid number of bytes: ‘0x00000800’
This is making the test to fail, but since the exit code for the mentioned
command is not checked, it's still reported as if the test succeed.
$ ./test_tpm2_nv.sh
70 6c 65 61 73 65 31 32 33 61 62 63 0a
000000: e8 5d ca 86 cc 7f 00 00 e8 5d ca 86 cc 7f 00 00  .].......]......
000010: 30 e0 87 5a 79 55 00 00 05 00 00 00 00 00 00 00  0..ZyU..........
0. NV Index: 0x1500018
release the nv index OK!
head: invalid number of bytes: …

test: fix tpm2_nv.sh passing a hex number as head command -c argument

---

README.md

The `manual` has been removed in c9b3d9a34aec1d16520d174dac275e69302ed53b, so remove reference to it.

README.md: remove left over reference to "manual"

---

tools/tpm2_nvread.c

The first argument is the destination which needs to be offset based on
how much has already been read. The third argument is the size that we
should be reading. Correct the spelling of the variable name.
Signed-off-by: Doug Goldstein <cardoe@cardoe.com>

tpm2_nvread: fix memcpy() arguments

---

test/system/test_tpm2_nv.sh

There's no test for tpm2_nvreadlock, add a test case for it to the NV
test. Also print a success message if test finish successfully like's
done in the other tests.
Fixes: #462

test: add a tpm2_readlock test case to tpm2_nv.sh

---

man/tcti-options.troff

Commit 1cb24d62d6b ("option fixing: move to single getopt") reworked how
the options are handled by the tools, but it also changed how the TCTI
specific options are passed to the TCTI initialization code.
The man pages were not updated and still list the old way to specify the
TCTI specific options, users reading the man page will face this issue:
$ tpm2_pcrlist -L sha1:7 -T device -d /dev/tpm0
tpm2_pcrlist: invalid option -- 'd'
ERROR: Unknown Argument: d
Update man pages so users know that they instead need to do following:
$ tpm2_pcrlist -L sha1:7 -T device:/dev/tpm0
Bank/Algorithm: sha(0x0004)
PCR_07:6d7206871c9c6f38ad3997baceebee95dadec04d

man: update TCTI options man page according to new options handling

---

tools/tpm2_nvread.c

The nv_read() function queries the NV index public data size to know how
much bytes have to be read. But the reported size may be bigger than the
actual size read from the NV area.
So instead of using the reported NV area public data size for printing,
use the read NV area size.
For example using the NV are public data size may lead to the following:
$ echo -n foobar > data.txt
$ hexdump -C -v data.txt
00000000  66 6f 6f 62 61 72                                 |foobar|
00000006
$ tpm2_nvwrite -x 0x1500018 -a 0x40000001 -f data.txt
66 6f 6f 62 61 72
$ tpm2_nvread -x 0x1500018 -a 0x40000001 -s 6 -o 0
data_size 32 ctx.size_to_read 0 data_offset 6
000000: 66 6f 6f 62 61 72 00 00 c8 ad 07 91 78 7f 00 00  foobar......x...
000010: 10 60 b2 e9 92 55 00 00 05 00 00 00 00 00 00 00 …

tpm2_nvread: only print the number of bytes read

---

test/system/test_tpm2_nv.sh

If the test is interrupted, then temporary files may not be cleaned up
correctly. Ensure that the files are always removed on the script exit.

test: make sure temp files are cleaned up on test_tpm2_nv.sh exit

---

man/tpm2_evictcontrol.1.md

The specification says "If objectHandle is a persistent object, then the
call evicts the persistent object" and "if objectHandle is a persistent
object handle, then it shall be the same value as persistentHandle".
So the tool is doing the correct thing by requiring both the object and
persistent handles to be defined and being the same to evict an object.
But this isn't documented in the tool man page and it may not be evident
to people not familiar with the TCG TPM specification.
While being there, remove a -X option from one of the examples since the
tpm2_evictcontrol tool doesn't have one.

man: explain in tpm2_evictcontrol page how objects are evicted

---

man/tpm2_evictcontrol.1.md
tools/tpm2_evictcontrol.c

The TCG TPM specification requires the same handle to be provided for both
objectHandle and persistentHandle but this implementation detail leaked in
the tool and so users need to provide both a -S and -H options to evict an
object.
But the tool can be smarter, the handles are not just opaque values but
they encode information. The first byte is the TPM_HT (Handle Type) and
for persistent objects handles this is TPM_HT_PERSISTENT (0x81).
Fixes: #492

tpm2_evictcontrol: make tool smarter to not require -S to evict objects

---

man/tpm2_load.1.md
tools/tpm2_load.c

The tool requires the option for a file path to store the structure name
of the object, but this shouldn't really be a required option. In fact,
the whole option checking seems bogus so just check for the options that
should be required and not the ones that should be optional.
While being there, make this clear in the man page as well.
Fixes: #494

tpm2_load: don't make -n option to be required

---

man/tpm2_listpersistent.1.md
tools/tpm2_listpersistent.c

This is a v2 of PR #490. As suggested by @williamcroberts, it instead improves the output format used by the tool and also adds a -g and -G options to filter by the hash and key algorithms like's done in other tools (i.e: tpm2_pcrlist).

tpm2_listpersistent enhancements

---

tools/tpm2_listpersistent.c

The tool is using the tpm2_alg_util_from_optarg() function to convert from
the pretty names provided by the user to the hexadecimal algorithm values.
But the same function is used to convert both key and hash algorithms and
so using a key as a hash and viceversa was wrongly taken as correct value.

tpm2_listpersistent: check that -g and -G correct values were provided

---

lib/tpm2_util.h
tools/tpm2_createprimary.c

Fix for hierarchy authentication password overwriting the primary object's authentication password

---

test/system/test_tpm2_unseal.sh

Creating a primary key may take a lot of time, specially when using the
RSA algorithm. Since for test we can use any algorithm, use ECC instead
to speed up the test on most systems.
While being there, do other cleanups like using pretty names instead of
hexadecimal values and use the -E option in the tpm2_create command so
the needed object attributes are set by the tool.

test: use ECC algorithm instead of RSA for primary key in tpm2_unseal

---

man/tpm2_dump_capability.1.md
tools/tpm2_dump_capability.c

Add option to dump elliptic curves supported by the device.
Corresponding capability selector is TPM_CAM_ECC_CURVES.
Signed-off-by: Anton Gerasimov <anton@advancedtelematic.com>

tpm2_dump_capability: add dumping ECC curves

---

lib/tpm2_alg_util.c
test/system/test_tpm2_create.sh
test/system/test_tpm2_encryptdecrypt.sh
test/system/test_tpm2_hmac.sh
test/system/test_tpm2_pcrextend.sh
test/system/yaml_get.py
test/unit/test_tpm2_alg_util.c

The specification makes it clear that both TPM_ALG_SHA and TPM_ALG_SHA1
refer to the SHA-1 algorithm, but the algorithms table has entries for
both even when they have the same hexadecimal value (0x0004).
That means that TPM_ALG_SHA1 will never be matched, since a match will
happen with TPM_ALG_SHA before. So all tools are currently printing a
"sha" string when a "sha1" should be printed instead:
$ tpm2_dump_capability -c algorithms | grep sha
TPMA_ALGORITHM for ALG_ID: 0x4 - sha
TPMA_ALGORITHM for ALG_ID: 0xb - sha256
After this patch:
$ tpm2_dump_capability -c algorithms | grep sha
TPMA_ALGORITHM for ALG_ID: 0x4 - sha1
TPMA_ALGORITHM for ALG_ID: 0xb - sha256

tpm2_alg_util: remove duplicated SHA-1 entry in algorithms table

---

README.md

The "A Practical Guide to TPM 2.0" book has an open access book, which
means that the content is freely available to anyone. So add a link to
the site where the book can be downloaded.

README: add link to A Practical Guide to TPM 2.0 book

---

man/tpm2_nvread.1.md
tools/tpm2_nvread.c

Add "out-file" option (-f) to save data to a user-specified file in
addition to hexdump()-ing to screen.
Signed-off-by: Haris Okanovic <haris.okanovic@ni.com>

tpm2_nvread: Add "out-file" option (-f)

---

tools/tpm2_createpolicy.c

The tpm2_tool_output() doesn't add a new line character like the LOG_*()
macros, add one so the session handle information is printed correctly.

tpm2_createpolicy: add new line to extend policy session handle output

---

.travis.yml

The commit fd034b2fe2f0 ("man: use pandoc instead of md2man for man pages
generation") replaced the tool used to generate the man pages. But forgot
to update the Travis CI yaml, to install pandoc so man pages are created.
Using pandoc will also have the side effects of getting rid of the ruby
version manager shenanigans that were in the Travis configuration file.

travis: install pandoc to build man pages

---

Makefile.am
lib/tpm_kdfa.c
tools/main.c
tools/tpm2_dump_capability.c
tools/tpm2_listpcrs.c

This pull request cherry picks the following fixes from the master branch:
c2586d4116b2 ("tpm2_listpcrs: use TPM2_GetCapability to determine PCRs to read")
433a1e44f362 ("listpcrs: remove one redundant call to tpm get cap")
ada4c20d23d9 ("listpcrs: fix for unsupported/disabled alg in -L")
9466263446fb ("build: use supported comment to suppress GCC7 fallthrough warning")
5cee30cbc3da ("kdfa: allow to build with OpenSSL 1.1.x")
Plus a patch suggested by @snits that fixes the man pages generation to include information about the tabrmd TCTI. This fix is not in the master branch because doesn't apply anymore.
We have these fixes in our 2.1.0 tpm2-tools package, so it would be nice to have it in the 2.X branch and release a new minor version so we can drop them.

Fixes for 2.1.0 (2.X branch)

---

tools/tpm2_createprimary.c

This does the same as tpm2_create.

tpm2_createprimary: support to print the object attributes

---

test/system/test_tpm2_activecredential.sh
test/system/test_tpm2_akparse.sh
test/system/test_tpm2_createpolicy.sh

The -f parameter already suppresses the common but harmless error messages,
e.g. file not found, so this is unnecessary.
Pointed out by @martinezjavier in #555.

test/system: remove pipe to /dev/null for rm -f calls

---

tools/tpm2_nvread.c

nvread is not understanding the "-f" parameter because the
option is missing from the optstring. Add it to the optstring.
Signed-off-by: Fabien Parent <fparent@baylibre.com>

nvread: fix missing 'f' in optstring

---

test/system/test_tpm2_createpolicy.sh

This fix resolves the following errors:
./test_tpm2_createpolicy.sh: line 57: [[:
9872964b9b40cdd0363fcd6af8c267c9cb34200b: value too great for base
(error token is "9872964b9b40cdd0363fcd6af8c267c9cb34200b")
Failure: Creating Policy Digest with PCR policy for index 0 and sha1
pcr index hash

test_tpm2_createpolicy.sh: fix the compare between PCR 0 and hex value

---

.travis.yml
Makefile.am
configure.ac
lib/tpm2_util.h
man/tpm2_import.1.md
test/system/test_tpm2_import.sh
tools/tpm2_import.c

TODO:
1. --parent-key-public should be optional, just read it in if not specified.
2. I don't understand the difference between the imported private, public and
symetric. Is this limited to just importing an AES-128 key? If so why do I
need a private and public key?
3. Should the mandatory inputs be options or arguments?
Limited to importing a symmetric AES-128 key.
^^^
Is this true?
Add tests.

[WIP] tpm2_import: new tool that uses tpm2_import to import a key

---

tools/tpm2_import.c

This pull request contains fixes for the tpm2_import tool. I noticed these while fixing a build error with OpenSSL 1.1.0.
@idesai could you please review these since you are the author of the tpm2_import tool.
@mgerstner I would really appreciate your review too, specially for the OpenSSL API usage.

tpm2_import: fix build error with OpenSSL 1.1.0 and other issues

---

test/system/test_helpers.sh
test/system/test_tpm2_create.sh
test/system/test_tpm2_createprimary.sh

Changelog:
- V4
* Directly query the supported hash algs in form of mixed naming scheme from TPM.
* The test results on my system:
```
$./test_tpm2_create.sh ; echo $?
0
$./test_tpm2_createprimary.sh  ; echo $?
0
```
- V3
* Query the supported hash algs and check whether TPM supports the specified alg before testing it.
* Place the common piece in test_helpers.sh.
* The test results on my system:
```
$./test_tpm2_create.sh 
Ignore testing the unsupported hash algorithm "sha384"
$./test_tpm2_createprimary.sh 
Ignore testing the unsupported hash algorithm "0x0C"
```

[V4] test: don't use sha384 hash algorithm in tpm2_createprimary test

---

test/system/test_tpm2_createpolicy.sh

For the simulator, PCR0 contains the value 0x03, but this is not necessarily the case for other TPM implementations. Therefore, use a file to supply the expected PCR value to tpm2_createpolicy, so that the expected policy digest remains unchanged and the test passes for all TPMs.
We tried a similar approach some time ago. I've now reimplemented it, but had no chance to test it, so I hope that this works :)
Fixes #551, #335.

test_tpm2_createpolicy.sh: use file to supply expected PCR value

---

lib/context-util.c

In case where sapi_ctx_init fails in sapi_init_from_options, free tcti_ctx.
This is specific to the 2.X branch.

lib: clean up potential memory leak

---

.travis.yml

commit c54e876b906361984bf7e6d65e1b28525fcac425
in the tss introduces a regression in the tools.
The marshaling routine is expecting a non-null src
buffer, and using an empty src buffer results in
more invalid issues.
For now, while we trouble shoot, freeze the tss on this
commit.

[REVERTME] travis: get build working

---

Makefile.am
lib/tpm2_errata.c
lib/tpm2_errata.h
test/system/test_helpers.sh
test/system/test_tpm2_create.sh
test/system/test_tpm2_encryptdecrypt.sh
test/system/test_tpm2_quote.sh
tools/tpm2_create.c
tools/tpm2_import.c
tools/tpm2_tool.c

The TPM errata should be addressed and handled transparently by design.
In order to handle an errata, the errata info should be recorded in
tpm2_errata.[ch], and the affected tools need to query the errata
handler with a pre-defined errata number and to-be-fixed contents.
During the initialization, the TPM spec and errata info will be
remembered and used to check the errata query issued by the tools.

[V4] tpm2_errata: implement a generic handling for errata

---

lib/tpm2_errata.c
lib/tpm2_errata.h
tools/tpm2_tool.c

When the tpm version has no errata, don't print the error
messsages.
Correct Doxygen comments.

tpm2_errata: cleanup error messages

---

tools/tpm2_unseal.c

The tool currently checks if both the -L and -F options were defined and
only builds a PCR policy session for authentication if that's the case.
But the tpm2_unseal man page says that the -F option is not required, if
this isn't defined then the current PCR values are used to build the PCR
policy used for authorization to unseal the data.
So honor the man page says and don't make the -F option to be required,
instead just always pass raw_pcrs_file to tpm2_policy_build(). If it's
NULL, then this function reads the current PCR values instead of trying
to use the values that are defined in a file.

tpm2_unseal: make -F optional to allow using current PCR values for auth

---

man/tpm2_getcap.1.md
tools/tpm2_getcap.c

handles-hmac-session and handles-policy-session should be replaced by
handles-loaded-session and handles-saved-session. According to the
spec, TPM_HT_LOADED_SESSION and TPM_HT_HMAC_SESSION have the same
value, as do TPM_HT_SAVED_SESSION and TPM_HT_POLICY_SESSION, but they
are used in different context.

[V0] tpm2_getcap: correct option names

---

configure.ac

The bash shell sets the BASH variable with the full path name used to
execute the current instance of bash. But the configure script uses it
to attempt to check if the bash binary is present on a given system.
The configure script uses the #!/bin/sh shebang, so on a system where
/bin/sh is the bash shell, the configure script will fail to find the
bash binary due BASH being set to /bin/sh:
checking for bash... /bin/sh
configure: WARNING: Required executable bash not found, system tests require a bash shell!
Use instead a variable name that isn't an internal one used by bash.

configure: fix check for bash shell

---

.travis.yml
test/system/test_tpm2_activecredential.sh
test/unit/test_tpm2_password_util.c

The CI build is failing since Travis tries to download OpenSSL packages
that are not longer available. Update the configuration file to fetch
the latest version of these packages.

travis.yml: fix issue with trying to download unavailable OpenSSL pkgs

---

Makefile.am

The missing header files and man pages were fixed after the 2.X
release. Backport that fix.
Fixes: #601

Makefile.am: fix make distcheck

---

CHANGELOG.md
man/tpm2_nvlist.1.md
test/system/test_tpm2_nv.sh
tools/tpm2_nvlist.c

Only print the written data when -V is specified and print
the data in an xxd compatable hexdump.
Fixes: #605

tpm2_nvwrite: only print data on verbose

---

tools/tpm2_tool.c

log_set_level() was never being called when verbose
was enabled. So set it when verbose is enabled.
This fixes LOG_INFO not showing up.

log: fix verbose option

---

lib/tpm2_options.c
lib/tpm2_options.h
man/common/options.md
tools/tpm2_tool.c

Disable the application of errata fixups by default and require the user to enable them.
Fixes #622

tpm2_errata: enable with -Z

---

Makefile.am
test/system/test_tpm2_dictionarylockout.sh
test/system/test_tpm2_quote.sh
test/unit/test_tpm2_errata.c

Add tests to validate that the errata routines are functioning.

test: add unit tests for tpm2_errata

---

tools/tpm2_nvwrite.c

Do not output data as it's written.

tpm2_nvwrite: drop written data output

---

lib/rc-decode.c
tools/tpm2_rc_decode.c

This pull request adds support for the tpm2_rc_decode tool to decode response codes sent by the Resource Manager layer.

[for 3.X] Add support for Resource Manager level errors to tpm2_rc_decode tool 

---

lib/rc-decode.c
tools/tpm2_rc_decode.c

This pull request adds support for the tpm2_rc_decode tool to decode response codes sent by the Resource Manager layer.

Add support for Resource Manager level errors to tpm2_rc_decode tool

---

test/system/test_tpm2_listpersistent.sh

The tool is exercised as a part of the tpm2_getmanufec integration test,
but there should also be a test specific for the tpm2_listpersistent tool.
Fixes: #461

[for 3.X] tpm2_listpersistent: add integration test

---

lib/tpm2_util.h
tools/tpm2_encryptdecrypt.c

The TPM only uses the lower 12 bits from the 32 bits of TPM_RC, the other
layers uses some of the higher unused 20 bits to indicate from which layer
of the stack the error comes from.
So mask the low-order 12 bits of the TPM_RC variable instead comparing TPM
response codes directly. There's no need to mask when the check is against
TPM_RC_SUCCESS, since in this case the upper 20 bits are going to be zero.
Fixes: #646

[for 3.X] lib: mask TPM_RC to only get the bits set by the TPM

---

.travis.yml
lib/tpm2_alg_util.c

The TPMU_HA is just a union data type, so instead of attempting to copy
.na field, copy the union since both refer to the same memory location.
This also allows the tpm2-tools to be built against the tpm2-tss 1.x
since the TPMU_HA union doesn't have a .na field in that version. So it
prevents the following build error:
lib/tpm2_alg_util.c: In function ‘tpm2_extract_plain_signature’:
lib/tpm2_alg_util.c:348:33: error: ‘TPMU_HA {aka union <anonymous>}’ has no member named ‘na’
memcpy(buffer, &hmac_sig->na, *size);
^~
make: *** [Makefile:1871: lib/tpm2_alg_util.o] Error 1

lib: just copy the TPMU_HA union instead of copying its member

---

test/system/test_tpm2_listpersistent.sh

The tool is exercised as a part of the tpm2_getmanufec integration test,
but there should also be a test specific for the tpm2_listpersistent tool.
Fixes: #461

tpm2_listpersistent: add integration test

---

tools/tpm2_rsaencrypt.c

Based on argument ordering and getopt handling, the code was getting lucky and
actually properly grabing the input file at argv[1]. However, the first
item in the array is really argv[0].
A result could be that the input file is NULL, which means read data
from stdin and the tool will hang.
Fixes: #664

tpm2_rsaencrypt: fix file argument

---

man/tpm2_createpolicy.1.md
tools/tpm2_createpolicy.c

The new option -S, associated with either -e or -a option, allows to
save the session context to a file.

tpm2_createpolicy: support to save session context with the option -S

---

lib/tpm2_util.h
tools/tpm2_encryptdecrypt.c

The TPM only uses the lower 12 bits from the 32 bits of TPM_RC, the other
layers uses some of the higher unused 20 bits to indicate from which layer
of the stack the error comes from.
So mask the low-order 12 bits of the TPM_RC variable instead comparing TPM
response codes directly. There's no need to mask when the check is against
TPM_RC_SUCCESS, since in this case the upper 20 bits are going to be zero.
Fixes: #646

lib: mask TPM_RC to only get the bits set by the TPM

---

test/system/test_tpm2_encryptdecrypt.sh
tools/tpm2_encryptdecrypt.c

tpm2_encryptdecrypt takes a -D argument to indicate to the
tool to perform a decrypt operation. The option currently
requires an argument of YES or NO. Remove this requirment
and make the default operation encrypt and the -D option
trigger a decryption.
No update to the manpage is required, as this change places it
in line with the man page.
Fixes: #614

tpm2_encryptdecrypt: drop -D YES|NO argument

---

Makefile.am
configure.ac

This change is inspired by Andreas Fuchs enabling the silent-rules option
by default on tpm2-tss. The output is much nicer and one can have the old
output anyways by either disabling the silent-rules option or "make V=1".

configure.ac: enable silent-rules configure option by default

---

man/tpm2_unseal.1.md

The manpage had a copy+paste error when porting the
manpages to markdown. Correct this.
Fixes: #670

man/tpm2_unseal: correct manpage

---

.travis.yml
README.md
lib/tpm2_options.c
tools/tpm2_listpersistent.c

coverity_scan builds are failing with API access issues:
https://travis-ci.org/intel/tpm2-tools/builds/312695074
Error:
Coverity Scan analysis selected for branch coverity_scan.
Coverity Scan API access denied. Check $PROJECT_NA
The project name in Coverity was accidnetally renamed and the
project public key likely changed with the project rename/move,
so re-encrypt the coverity scan token.

coverity: fix scan issue

---

Makefile.am

The LICENSE file that's present in the source code is not distributed in the
tarball generated by the make dist target. Including full license text makes
it easier for people to comply with the desired license terms.

Makefile.am: Add LICENSE in tarball generated by the make dist target

---

Makefile.am

The LICENSE file that's present in the source code is not distributed in the
tarball generated by the make dist target. Including full license text makes
it easier for people to comply with the desired license terms.

[for 3.0] Makefile.am: Add LICENSE in tarball generated by the make dist target

---

Makefile.am

These files should also be included in the tarball generated by make dist.

[for 3.0] Makefile.am: include rest of the markdown files to the generated tarball

---

Makefile.am

These files should also be included in the tarball generated by make dist.

Makefile.am: include rest of the markdown files to the generated tarball

---

.ci/travis-tss-install.sh
.travis.yml
CHANGELOG.md

Lots of empty commits, but this forces a sync between the two branches where it matters and gets git describe version on master reporting 3.0 as the nearest tag.

merge 3.X into master

---

Makefile.am

The integration tests are not included in the tarball generated by the
make dist target.

[for 3.x] Makefile.am: include integration tests to generated tarball

---

Makefile.am

The integration tests are not included in the tarball generated by the
make dist target.

Makefile.am: include integration tests to generated tarball

---

Makefile.am
man/tpm2_changeauth.1.md
man/tpm2_clear.1.md
test/system/test_output_formats.sh
test/system/test_tpm2_certify.sh
test/system/test_tpm2_changeauth.sh
test/system/test_tpm2_encryptdecrypt.sh
test/system/test_tpm2_evictcontrol.sh
test/system/test_tpm2_flushcontext.sh
test/system/test_tpm2_getmanufec.sh
test/system/test_tpm2_getpubak.sh
test/system/test_tpm2_hmac.sh
test/system/test_tpm2_listpersistent.sh
test/system/test_tpm2_load.sh
test/system/test_tpm2_loadexternal.sh
test/system/test_tpm2_nv.sh
test/system/test_tpm2_quote.sh
test/system/test_tpm2_readpublic.sh
test/system/test_tpm2_rsadecrypt.sh
test/system/test_tpm2_rsaencrypt.sh
test/system/test_tpm2_sign.sh
test/system/test_tpm2_unseal.sh
test/system/test_tpm2_verifysignature.sh
tools/tpm2_changeauth.c
tools/tpm2_clear.c

This PR proposes a few changes (as discussed in PR#696) :
- Add a new tpm2_clear tool whose goal is to provide a way to clear a TPM2 - i.e. remove all (owner + endorse + lockout) authorization values from it.
- Rename tpm2_takeownership to tpm2_changeauth and remove option -c from the newly named tool (since option -c is handled by tpm2_clear). 
Please note that I did not change CHANGELOG.md as it seems this file is a bit outdated (and I frankly don't know where I should explain these changes).

tpm2_clear: add tool and rename tpm2_takeownership

---

tools/tpm2_nvread.c
tools/tpm2_nvwrite.c

Currently if a tpm device supports a max nv buffer size greater than
tss supports we can get buffer overflows. Check the size returned by
the tpm device, and use the min of that and the max supported by tss.

nv: don't exceed max nv buffer size for TSS

---

.ci/travis-tss-install.sh
.travis.yml

Commit 590ed9d2ed21 ("travis: fix autconf dependency on tss") fixed the
tpm2-tss dependency with the AX_CODE_COVERAGE macro, by fetching latest
autoconf-archive and copying the macro into the tpm2-tss source code m4
directory.
But now tpm2-abrmd also uses the macro for code coverage and so instead
of duplicating the same logic, install autoconf-archive in the machine.
While being there, clone the tpm2-{tss,abrmd} repos from the latest URL.

travis.yml: build and install autoconf-archive from source

---

tools/tpm2_getmanufec.c

Commit cc51f9fe188a ("tpm2_getmanufec: fix a memory leak") fixed a memory
leak in TPMinitialProvisioning(), but after this change a pointer that is
already NULL is attempted to be freed.
This doesn't matter since free(3) is a no-op if a pointer is already NULL
but still it's a good practice to free the resources in the inverse order
than were allocated and also makes no sense to attempt to free a NULL ptr.
Reported-by: Jerry Snitselaar <jsnitsel@redhat.com>

tpm2_getmanufec: don't attempt to free a pointer that is already NULL

---

man/tpm2_dump_capability.8.in

Option "--c | --capability" should be "-c | --capability"
Rebased to tpm2-tools branch 2.X.
See also: PR https://github.com/intel/tpm2-tools/pull/735

Fix typo mistake in tpm2_dump_capability.8.in

---

tools/tpm2_create.c

Commit cd3a1c72b278 ("tpm2_create: rename options for public and sensitive
portions of the object") renamed the o and O options to u and r so they're
consistent with other tools, but forgot to rename the flags used for these.

tpm2_create: change o and O flags to reflect the tool options

---

Makefile.am
man/tpm2_clearlock.1.md
test/system/tests/clearlock.sh
tools/tpm2_clearlock.c

The tpm2_clearlock tools is used to authorize/forbid the use of
tpm2_clear. It used TPM2_ClearControl() to set or clear disableClear
(when disableClear is set it's not possible to call TPM2_Clear()).
One can check for the status of disableClear using the tpm2_getcap tool.
The clearlock.sh test check for the behavior of this newly added tool.
Fixes: #710
Signed-off-by: Emmanuel Deloget <logout@free.fr>

tpm2_clearlock: add tool

---

lib/tcti/tpm2_tools_tcti_device.c
lib/tcti/tpm2_tools_tcti_socket.c

Both the device and socket TCTI config structure changed upstream.

tcti: Account for removal of log stuff from TCTI config structures.

---

lib/tpm2_options.c
lib/tpm2_options.h
tools/tpm2_tool.c

When the -h / --help option is passwed to the tools, their man pages are
shown. But the tools should be allowed to be used even on machines where
the man pages were not installed.
Currently the tools print a usage text when are executed with no options
but the -h option should be available for those setups and also some of
the tools allow them to be executed with no options (i.e: when using the
standard input to read data).
So add a configure flag to allow the tools -h option to not show the man
pages and install fallback to print the summary text usage instead.
Suggested-by: Emmanuel Deloget <logout@free.fr>

configure.ac: add --with-manpages-help option

---

.travis.yml

The tpm2-tss simulator TCTI library uses symbols from Uriparser library,
so install its dev package in the Travis CI instance to build tpm2-tss.

travis.yml: install liburiparser-dev package

---

man/tpm2_sign.1.md
test/system/tests/sign.sh
tools/tpm2_certify.c
tools/tpm2_changeauth.c
tools/tpm2_getmanufec.c
tools/tpm2_load.c
tools/tpm2_loadexternal.c
tools/tpm2_makecredential.c
tools/tpm2_nvdefine.c
tools/tpm2_nvread.c
tools/tpm2_nvwrite.c
tools/tpm2_pcrevent.c
tools/tpm2_quote.c
tools/tpm2_readpublic.c
tools/tpm2_rsadecrypt.c
tools/tpm2_sign.c
tools/tpm2_unseal.c

Intruct tpm2_sign to allow it to handle signing pre-computed hashes. This fixes #753. 
When one wants to use option -D he needs to respect a few conditions: 
* the digest file size should match the selected halg
* the selected signing key shall not be restricted
When option -D is used, options -m and -t are (silently) ignored. 
The patch is bundled with a cleaning patch that remove optarg from the tools code (optarg is a global set by getopt_long() and passed to the tools on_option() as argument value ; thus, it's always available using variable value, and one may consider that optarg is, at this point, an implementation details that should not be shown to users). 
Best regards, 
-- Emmanuel Deloget

tpm2_sign : provide -D option to sign a pre-computed hash

---

lib/tpm2_options.c

For tools that takes no options and arguments, its struct tpm2_options is
NULL so trying to access it will lead to a NULL pointer dereference error.
This is checked in the main() function before calling tpm2_print_usage(),
but it was checked when tpm2_print_usage() was added as a fallback to the
--help option when executing the man pager fails.
Instead of relying of the caller to do the check, make tpm2_print_usage()
robust enough to cope with being called with a NULL struct tpm2_options.
After all, it makes no sense to print a usage text for a tool that takes
neither options nor arguments.
Reported-by: Emmanuel Deloget <logout@free.fr>

lib: fix tpm2_print_usage() when tools have no options/args

---

man/common/tcti.md

TCTi abrmd now supports both bus name and type parameters as introduced
in PR https://github.com/intel/tpm2-abrmd/pull/294
Update the TCTI man page documentation to reflect this.

tcti: add new config paramaters for abrmd

---

lib/tpm2_errata.c

Infineon SLB9665 (PT_REV 1.16) is affected by the errata
"Sign/decrypt attribute encoding" and the related test case thus
needs -Z option.
However, the test cases print lots of noises about more-data-available
because this tpm chip always responds more data available when the
requesting property is PT_FIXED. Digging into the internal, PT_VAR is
implied as the potentially available data.
More worse, launching test.sh -Z causes each test case generating the
noises.
The errata logic only requires the first few fields from PT_FIXED so
the check for more_data can be ignored in order to mute the noises
when the errata is applied.
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>

tpm2_errata: mute the noises when more data is available

---

lib/conversion.c
lib/tpm2_openssl.c
tools/tpm2_import.c

OPENSSL_VERSION_NUMBER is used to test the version of OpenSSL but this
test alone breaks the build with LibreSSL due to implicit declarations
of functions 'RSA_set0_key' and 'HMAC_CTX_free'.
Test if OpenSSL < 1.1.0 or LIBRESSL_VERSION_NUMBER is defined, instead.
Signed-off-by: Carlos Santos <casantos@datacom.ind.br>

Fix build with LibreSSL

---

lib/tpm2_policy.c

When a PCR selection has more than 8 selections, the pcrSelections
array was being indexed past its end.
Fixes: #778

Limit selected PCRs to 8

---

Makefile.am
lib/tpm2_hierarchy.c
lib/tpm2_hierarchy.h
man/tpm2_createprimary.1.md
man/tpm2_evictcontrol.1.md
man/tpm2_nvdefine.1.md
man/tpm2_nvread.1.md
man/tpm2_nvrelease.1.md
man/tpm2_nvwrite.1.md
test/system/tests/nv.sh
test/unit/test_tpm2_hierarchy.c
tools/tpm2_createprimary.c
tools/tpm2_evictcontrol.c
tools/tpm2_nvdefine.c
tools/tpm2_nvread.c
tools/tpm2_nvreadlock.c
tools/tpm2_nvrelease.c
tools/tpm2_nvwrite.c

Correct the handling of hierarchies in the NV related tools to use friendly names like "o" for the owner platform rather than the raw numerical format.
This also moves the parsing logic to a common routine, with unit tests.
Fixes: #512

Friendly Options for Hierarchy Specification

---

.travis.yml
man/common/footer.md
test/system/tests/tcti/abrmd/extended-sessions.sh

Hello, 
Here is a small PR whose goal is only to update the various github URLs that changes when the tpm2 projects went from the intel 'organization' to the tpm2-software 'organization'.
These are quite trivial changes (at least for the 'man' and the 'tests' commit as they have no impact on anything but printed text or comments ; the 'travis' one may need at least a check) that can be, if needed, squashed into a single commit. 
BR, 
-- Emmanuel Deloget

Fix various github URLs here and there

---

lib/tpm2_util.c
lib/tpm2_util.h
test/system/tests/listpersistent.sh
tools/tpm2_createprimary.c
tools/tpm2_import.c
tools/tpm2_listpersistent.c

The object attributes were being output in an add hoc way, collapse them into proper yaml outputs, since they have multiple fields in the output.
Fixes: #557

Clean up TPMA_OBJECT attribute outputs

---

.gitignore
Makefile.am
lib/future/test/error.c
lib/log.h
lib/tpm2_error.c
lib/tpm2_error.h
lib/tpm2_util.h
test/system/tests/clearlock.sh
test/system/tests/tcti/abrmd/extended-sessions.sh
test/unit/test_tpm2_error.c
tools/tpm2_activatecredential.c
tools/tpm2_certify.c
tools/tpm2_changeauth.c
tools/tpm2_clear.c
tools/tpm2_clearlock.c
tools/tpm2_create.c
tools/tpm2_createprimary.c
tools/tpm2_dictionarylockout.c
tools/tpm2_encryptdecrypt.c
tools/tpm2_evictcontrol.c
tools/tpm2_flushcontext.c
tools/tpm2_getcap.c
tools/tpm2_getmanufec.c
tools/tpm2_getpubak.c
tools/tpm2_getpubek.c
tools/tpm2_getrandom.c
tools/tpm2_hmac.c

Eventually, we would like to formalize an interface for handling
tpm error codes analagous to C's strtoerr. Until we have such
a formalization, let this live under lib/future in the tools
project.
The tools will be consuming this for the 4.0 release under
ticket #769:
- https://github.com/tpm2-software/tpm2-tools/issues/769

liberror: implement in tools

---

.travis.yml

abrmd has a new dynamic tcti option, update travis to use
it.
Note: --disable-dlclose works around these bugs:
- https://github.com/tpm2-software/tpm2-abrmd/issues/323
- https://github.com/tpm2-software/tpm2-tools/commit/130582559d7c51d18e3ce82803c30bc161d9c34d#diff-9a57bc4e2757e72fe020a15ac7775dfa

travis: update tcti options for abrmd

---

tools/tpm2_createprimary.c
tools/tpm2_tool.c

Add extremely minimal error handling to tpm2_tools so that if onrun() fails, it will at least indicate that it will. Also, modify tpm2_createprimary's onrun() function to return slightly more useful errors (one day maybe someone will use them). refactor onrun() a little bit to make it easier to read and correct inconsistency with flag naming.

cleanup error handling

---

lib/tpm2_options.c
lib/tpm2_tcti_ldr.c
lib/tpm2_tcti_ldr.h
man/common/tcti.md

Currently, the tcti option supported 3
formats:
--tcti=<name>
--tcti=<name>:
--tcti=<name>:<option(s)>
Add support for:
--tcti=:<option(s)>
This recitifes the tpm2-abrmd dynamic tcti handling with the
tools.
Fixes: #902

tcti: handle option string better

---

lib/tpm2_alg_util.c
man/tpm2_getcap.1.md
test/system/helpers.sh
test/system/tests/create.sh
test/system/tests/createprimary.sh
test/system/tests/dictionarylockout.sh
test/system/tests/getcap.sh
test/system/tests/getrandom.sh
test/system/tests/hash.sh
test/system/tests/listpersistent.sh
test/system/tests/nv.sh
test/system/tests/pcrevent.sh
test/system/tests/pcrlist.sh
test/system/tests/quote.sh
tools/tpm2_createpolicy.c
tools/tpm2_getcap.c
tools/tpm2_getmanufec.c
tools/tpm2_getrandom.c
tools/tpm2_hash.c
tools/tpm2_load.c
tools/tpm2_pcrevent.c
tools/tpm2_pcrlist.c
tools/tpm2_policypcr.c
tools/tpm2_quote.c

Audit the tools for printf usages and replace with tpm2_tool_output. Also verify that output is in a YAML compliant format. Add tests that verify that the output can be loaded via the YAML module in python.
Fixes: #634

Yaml output

---

test/unit/test_tpm2_alg_util.c

With gcc v7.3.1 test_tpm2_alg_util.c fails with:
In file included from test/unit/test_tpm2_alg_util.c:33:0:
test/unit/test_tpm2_alg_util.c: In function ‘test_pcr_parse_digest_list_compound’:
test/unit/test_tpm2_alg_util.c:349:78: error: array subscript is above array bounds [-Werror=array-bounds]
fail_msg("Missing algorithm test for: %u", dspec->digests.digests[i].hashAlg);
~~~~~~~~~~~~~~~~~~~~~~^~~
Fix this by explicitly checking the array bounds.

test: fix compilation

---

tools/tpm2_send.c
tools/tpm2_tool.c

Without this patch build fails with 'implicit declaration of function'.
* tools/tpm2_send.c (tpm2_tool_onrun): Replace tss2_tcti_transmit with
Tss2_Tcti_Transmit.  Replace tss2_tcti_receive with Tss2_Tcti_Receive.
* tools/tpm2_tool.c (tcti_teardown): Replace tss2_tcti_finalize with
Tss2_Tcti_Finalize.
Signed-off-by: Manolis Ragkousis <manolis837@gmail.com>

tools: Fix typos in tpm2_send and tpm2_tool

---

.ci/docker.env
.ci/docker.run
.ci/download-deps.sh
.travis.yml
tools/tpm2_clearlock.c
tools/tpm2_encryptdecrypt.c
tools/tpm2_flushcontext.c
tools/tpm2_getcap.c

Travis uses ancient docker and VM images. Switch to a custom
docker image that has all dependencies for the TSS stack pre-installed.
This has a few benefits:
1. Local testing by just running the docker command in the travis.yml file
2. Less dependency setup code in the travis.yml
3. ESAPI builds work on Travis now (the tools can start switching over)
This has a major draw backs:
1. Back on travis VM based builds, which can have long wait queues.
A. A workaround to this, is you can run your full CI buildup locally
so you can just merge outside of travis if need-be.
Fixes: #909

travis: use a custom docker container

---

man/tpm2_createak.1.md

There was a double -g option, and one of them should
have been -D. Fix this, by correcting the tpm options.
Fixes: #916

tpm2_createak: fix manpage double -g options

---

tools/tpm2_createprimary.c

The handle output was missing a newline, which makes
command line output a bit of a struggle as the shell
cursor is on the same line as the output.
Fix this by adding a newline.
Fixes: #914

tpm2_createprimary: add missing newline

---

test/system/tests/encryptdecrypt.sh

The error trap was cleared when using tpm2_getcap
to verify if command encryptdecrypt was supported.
If it wasn't supported, by checking the grep return
code via $?, then a warning is printed and the test
is skipped.
When tpm2_getcap fails, $? is 1 and the test is reported
as passing, which is incorrect.

tests/encryptdecrypt: fix errors that cause passing

---

bootstrap

A ```mkdir -p m4``` will remove the warning, which is not needed
and only causes confusion.
Fixes #926.

bootstrap: Remove Spurious Warning about Missing m4 Directory

---

INSTALL.md

Add mention that pancod is needed (in addition to md2man-roff) to build man pages.
Fixes #929.

INSTALL.md: Document that Pandoc is Needed for Man Pages

---

tools/tpm2_startup.c

The tool doesn't have this short option, so the opstring isn't correct.

tools: remove incorrect 's' option from tpm2_startup optstring

---

.travis.yml
CHANGELOG.md
CONTRIBUTING.md
INSTALL.md
README.md
RELEASE.md
man/common/tcti.md
man/tpm2_print.1.md
test/system/tests/getmanufec.sh
test/system/tests/rc_decode.sh
tools/tpm2_pcrextend.c

- Ensure github links point to the latest repos in the new tpm2-software organisation
- Fix TCTI common options for the socket->mssim rename
- Remove a TODO item which pointed to a bug which is closed WONTFIX

Minor docs tweaks

---

Makefile.am

Generate the man pages from markdown and distribute in the
dist tarball by making a dependency on the man pages via
the EXTRA_DIST variable.
Also, make "make dist" fail if pandoc is not installed:
$ make -j4 dist > /dev/null
You do not have pandoc, a requirement for the distribution of manpages
make[2]: *** [dist-hook] Error 1
make[1]: *** [distdir] Error 2
make: *** [dist] Error 2
Behavior under clean:
1. On a build tree, make clean removes the manpages
2. On a dist tarball, make clean leaves the manpages
Fixes: #925

dist: include built manpages

---

lib/tpm2_options.c
lib/tpm2_options.h
tools/tpm2_tool.c

envp is no longer being used, so remove it.

main: remove envp param as it is unused

---

tools/tpm2_tool.c

TSS doesn't export the ABI defines in public heades anymore.
This is a followup for https://github.com/tpm2-software/tpm2-tss/pull/864

tpm2_tool: define ABI version locally

---

lib/tpm2_attr_util.c
lib/tpm2_errata.c
man/common/obj-attrs.md
man/tpm2_create.1.md
test/unit/test_tpm2_attr_util.c
test/unit/test_tpm2_errata.c
tools/tpm2_create.c
tools/tpm2_createak.c
tools/tpm2_getmanufec.c
tools/tpm2_import.c

Removes all mentions of TPMA_OBJECT_SIGN, since upstream will remove them after https://github.com/tpm2-software/tpm2-tss/pull/868 is merged.
The build currently fails, because upstream removed tpm20.h though...
I guess I or anyone should rebase, once a patch for tpm20.h removal is in master...

all: Switch TPMA_OBJECT_SIGN to _ENCRYPT

---

.gitignore
Makefile.am
bootstrap

Generate the library sources and create variables for them.
This will help make the Makefile smaller and easier to
maintain.

bootstrap: generate library sources

---

Makefile.am
lib/tpm2_capability.c
lib/tpm2_capability.h
lib/tpm2_hierarchy.h
man/tpm2_createak.1.md
man/tpm2_createek.1.md
man/tpm2_createprimary.1.md
man/tpm2_evictcontrol.1.md
man/tpm2_getmanufec.1.md
man/tpm2_hash.1.md
man/tpm2_loadexternal.1.md
test/system/tests/evictcontrol.sh
test/system/tests/hash.sh
tools/tpm2_createak.c
tools/tpm2_createek.c
tools/tpm2_evictcontrol.c
tools/tpm2_getcap.c
tools/tpm2_getmanufec.c
tools/tpm2_hash.c
tools/tpm2_loadexternal.c

The following series of patches implements a solution to issue #892. The changes within:
changes all tools which take a hierarchy argument to make that argument optional and default to the owner hierarchy when no value is passed
for tools which take a handle argument in order to specificy a persistent handle when making a transient object persistent no longer require a handle to be specified.
The tpm2_evictcontrol tool will do the right thing and, when a handle to a transient object is specified without a matching permanent handle we now automatically try and find an open slot in the persistent handle namespace.
tools which take an optional handle to persist a transient object at now have the option of specifying - as a handle. When passed a handle of (-* the tool will automatically find …

Set heirarchy to owner by default for all tools, make -H optional 

---

test/unit/test_files.c
test/unit/test_tpm2_alg_util.c
test/unit/test_tpm2_attr_util.c
test/unit/test_tpm2_error.c
test/unit/test_tpm2_policy.c
test/unit/test_tpm2_session.c

GCC would complain about implicit declaration of functions [-Wimplicit-function-declaration] if stdlib.h and string.h is not included directly. (Previously stdlib.h and string.h were indirectly included from sapi/tpm20.h)

test: Suppress GCC warnings of implicit declarations

---

tools/tpm2_certify.c

get_key_type does not assign a value to 'type' on error conditions,
which makes the compiler believe that it will be used uninitialized in
the LOG_ERR call, in set_scheme. In practice this will never happen
because set_scheme returns immediately if get_key_type retuns false but
the compiler does not understand that logic and fails because warnings
are treated as errors.
Signed-off-by: Carlos Santos <casantos@datacom.ind.br>

tpm2_certify: fix "'type' may be used uninitialized" warning

---

man/tpm2_nvdefine.1.md
man/tpm2_nvread.1.md
man/tpm2_nvreadlock.1.md
man/tpm2_nvwrite.1.md
tools/tpm2_nvdefine.c
tools/tpm2_nvread.c
tools/tpm2_nvreadlock.c
tools/tpm2_nvwrite.c

My previous attempt to set the default hierarchy for all tools to the owner hierarchy in #950 turned out not to include all tools. This series fixes up some tools I missed.

Change more tools to default to owner hierarchy

---

tools/tpm2_import.c

Switch from loading the public key file and seeking around to find the modulus to instead loading the key file with libmarshal (via the `files_load_public()` function) and using the struct members to access the key data.

Make key loading in tpm2_import more robust

---

man/tpm2_evictcontrol.1.md

The -a / --hierarchy option was incorrectly documented as
having a long option name of --auth-heirarchy.

man/tpm2_evictcontrol: fix long option name for -a

---

man/common/tcti.md

When the TCTI configuration got simpler, the wording
never followed. Clean up the TCTI description so
it's more understandable.

man: clean up tcti description

---

lib/tpm2_options.c

Before:
tpm2_getmanufec --verbose
tool="../tools/tpm2_getmanufec" version="3.0.2-403-g17d361d-dirty" tctis="dynamic" tcti-default=tabrmd dlclose=enabled
After:
tpm2_getmanufec --version
tool="../tools/tpm2_getmanufec" version="3.0.2-403-g17d361d-dirty" tctis="dynamic" tcti-default=tabrmd dlclose=enabled
Fixes: #967

options: fix --verbose and --version crossover

---

test/system/tests/createak.sh
test/system/tests/createek.sh
test/system/tests/createprimary.sh
test/system/tests/evictcontrol.sh
test/system/tests/getmanufec.sh
test/system/tests/loadexternal.sh
tools/tpm2_createprimary.c
tools/tpm2_loadexternal.c

Following on from #950 and #959 this series fixes **tpm2_createprimary** and **tpm2_loadexternal** to not require an explicit hierarchy option be passed, using the default of **TPM2_OWNER** when one isn't specified.
Further we add some tests for the default owner hierarchy and persistent handle finding changes made in #950.

Implicit H follow on

---

lib/tpm2_options.c
man/common/tcti.md

The tools used two different environment variables to configure the TCTI:
TPM2TOOLS_TCTI_NAME that was used to set TCTI name and per TCTI variable
that was used to set properties that were specific to a particular TCTI.
For example, the device TCTI used TPM2TOOLS_DEVICE_FILE to choose which
TPM character device is used and so on. Later this was changed to only
need a single variable and both the TCTI name and properties could be
set by separating them using a ':' character.
But the variable name was left as TPM2TOOLS_TCTI_NAME which is kind of
misleading due being formerly use just to configure the TCTI name. So I
think that's better to change the variable name to TPM2TOOLS_TCTI which
is a more generic name and better reflects current variable's semantics.
Signed-off-by: Javier Martinez …

options: use TPM2TOOLS_TCTI as environment variable for configuration

---

.ci/download-deps.sh

In order to speed up the process, use shallow clones of the dependency
git repositories tpm2-tss and tpm2-abrmd instead of full history clones.
Signed-off-by: Andreas Fuchs <andreas.fuchs@sit.fraunhofer.de>

tests/docker: shallow clone git repos

---

.ci/docker.run

If the unit tests fail, print out the content of test-suit.log.
This allows developers to directly see the output of the tools
and hopefully speed up debugging.

Tests: Show test-suit.log in docker

---

lib/tpm2_alg_util.c
tools/tpm2_import.c

Fix warnings about a memory leak in an error condition, 0-sized memcpy(),
0-size malloc(), and malloc() size not matching type.
Fixes #983.

Fix Bugs Found by Clang Scan-build Static Code Analyzer

---

tools/tpm2_import.c

tools: Fix warning from clang scan-build about malloc() size not matching type.
Fixes #988.

tools: Fix a Warning From Clang Scan-build Static Code Analyzer

---

configure.ac

configure was attempting to configure for unit tests
when the option was NOT being passed. Fix this by
correcting the check on the option.
Fixes: #995

configure: fix unit test check

---

INSTALL.md

md2man-roff is not needed (use Pandoc instead, which is already mentioned).
Fixes #1005.

INSTALL.md: Remove mention of md2man-roff

---

man/common/tcti.md
test/integration/helpers.sh

The TCTI library isn't using URIs for the config string any longer.
Instead we're using a string of key/value pairs with 'host' and
'port' as the keys.

tcti: Update mssim TCTI usage to use new key/value pair conf string.

---

lib/files.c

When -u is provided and is an invalid structure,
the error message is not always clear:
echo "this is public" > public
tpm2_loadexternal  --tcti device -a o -u public
WARNING:marshal:src/tss2-mu/tpm2b-types.c:355:
Tss2_MU_TPM2B_PUBLIC_Unmarshal() buffer_size: 20 with offset: 2 are insufficient for object of size 21608
ERROR: Error serializing public structure: 0x90006
Update the error output to indicate that the file needs to be a TPM2B_PUBLIC data structure.
tpm2_loadexternal -a o -u public
WARNING:marshal:src/tss2-mu/tpm2b-types.c:355:Tss2_MU_TPM2B_PUBLIC_Unmarshal() buffer_size: 15 with offset: 2 are insufficient for object of size 29800
ERROR: Error serializing public structure: 0x90006
This will also issue errors of similair construct for other file types loaded up.
Fixes: #985 …

tpm2_loadexternal: improve error message

---

.ci/docker.run

Enable scan-build compile-time static analysis.
Rebuild after running scan-build as test_tpm2_session fails
when build under scan-build.
Fixes #999.

Enable scan-build

---

INSTALL.md

Add a complete build example of tpm2-tools with its dependencies on fedora 27 ready to run

INSTALL.md: add a build from source example 

---

lib/files.c
lib/files.h
tools/tpm2_create.c
tools/tpm2_load.c

The tpm2_create tools is only storing the TPM2B_PRIVATE .buffer field but
not it's .size field. This causes the private keys stored with the stable
version of the tools, to fail loading when using the latest master branch.
Fix this by storing the whole TPM2B_PRIVATE object, including size field.
Fixes: #976

[v2] tools: Fix save and load for TPM2B_PRIVATE

---

tools/tpm2_import.c

This commit fixes the following GCC warning that leads to a compile error:
CC       tools/tpm2_import.o
tools/tpm2_import.c: In function ‘on_option’:
tools/tpm2_import.c:590:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
switch(ctx.key_type) {
^~~~~~
tools/tpm2_import.c:602:5: note: here
case 'K':
^~~~
cc1: all warnings being treated as errors

tpm2_import: Fix build error due missing break in a case statement

---

Makefile.am
lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
lib/tpm2_convert.c
lib/tpm2_convert.h
man/common/signschemes.md
man/tpm2_import.1.md
man/tpm2_verifysignature.1.md
test/integration/tests/import.sh
test/unit/test_tpm2_alg_util.c
tools/tpm2_import.c
tools/tpm2_verifysignature.c

Updated: 5/1/2018 @ 11:43AM Pacific
Adds tests for import that:
* Sign with the tpm and verify with openssl
* Sign with openssl and verify with the tpm
* Required -r raw support to be fixed
* Required conversion routine from plain signature to tss
Additional Changes:
* Changes private key input to openssl PEM file and  supports encrypted private keys.
* Drops a dead function prototype as well
* Drops dead crufty code
* Update tpm2_verifysignature to support `-f --format` instead of `-r --raw`.
* This is the generic plumbing for taking in a signing scheme, even though only rsassa is supported.
* Add more unit tests
Post-Merge TODO:
Update Changelog to include the tpm2_verifysignature option rename

Import work

---

lib/tpm2_options.c

Improve usage output with proper capitalization, indentation and use of
traditional BNF notation common in usage and man pages.
Usage output appears for commands appear when no man page is present or
the man pages are not installed.
Fixes #1031.

lib: Improve Usage Output

---

Makefile.am
configure.ac

The changes introduced for issue #925 still don't work out completely. The man
pages are now distributed in the release tarball, but they won't be installed
by automake, because the install targets are not setup when `pandoc` is not
around.
With this change the man page install targets will be setup even if
pandoc is not installed but generated man pages are available in
man/man1.
The test is not perfect, maybe you have a better idea how to achieve this.

autotools: allow man page installation without pandoc being available

---

man/common/alg.md
man/common/pcr.md
man/common/pubkey.md
man/tpm2_changeauth.1.md
man/tpm2_makecredential.1.md
man/tpm2_nvread.1.md
man/tpm2_nvwrite.1.md
man/tpm2_pcrlist.1.md
man/tpm2_quote.1.md
man/tpm2_unseal.1.md

The tpm2_pcrlist example is incorrect. This: `sha:3,4+sha256:5,6`
should be: `sha1:3,4+sha256:5,6`
Add the command for the `tpm2_pcrlist -L sha1:0+sha256:0` example.
Fix these spelling errors:
s/secification/specification
s/Specfiers/Specifiers
s/limitaion/limitation
s/certififcate/certificate
s/locakout/lockout
Fixes #1034.

man: Fix tpm2_pcrlist Example and Spelling Errors

---

CHANGELOG.md
lib/tpm2_util.c
man/tpm2_create.1.md
man/tpm2_createprimary.1.md
test/integration/tests/createprimary.sh
tools/tpm2_create.c
tools/tpm2_createprimary.c

The name hash algorithm and key algorithms have defaults, use
them so -g/-G do not need to be specified.
Now the command tpm2_createprimary -o context.dat will work.

tpm2_createprimary: specify defaults for -g/-G

---

man/tpm2_certify.1.md
man/tpm2_createak.1.md
man/tpm2_createek.1.md
man/tpm2_evictcontrol.1.md
man/tpm2_hmac.1.md
man/tpm2_load.1.md
man/tpm2_policypcr.1.md
man/tpm2_policyrestart.1.md
man/tpm2_quote.1.md
man/tpm2_sign.1.md
man/tpm2_unseal.1.md
man/tpm2_verifysignature.1.md
test/integration/tests/certify.sh
test/integration/tests/create.sh
test/integration/tests/createprimary.sh
test/integration/tests/encryptdecrypt.sh
test/integration/tests/evictcontrol.sh
test/integration/tests/hmac.sh
test/integration/tests/import.sh
test/integration/tests/listpersistent.sh
test/integration/tests/load.sh
test/integration/tests/loadexternal.sh
test/integration/tests/quote.sh
test/integration/tests/readpublic.sh
test/integration/tests/rsadecrypt.sh
test/integration/tests/rsaencrypt.sh
test/integration/tests/sign.sh
test/integration/tests/tcti/abrmd/extended-sessions.sh
test/integration/tests/unseal.sh
test/integration/tests/verifysignature.sh

The object loading code doesn't require a file: prefix for files, except in cases where the file name could be confused for a handle. Update the examples in the manual pages and the tests to not use the file: prefix, as doing so might suggest the prefix is required.
Possibly addresses #1040

Clarify that file: prefix is not required by tpm2_util_object_load

---

lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
lib/tpm2_attr_util.c
tools/tpm2_create.c
tools/tpm2_createprimary.c
tools/tpm2_load.c

* Clean up some code
* Allow for parent secondary objects to be created via the restricted attribute in tpm2_create
* Add the memsets that got abandoned, did they get cherry-picked to 3.0.4? (check this)

object creation fixes

---

lib/tpm2_tcti_ldr.c

tcti_ldr: load a specific so version

---

lib/files.c
lib/files.h
man/tpm2_encryptdecrypt.1.md
test/integration/tests/encryptdecrypt.sh
tools/tpm2_encryptdecrypt.c

Support using stdin and stdout as a way to encrypt and decrypt data.
This will help prevent spilling a potential secret to disk.

tpm2_encryptdecrypt: support stdin/stdout

---

lib/tpm2_tcti_ldr.c

The raw .so file always points to the latest shared library object and is
usually split into the development package in distributions.
Factor TCTI dlopen'ing into a shared function that loads the TCTI by
versioned SONAME.
Resolves issue #1057

tcti_ldr: load TCTI's by SONAME, not raw .so filename

---

CHANGELOG.md
man/tpm2_activatecredential.1.md
man/tpm2_certify.1.md
man/tpm2_createak.1.md
man/tpm2_createprimary.1.md
test/integration/tests/certify.sh
test/integration/tests/output_formats.sh
test/integration/tests/quote.sh
tools/tpm2_activatecredential.c
tools/tpm2_certify.c
tools/tpm2_createak.c
tools/tpm2_createprimary.c
tools/tpm2_quote.c

Fix issues noted in #1039 where the incorrect case is used for short options.

Capital options for parent, lower for current object

---

Makefile.am
lib/tpm2_util.c
man/tpm2_print.1.md
test/unit/test_tpm2_util.c
tools/aux/tpm2_print.c

The 3rd commit adds rudimentary support for `TPMS_CONTEXT` to **tpm2_print**, I'm not sure if it's useful or not but I wrote it in order to better understand the context file (in order to spoof one for testing) so thought it was at least worth including in a PR.
Fixes #1037

Add unit test for tpm2_util_object_load()

---

configure.ac

The API has changed considerably and the headers have moved around,
so the tools won't build against an older version of the TSS.

configure: require tss2-sys 2.0.0 or greater

---

.ci/travis.run
CHANGELOG.md
man/common/signschemes.md
man/tpm2_sign.1.md
man/tpm2_verifysignature.1.md
scripts/utils/analyze.py
test/integration/tests/import.sh
test/integration/tests/output_formats.sh
test/integration/tests/sign.sh
test/integration/tests/verifysignature.sh
tools/tpm2_sign.c
tools/tpm2_verifysignature.c

This pull request should resolve the remaining items to resolve/fix #957:
- change **-f** to **-i** in `tpm2_verifysignature`
- change **-g** to **-G** in `tpm2_sign` and `tpm2_verifysignature`
- updates `scripts/utils/analyze.py` to only print the report for the custom group when the **-c** option is passed
- integrates `scripts/utils/analyze.py` into the CI loop so that introduction of conflicting short options causes a CI failure

Make option short forms consistent

---

tools/tpm2_nvdefine.c

This was left in accidentally after the option was changed from -I to -p

tpm2_nvdefine: remove no longer valid shortopt -I

---

man/common/authorizations.md
man/tpm2_unseal.1.md

- Changed 'ran' to 'run' in the description paragraph for tpm2_unseal.
- Changed 'hex-string,' to 'hex-string password' in authorizations.
- Cleaned up the Sessions paragraph in authorizations.

Updated tpm2_unseal and authorizations pages.

---

lib/tpm2_attr_util.c

This reverts commit e103bbf5117b0b62b358fd15f18f848854fcb0ee.
The tpm2-tools 3.1.0 release contains a backward incompatible change that
was introduced by commit e103bbf5117 ("objectattrs: clear before or'ing
in values"), that changed the way that object attributes were specified.
Before there were a set of default attributes and the user could specify
additional attributes to be used, but after the mentioned commit the user
must specify all attributes.
This is a user visible change that changes the tools semantics, so is not
a suitable change for a MINOR version number increment, according to the
Semantic Versioning document (https://semver.org) since it breaks rule 2:
2.MINOR version when you add functionality in a backwards-compatible manner
Fixes: #1097
Signed-off-by: Javier Martinez …

Revert "objectattrs: clear before or'ing in values"

---

Makefile.am
configure.ac
dist/bash-completion/tpm2-tools/tpm2_completion.bash
lib/tpm2_options.c

This pull-request contains @kaiserkyu patch from PR #1068, plus some fixes from issues I pointed out in the review.
The changes from his original commit are:
1. Install bash completion file in compatdir (/etc/bash_completion.d) instead of completionsdir(/usr/share/bash-completion/completions).
2. Only show the pretty names instead of the hexadecimal values for option arguments.
3. Don't show long options as `--option=` but instead just as `--option` and also allow to autocomplete the arguments for long options.
4. Remove some unnecessary blank lines that were introduced in the patch.
@williamcroberts I've tested his patch and it works for me, basically what I do is:
```
$ ./bootstrap
$ ./configure --prefix=/usr
$ make -j5 && sudo make install
```
Then I open a new terminal and type:
```
$ …
```

Add bash completion support for all the tools

---

.ci/docker.run
.ci/travis.run
lib/tpm2_options.c

The following commit:
https://github.com/tpm2-software/tpm2-tools/commit/2fb68758e01bca412f9001ad53374beb862c752f
Introduced in a bug in TCTI initialization, which then skips providing a SAPI context
to the tools. Correct the check so TCTI initialization occurs.
Also, it looks like Travis stopped getting the exit code propagated back, fix this with some set -e in the scripts.

Fix no TCTI initialized and correct travis

---

Makefile.am
test/integration/tests/import.sh
tools/tpm2_import.c

This is the minimum set of fixes for tpm2-import. It still requires a lot of hardcoded values. Future work needs to be done to make this tool much more robust in the face of different parents, as well as configurable parameters for the object being created.
This makes progress towards #1079

Minimum fixes to import

---

lib/files.c
lib/files.h
test/unit/test_files.c
tools/tpm2_certify.c
tools/tpm2_rsadecrypt.c
tools/tpm2_sign.c
tools/tpm2_verifysignature.c

Almost no tool checks to see if the user specified output
file already exists, and if so, aborts operation with an
error. Just clobber the output file.

tools: stop checking if output file already exists

---

test/integration/tests/getcap.sh
tools/tpm2_activatecredential.c
tools/tpm2_certify.c
tools/tpm2_create.c
tools/tpm2_createak.c
tools/tpm2_createek.c
tools/tpm2_dictionarylockout.c
tools/tpm2_encryptdecrypt.c
tools/tpm2_getcap.c
tools/tpm2_hmac.c
tools/tpm2_load.c
tools/tpm2_makecredential.c
tools/tpm2_pcrlist.c
tools/tpm2_policypcr.c
tools/tpm2_quote.c
tools/tpm2_rsadecrypt.c
tools/tpm2_tool.c
tools/tpm2_tool.h

This PR updates the tpm2_tools tpm2_tool_onrun() method, the main interface for tools, such that if -1 is returned the tools usage will be printed.
Addresses #1099

Print usage information when incorrect options are passed to tools

---

lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
lib/tpm2_util.c
man/common/alg.md
test/integration/tests/create.sh
tools/tpm2_createprimary.c

Support specifying meaningful data in the scheme field of complex
algorithm specifiers. This allows for one to create keys for signing,
etc.
For instance things like this are now possible via -G:
- ecc256:ecdaa4-sha256

Algorithms: Enhance scheme support

---

configure.ac
tools/tpm2_rsaencrypt.c

Whilst trying to replicate #1089 I have build both the 3.X and master branches on CentOS 7. The following two patches were required to build master on CentOS 7.

Fixes for building on CentOS 7

---

CHANGELOG.md
man/tpm2_create.1.md
man/tpm2_createprimary.1.md

The filename is obj-attrs.md not object-attrs.md

man: fix inclusion of common object attribute specifiers section

---

test/system/test_tpm2_unseal.sh
tools/tpm2_create.c

The tpm2_create tool allows to define a policy session or a password for
authentication. By default no policy session is used and the password is
empty, which means that this empty password is used for authentication.
So the default object attribute flag userWithAuth is set in order to use
the empty password. This isn't a good default though if a policy is set,
since in this case the policy session has to be used for authentication
instead of an empty password.
If a policy is defined, the userWithAuth bit has to be clear unless the
user defines a password so in that case authentication would happen only
using the policy session or the defined password.

[for 3.X] tpm2_create: Use better object attributes defaults for authentication

---

.ci/download-deps.sh

Recent changes in tpm2-tss and tpm2-abrmd broke our CI for the 3.X branch.

Fix CI for 3.X branch

---

scripts/utils/analyze.py
test/integration/tests/activecredential.sh

This is just an extremely trivial pull request to add parentheses to the Python `print` function so that it works with Python 3 as well as Python 2. This is necessary to run the integration tests e.g. on Arch Linux, which uses Python 3 as the default interpreter. I think I found all instances where the old syntax was still used, while some scripts like [test/integration/tests/getcap.sh](https://github.com/tpm2-software/tpm2-tools/blob/master/test/integration/tests/getcap.sh#L58) already used the new syntax anyway.
With this change, the test suite compiles and runs successfully on Arch Linux. The resulting files still work with Python 2 as well.

Ensure Python 3 compatibility of print function

---

CHANGELOG.md
lib/tpm2_util.c
man/tpm2_import.1.md
test/integration/tests/import.sh
tools/tpm2_activatecredential.c
tools/tpm2_create.c
tools/tpm2_createak.c
tools/tpm2_createek.c
tools/tpm2_encryptdecrypt.c
tools/tpm2_evictcontrol.c
tools/tpm2_flushcontext.c
tools/tpm2_hmac.c
tools/tpm2_import.c
tools/tpm2_load.c
tools/tpm2_quote.c
tools/tpm2_readpublic.c
tools/tpm2_rsadecrypt.c
tools/tpm2_rsaencrypt.c
tools/tpm2_sign.c
tools/tpm2_unseal.c
tools/tpm2_verifysignature.c

Enhance tpm2-import:
1. Internal refactoring to reduce usages of globals.
2. Support setting name hash algorithm via -g.
3. Support varying parent name-alg and symmetric parameters.
4. Support importation of RSA 1024 keys (likely works for 4096 but needs testing)
5. Support importation of AES 128/192/256 keys
This makes progress on #1079, but doesn't resolve everything. Issues #1129 and #1128 have been opened to address adding in missing ECC support.
It might be awhile before I can get back to tpm2_import, but this makes major progress and should be included in master.

Enhancments to tpm2-import

---

tools/tpm2_import.c

Commit:
45a1dd2bf415 "tpm2_import: drop hardcoded prime size in bytes"
Uses %lu to print the returns from sizeof(), when it should be
using %zu for size_t. This causes build issues on 32 bit machines.
Fixes: #1134

tpm2_import: fix size_t printf format specifiers

---

CHANGELOG.md
tools/tpm2_verifysignature.c

* Stop outputting the message bytes
* Make -t optional
* Issue a warning when -t is specified and the object hierarchy is NULL.

tpm2_verifysignature enhancmeents

---

RELEASE.md

So far there wasn't consistency on how the CHANGELOG was edited to reflect
the release candidates and final releases. Add some words on how this must
be done so the CHANGELOG remains consistent between releases and branches.

RELEASE: add explanation on how to edit the CHANGELOG file for releases

---

man/tpm2_create.1.md
man/tpm2_createek.1.md
man/tpm2_createprimary.1.md
man/tpm2_encryptdecrypt.1.md
man/tpm2_evictcontrol.1.md
man/tpm2_getmanufec.1.md
man/tpm2_hmac.1.md
man/tpm2_load.1.md
man/tpm2_nvrelease.1.md
man/tpm2_quote.1.md
man/tpm2_rsadecrypt.1.md

-S is no longer used in tools, it's supported as a password
option, thus remove the mentions from the manpage.

man: remove mentioned but unused -S options

---

test/integration/tests/rsadecrypt.sh
tools/tpm2_rsadecrypt.c

In the getopt short option string, a capital P was in place
for lowercase p resulting in the password option not being
processed. Fix this and add passwords to the tests to prevent
regressions.

tpm2_rsadecrypt: fix -p option

---

lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
lib/tpm2_convert.c
lib/tpm2_convert.h
lib/tpm2_openssl.c
man/tpm2_loadexternal.1.md
man/tpm2_sign.1.md
man/tpm2_verifysignature.1.md
test/integration/tests/loadexternal.sh
tools/tpm2_certify.c
tools/tpm2_quote.c
tools/tpm2_sign.c
tools/tpm2_verifysignature.c

Add:
1. Support to loadexternal for ECC keys (which bled into verifying them)
2. Support for tpm2_verifysignature for loading OSSL produced signatures (ASN1 ECDSA sigs)
3. Support for tpm2_sign for outputting ASN1 ECDSA signatures for OSSL
Test that this all works, ie can load an external ECC key, sign and verify to/from OSSL and TPM.
Update man pages with better examples, fix some typos.

add more ECC support

---

tools/tpm2_import.c

The code was checking if the public file was specified twice, when
it wanted ot verify public once and private once. Correct this.

tpm2_import: fix private file option check

---

CHANGELOG.md
man/tpm2_loadexternal.1.md
scripts/utils/analyze.py
test/integration/tests/loadexternal.sh
tools/tpm2_loadexternal.c

Output the name of the loaded object to both stdout and via the -n option.
Add tests to verify the YAML output.
Fixes: #1163

tpm2_loadexternal: output name

---

lib/tpm2_alg_util.c
man/common/alg.md

All TPMs support AES128CFB, but not many seem to support
AES128. Numerous bug reports have surfaced on switching
the default to AES256, dial it back so it just works.
Fixes: #1166 
References initial bug: #1142

default: dial back AES256 default to AES128

---

test/integration/tests/createek.sh
tools/tpm2_createek.c

-c/--context is optional, therefore don't assume the argument is passed
(and segfault trying to access an unallocated variable).
Fixes #1169

tpm2_createek: don't segfault if -c isn't passed

---

test/system/test_tpm2_activecredential.sh

Use the print function, not the print keyword, so that the code is
compatible with python3.
Fixes #1178

test: make test_tpm2_activecredential python3 compatible

---

Makefile.am
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_policyauthorize.1.md
scripts/utils/analyze.py
test/integration/tests/tcti/abrmd/policyauthorize.sh
tools/tpm2_policyauthorize.c

This tool enables creating policy that authorizes policy digests. 
Amongst other uses of this tool, This tool also helps address a very specific problem with sealing secrets to raw PCR values. Since the PCRs are reflective of a software (preboot) state, PCRs are susceptible to frequent changes as software is updated. This results in PCR-brittleness, in that, one loses the ability to unseal the secrets tied to a specific set of PCR with specific values. This tool can address this issue by generating a policy by authorizing the pcr policy digest.
PS: 
There is a need to augment the existing tpm2_loadexternal tool to directly load an external public key file in pem format. This is required when verifying the signatures created with the signing authority when using the this …

tpm2_policyauthorize: New tool to enable authorizing policy digests using PolicyAuthorize

---

test/integration/tests/unseal.sh
tools/tpm2_create.c

As explained in https://github.com/tpm2-software/tpm2-tools/pull/1127#issuecomment-418175796, the handling of the `userwithauth` object attribute has been improved on the 3.X branch in https://github.com/tpm2-software/tpm2-tools/pull/1126, but these changes have not been merged to master yet. There was a pull request for that (https://github.com/tpm2-software/tpm2-tools/pull/1127), but it has been overwritten by other changes, so I reconstructed the original state of that pull request from https://github.com/tpm2-software/tpm2-tools/pull/1126 and the still available diffs in https://github.com/tpm2-software/tpm2-tools/pull/1127. The resulting code matches the behaviour of `tpm2_create` on the 3.X branch, as described in https://github.com/tpm2-software/tpm2-tools/pull/1126#issuecomment-408 …

[for master] tpm2_create: Use better object attributes defaults for authentication

---

.ci/docker.run
CHANGELOG.md
tools/tpm2_takeownership.c

Backport of the change in 7ace0ea to the 3.X branch.
Only send a changeauth command if the hiearchy is specified.
This corrects behavior of attempting to change a non-specified hierarchy.
Fixes #1183

tpm2_changeauth: only change hierachy specified

---

man/tpm2_policyauthorize.1.md

1. Need to change the hierarchy from null to the owner since
tpm2_verifysignature do not create the verification ticket
when the hierarchy is null.
2. In  tpm2_create command store the privet and public object
in a separate file.
3. Typo error while providing the signing key name in
tpm2_policyauthorize.
4. tpm2_load object is missing before tpm2_unseal command.

man/tpm2_policyauthorize: correct issues and typos

---

man/tpm2_evictcontrol.1.md

Can specify handle-id or file path of a context blob.

tpm2_evictcontrol.1.md: Typo in the man page

---

man/tpm2_rsaencrypt.1.md

The -I option was removed and became an argument

tpm2_rsaencrypt: fix example in man page

---

lib/tpm2_convert.c
lib/tpm2_openssl.c
lib/tpm2_openssl.h
test/integration/tests/output_formats.sh

Add support for outputing ECC keys via the tpm2_format
routines.
Examples:
tpm2_readpublic -c ecc.ctx -f der -o ecc.der.pub
tpm2_readpublic -c ecc.ctx -f pem -o ecc.pem.pub
openssl ec -pubin -inform pem -text -in ecc.pem.pub
openssl ec -pubin -inform der -text -in ecc.der.pub
Fixes: #1212

format: add suport ECC keys

---

test/integration/tests/hash.sh

`xxd` expects 32 bytes value (sha256 size) instead 256.
`Signed-off-by: Igor Opaniuk <igor.opaniuk@gmail.com>`

tests/hash.sh: fix sha256 hash size

---

CHANGELOG.md
lib/files.c
lib/tpm2_convert.c
lib/tpm2_openssl.c
lib/tpm2_openssl.h
man/tpm2_import.1.md
man/tpm2_loadexternal.1.md
test/integration/tests/import.sh
test/integration/tests/loadexternal.sh
tools/tpm2_import.c
tools/tpm2_loadexternal.c
tools/tpm2_tool.c

* cleanups and fixes
* Allow encrypted PEM passwords via --passin similair to OSSLs -passin option.
Fixes: #1217

Issue 1217 passin ossl

---

lib/tpm2_options.c

commit:
- 175e47711c72 lib/tpm2_options: restore TCTI configuration environment variables
Broke the option handling, effectively ignoring the -T/--tcti input. Honor that input
if specified and don't just run the default TCTI search unless it's not specified.

options: fix broken -T option

---

lib/files.c

Routine files_load_bytes_from_file_or_stdin() calls
files_load_bytes_from_path() when it already has an open FILE pointer, just
re-use that FILE * rather than invoking another fopen() call via
read_bytes_from_file().

lib/files: rm extra fopen() in library path

---

lib/tpm2_alg_util.c

tpm2_alg_util: remove scheme check
Remove an incorrect scheme check and allow NULL schemes
on restricted objects.
These checks are better enforced by the TPM, as the algorithm, scheme, object
attributes and symmetric details behave in a complex fashion. Also, revisions
of TPM software change how this matrix behaves, like revision 101 of:
- https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf
This allows for:
tpm2_createprimary -o primary.ctx
tpm2_create -C primary.ctx -g sha256 -G ecc256:ecdsa:null -u child.pub -r child.priv \
-A "fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|sign"

tpm2_alg_util: remove scheme check

---

Makefile.am
configure.ac
lib/tpm2_hash.c
lib/tpm2_options.c

Differences on QNX:
*   Have to define `_QNX_SOURCE` to enable parts of the API.
*   Dynamic-library API (e.g. `dl_open`) is a part of libc. There is no `libdl`.
*   There is no `fmemopen`, `open_memstream`, or equivalent functionality
`Makefile.am`:
Replaced hard-coded `LDFLAGS`, "`-ldl`", with variable, `LIBDL_LDFLAGS`.
`configure.ac`:
Added `$host_os` case statement to detect QNX targets and modify `CFLAGS` and set `LIBDL_LDFLAGS`.
`lib/tpm2_options.c`:
Added `#include <libgen.h>` explicitly for `basename`.
Replaced `linux/limits.h` with `limits.h`. Appears to be a valid change in Ubuntu, Alpine, MinGW64, and QNX.
`lib/tpm2_hash.c`: Modified code to work without `fmemopen`.
- Most of the code previously in `tpm2_hash_file` is now in `tpm2_hash_common` with additional changes.
- …

Added support for QNX build

---

lib/tpm2_auth_util.c
man/common/authorizations.md

Rather than have the general entry point deal with the parsing
pf the +, which would break passwords with a + in them, check
if it is a session, copy and modify the argument spliting the
string on the + character and call into the password handler for
the remaining password string if present.
This will support passwords with strings, and remove some
complexity from the code (confusing loop).

tpm2_auth_util: cleanup session auth value parsing

---

test/unit/test_tpm2_alg_util.c

Pull request https://github.com/tpm2-software/tpm2-tss/pull/1211/files adds explicit casts to `TPM2_ALG_ID` macro definitions. That change prevents stringifying the `TPM2_ALG_ID` macros directly, breaking the `nv_single_item_test2` tests. Instead, use `snprintf` to create the hex-value strings.

Fix test_tpm2_alg_util.c for TPM2_ALG_ID macro changes

---

tools/tpm2_sign.c

The error:
ERROR: Expected options (k or c) and (m or D) and s
Is both incorrect and confusing. Correct the "k" output, as "k"
is no longer supported and output them one at a time so the user
doesn't need to figure out what they were missing.

tpm2_sign: fix option error output

---

lib/tpm2_options.c

The commit 175e47711c7 ("lib/tpm2_options: restore TCTI configuration
environment variables") restored how the TCTI configuration was setup
for the 3.X releases, but this broke the -T,--tcti option since was
ignored.
Commit 554a13f45c0 ("options: fix broken -T option") partially fixed
this, but only when additional TCTI arguments were not used.
For example when specifying the -T device:/dev/tpmrm0 TCTI option:
$ tpm2_pcrlist -T device:/dev/tpmrm0
...
ERROR: Could not dlopen library: "device:/dev/tpmrm0"
ERROR: Could not load tcti, got: "device:/dev/tpmrm0"

options: fix broken -T option when passing additional arguments

---

test/integration/tests/getmanufec.sh
tools/tpm2_getmanufec.c

BIO_NOCLOSE prevents BIO_free() from freeing the underlying BUF_MEM
structure, however we don't need that as we do all of our work with
underlying buffer before we call BIO_free_all().
Fixes #390

tpm2_getmanufec: fix memory leak in OpenSSL usage

---

configure.ac

- Add a check for `xxd`, which is [required by some integration tests](https://github.com/tpm2-software/tpm2-tools/blob/88956e75684499a8186d517cc1ce0f68590c328a/test/integration/tests/activecredential.sh#L73).
- Only display the warnings about missing test dependencies if testing is enabled using `./configure --enable-unit`.
- Fix `AC_PYTHON_MODULE`:
- Suppress Python output.
- Display the name of the given module instead of the static string `pyyaml`.
- Add missing `else`.

build: add check for xxd, move warnings to unit_test_checks

---

Makefile.am
configure.ac
dist/bash-completion/tpm2-tools/tpm2_completion.bash

According to the [bash-completion FAQ](https://github.com/scop/bash-completion#faq), `/etc/bash_completion.d` (pkgconfig variable `compatdir`) is deprecated in favour of `/usr/share/bash-completion/completions` (pkgconfig variable `completionsdir`). As the completion file is loaded on demand based on its filename, we need to create symlinks for every tool during installation.
Using the on demand loading allows to replace the somewhat awkward [`find`-based loop to setup completion for all tools in `tpm2_completion.bash`](https://github.com/tpm2-software/tpm2-tools/blob/5d4cc4ee0f5ccc2ea84f7266a446373d602a188a/dist/bash-completion/tpm2-tools/tpm2_completion.bash#L136) with a simpler approach based on the currently requested completion.

bash-completion: move to recommended directory

---

configure.ac

`configure.ac` uses non-portable syntax:
- String comparison in `test` with a double `==` instead of a single `=`.
- `+=` for string concatenation of variables.
This can be problematic if `/bin/sh` is not `bash`, but e.g. `dash`.

configure: ensure POSIX compatibility

---

test/unit/test_files.c
test/unit/test_pcr.c
test/unit/test_string_bytes.c
test/unit/test_tpm2_alg_util.c
test/unit/test_tpm2_attr_util.c
test/unit/test_tpm2_errata.c
test/unit/test_tpm2_error.c
test/unit/test_tpm2_header.c
test/unit/test_tpm2_hierarchy.c
test/unit/test_tpm2_util.c

The reason for #1278 is a missing variable declaration. It is already present in [`test_tpm2_auth_util.c`](https://github.com/tpm2-software/tpm2-tools/blob/872076e1b31f22b18391c6761d47575a93891cd7/test/unit/test_tpm2_auth_util.c#L205), [`test_tpm2_policy.c`](https://github.com/tpm2-software/tpm2-tools/blob/872076e1b31f22b18391c6761d47575a93891cd7/test/unit/test_tpm2_policy.c#L378) and [`test_tpm2_session.c`](https://github.com/tpm2-software/tpm2-tools/blob/872076e1b31f22b18391c6761d47575a93891cd7/test/unit/test_tpm2_session.c#L299), which is where I copy-pasted it from.

test/unit: fix undefined reference to external variable

---

Makefile.am
man/tpm2_pcrreset.1.md
scripts/utils/analyze.py
test/integration/tests/pcrreset.sh
tools/tpm2_pcrreset.c

Resolve #853
- Added command to makefile
- Added manual entry for tpm2_pcrreset
- Added command relying on ESAPI
- Added integration test for coverage
Signed-off-by: sebastien le stum <lestums@protonmail.com>

tools/tpm2_pcrreset: Add command to reset one or more PCR indexes

---

CHANGELOG.md
lib/tpm2_auth_util.c
man/common/authorizations.md
test/integration/tests/changeauth.sh
test/unit/test_tpm2_auth_util.c

Add support for reading an authorisation password from a file. This helps
keep the authorisation information private from UNIX utilities such as ps.

lib/tpm2_auth_util: add support for reading auth passwords from a file

---

.ci/download-deps.sh
.gitignore
Makefile.am
configure.ac

This PR applies the following recent changes to the build system from tpm2-tss:
- Support for Autoconf Archive 2019.01.06: https://github.com/tpm2-software/tpm2-tss/pull/1238, including the fix for older versions in https://github.com/tpm2-software/tpm2-tss/pull/1256
- Installation of the aclocal macros to the `m4/` subdirectory: https://github.com/tpm2-software/tpm2-tss/pull/1245
- Removal of the Gnulib dependency: https://github.com/tpm2-software/tpm2-tss/pull/1254

Apply build changes from tpm2-tss

---

.ci/docker.run
Makefile.am

This commit removes the manual launching of the dbus session bus
instance in the docker.run file. This is replaced by adding the
'dbus-run-session' command to the AM_TEST_ENVIRONMENT. This allows
callers to simply execute 'make check' and the test harness will set up
a session bus instance automagically.

build: Use dbus-run-session in automake test harness.

---

.gitignore
Makefile.am
configure.ac
test/unit/test_files.c
test/unit/test_pcr.c
test/unit/test_string_bytes.c
test/unit/test_tpm2_alg_util.c
test/unit/test_tpm2_attr_util.c
test/unit/test_tpm2_errata.c
test/unit/test_tpm2_header.c
test/unit/test_tpm2_password_util.c
test/unit/tpm2-rc-decode_unit.c
test/unit/tpm2-rc-entry_unit.c

It would be nice to have the following PRs in the next release of tpm2-tools 3.X:
- #1277 and #1279 because the issues these PRs fix lead to errors in the Arch Linux reproducible builds scripts, see #1278. Note that #1279 needs an additional fix in `Makefile.am` in comparison to the master branch, see https://github.com/tpm2-software/tpm2-tools/pull/1279#issuecomment-454125823.
- #1292 because Gentoo (and probably other distributions as well) needs these changes to build with the recent version 2019.01.06 of Autoconf Archive, see e.g. https://github.com/tpm2-software/tpm2-tss/pull/1245 or https://github.com/tpm2-software/tpm2-tss/issues/1250.

Backport PR #1277, #1279 and #1292 to 3.X

---

test/integration/tests/createak.sh
test/integration/tests/nv.sh
tools/tpm2_createak.c
tools/tpm2_nvrelease.c

tpm2_createak and tpm2_nvrelease both had errors whereby we were passing the incorrect auth session handle into Esys API calls. This PR fixes both tools and adds integration tests to check that authorisation works correctly with them.

Fix incorrect auth session handle usage

---

man/tpm2_create.1.md

tpm2_create no longer supports a -o flag, so remove it
from the examples in the manpage to avoid confusion.

tpm2_create: remove non-existent flag from examples

---

lib/tpm2_identity_util.c
lib/tpm2_identity_util.h
lib/tpm2_openssl.c
lib/tpm2_openssl.h
lib/tpm2_options.c
lib/tpm2_options.h
man/tpm2_makecredential.1.md
test/integration/tests/makecredential.sh
tools/tpm2_import.c
tools/tpm2_makecredential.c

Performing the Make Credential routine does not require usage of a TPM, though the current implementation relies on leveraging the TPM to perform this function.  This PR adds functionality to tpm2_makecredential that allows it to perform this routine without needing a TPM to be present, supporting RSA right now. 
A large portion of this PR involves moving shared code from tpm2_import.c into a new library called tpm2_identity_util.c, since the TPM-less makecredential also will use these functions.  Some of these functions were renamed to be compliant with the library naming conventions (e.g., begin with "tpm2_identity_util_XX"). 
The function `tpm2_identity_util_encrypt_seed_with_public_key` was also generalized to accept either IDENTITY mode or DUPLICATE mode (so it still supports …

Add ability to run tpm2_makecredential without a TPM

---

CHANGELOG.md
man/tpm2_create.1.md
test/integration/tests/create.sh
tools/tpm2_create.c

Allow tpm2_create to take the -c/--context output option to
produce a context file similar to tpm2_load()
Internally, this will yeild a call to ESYS_CreateLoaded over
ESYS_Create thus producing the loaded ctx object.
Fixes: #832

tpm2_create: add TPM CreateLoaded support

---

tools/tpm2_nvlist.c

tpm2_nvlist was not handling the common and TCTI configuration options,
add those by making a call to tpm2_options_new() in a minmial
tpm2_tool_onstart() implementation.

tpm2_nvlist: add option handling for common options

---

test/unit/test_tpm2_alg_util.c

3.X backport of #1254 / re6b9930 originally authored by Safayet Ahmed.
Original description:
Pull request https://github.com/tpm2-software/tpm2-tss/pull/1211/files adds
explicit casts to `TPM2_ALG_ID` macro definitions. That change prevents
stringifying the `TPM2_ALG_ID` macros diretcly, breaking the
`nv_single_item_test2` tests. Instead, use `snprintf` to create the hex-value
strings.
----
Original discussion about this here: https://github.com/tpm2-software/tpm2-tools/pull/1254#issuecomment-463491554

[3.X] test_tpm2_alg_util: fix compatibility with tss 2.2.0+

---

lib/tpm2_errata.c

Passing TPM2_PT_FIXED as count to tpm2_capability_get is semantically
wrong, since it is not a count of anything, but an index into the list of
properties. The intention might have been to just request all the
properties, but this is not necessary since process is only interested in a
small subset of all the properties that can be requested more efficiently.
Signed-off-by: Alexander Steffen <Alexander.Steffen@infineon.com>

tpm2_errata: Do not request unnecessary properties

---

lib/tpm2_capability.c
test/unit/test_tpm2_errata.c

TPM2_GetCapability may return its data in one of several formats, depending
on the capability parameter. All formats are part of a union, but they may
have a different internal structure, so specific union members need to be
accessed to avoid accessing data in the wrong format.
If moreData is set, the next request needs to use a higher value for
property in order to prevent infinite loops. Ideally, the highest value
returned by the TPM +1 is used.
While reworking the code, also avoid unnecessary memory allocations and
just reuse the structure already allocated by Esys_GetCapability.
Fixes #1311.
Signed-off-by: Alexander Steffen <Alexander.Steffen@infineon.com>

tpm2_capability: Fix infinite loop and out-of-bounds memory access

---

INSTALL.md

This was already present for Fedora, but was missing from the description for Ubuntu.

INSTALL.MD: Add missing dependency to autoconf-archive

---

tools/tpm2_rsadecrypt.c
tools/tpm2_rsaencrypt.c

When a user passes a hex id of a TPM2_HANDLE we need to convert those to ESYS_TR handles for use in Esys_ calls.
Fixes #1323

Fix tpm2_rsaencrypt & tpm2_rsadecrypt when key is passed as a hex id

---

Makefile.am
lib/files.c
man/tpm2_stirrandom.1.md
scripts/utils/analyze.py
test/integration/tests/stirrandom.sh
tools/tpm2_stirrandom.c

Fixes: #876
Added command to makefile
Added manual entry for tpm2_stirrandom
Added command relying on ESAPI
Added integration test for coverage

tools/tpm2_stirrandom: Add command to inject additional input in TPM 

---

lib/tpm2_options.c

Coverity reported "Dereferencing a pointer that might be null" due to the
fact that getenv() returns NULL if no matching variable was found in the
environment.
Handle this case by ensuring we assign a value to device when getenv()
returns NULL.

lib/tpm2_options: fix potential dereference of NULL return value

---

test/integration/tests/nv.sh
tools/tpm2_nvdefine.c
tools/tpm2_nvrelease.c

I noticed that the tpm2_nvdefine and tpm2_nvrelease commands do not work without `-a`.
In the former case, it was a bug with the default value.
In the latter case, no default value was set.
Fixed and added a test for default the value for the hierarchy.

nv_define/relase: Default values for hierarchy "-a"

---

Makefile.am
man/tpm2_nvincrement.1.md
scripts/utils/analyze.py
test/integration/tests/nvinc.sh
tools/tpm2_nvincrement.c

Implemented tpm2_nvincrement, a copy/paste/rename from tpm2_nvwrite
I have noticed that the increments do not behave as I would have expected, perhaps I am missing something?
Tested against Infineon TPM9670
$ tpm2_clear
$ tpm2_nvdefine -x 0x1500001 -a o -s 8 -t "ownerread|ownerwrite|nt=1"
$ tpm2_nvdefine -x 0x1500002 -a o -s 8 -t "ownerread|ownerwrite|nt=1"
$ tpm2_nvdefine -x 0x1500003 -a o -s 8 -t "ownerread|ownerwrite|nt=1"
$ tpm2_nvincrement -x 0x1500001 -a o 
$ tpm2_nvread -x 0x1500001 -a o -s 8 | hexdump -C
00000000  00 00 00 00 00 00 00 03                           |........|
$ tpm2_nvincrement -x 0x1500002 -a o 
$ tpm2_nvread -x 0x1500002 -a o -s 8 | hexdump -C
00000000  00 00 00 00 00 00 00 04                           |........|
$ tpm2_nvincrement -x 0x1500003 -a o
$ tpm2_nvread …

Implement tpm2_nvincrement

---

configure.ac

The users asume, unless otherwise stated, that a feature has two states and it is either disabled or enabled.  For features enabled by default, the output of “./configure --help” is supposed to state how ot disable them and for features disabled by default, the very same output is supposed to state how to enable them.
This change adjusts the output of “./configure --help” accordingly.

configure.ac: tweak output of “./configure --help”

---

Makefile.am

This series includes a few build patches. The first 2 patches clean up how we set `AM_TEST_ENVIRONMENT` such that we can override it at _make check_ time.

Various build tweaks

---

lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
man/tpm2_createprimary.1.md
test/integration/tests/createprimary.sh
tools/tpm2_create.c
tools/tpm2_createprimary.c

This change allows creating a primary object that follows
the guidance of https://trustedcomputinggroup.org/wp-content
/uploads/TCG-TPM-v2.0-Provisioning-Guidance-Published-v1r1.pdf
The below should be all on one line:
tpm2_createprimary -a o -G rsa2048:aes128cfb -g sha256
-o prim.ctx
-A 'restricted|decrypt|fixedtpm|fixedparent|
sensitivedataorigin|userwithauth|noda' -u unique.dat
where unique.dat is: 0x00 0x01 (0x00 * 256)
Note that all numbers (as above) must be in little-endian
format. The marhsaling logic will for TPM2B_PUBLIC
will convert to big-endian.
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

tools: Add -u flag for to specify unique data for CreatePrimary

---

configure.ac

The convention is, that the variable enable_hardening is defined by Autoconf.  The code used to define another variable, ${hardening}, that has the same value and purpose as ${enable_hardening}.  This patch abolishes ${hardening} and uses ${enable_hardening}.

configure.ac:AC_ARG_ENABLE(hardening,…) follow Autoconf conventions

---

configure.ac

In AC_ARG_ENABLE(a,b,c,d) enable_a is implicitly set to $enableval, when c is present or absent.

configure.ac: AC_ARG_ENABLE(unit... delete some implicit defaults

---

Makefile.am

When PANDOC is absent, “make dist” fails.
When PANDOC is present, the man pages are generated and man pages are included by “make dist”, as these are prefixed with dist_.
There is no point in putting EXTRA_DIST in AM_CONDITIONAL, as the logic of conditionals is irrelevant when “make dist” calculates which files to include.

Makefile.am: include man pages on “make dist” with the dist_man prefix.

---

lib/tpm2_auth_util.c
test/unit/test_tpm2_policy.c
test/unit/test_tpm2_session.c
tools/tpm2_makecredential.c

Found by http://www.catb.org/~esr/deheader/

deheader: remove double #include’d headers

---

test/integration/tests/unseal.sh
tools/tpm2_unseal.c

Fixes : #1260
Also modified test script to check long option naming

tools/tpm2_unseal: Fix option from "item-context" to "context-object"

---

MAINTAINERS.md

I've been busy with other projects lately and couldn't find time to do the
work expected for someone listed as a maintainer of the project. So remove
myself from the MAINTAINERS.md file.
I will continue maintaining the tpm2-{tools,tss,abrmd} packages in Fedora
and try to help with this project but let's make the file reflect reality.

MAINTAINERS: Remove myself

---

.ci/travis.run

We need to land some fixes to the option parser which would cause the
builds to fail and doing this off master won't get as many eyes on it as
is desirable, therefore temporarily make the option parser finding
conflicts not cause the builds to fail.
Revert this before 4.0

ci: don't fail the build when options analyser finds conflicts

---

scripts/utils/analyze.py

#1330 discovered a bug in the [option analyser](https://github.com/tpm2-software/tpm2-tools/blob/master/scripts/utils/analyze.py): the last entry of an option array is not parsed if it does not end in a comma.
Unfortunately, the problem is deeper than that: if I understand correctly, the script is supposed to find options that are used by only one tool within the current group. Instead, the [current implementation](https://github.com/tpm2-software/tpm2-tools/blob/c66e4f069b04dcb13caed1f6408e4d199e6cf925/scripts/utils/analyze.py#L219) gathers a list of sets of options for each tool in the current group, then takes the symmetric difference of all sets in this list. This results in the [options that are used by an odd number of tools](https://en.wikipedia.org/wiki/Symmetric_difference#n-ary_s …

Fix option analyser

---

Makefile.am
lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
man/tpm2_testparms.1.md
scripts/utils/analyze.py
test/integration/helpers.sh
test/integration/tests/testparms.sh
tools/tpm2_testparms.c

No implementation issue was opened but this tool might be handy in some situation (like migration or tests)
- Added command to makefile
- Added manual entry for tpm2_selftest
- Added command relying on ESAPI
- Added integration test for coverage

tools/tpm2_testparms: Add a tool to check if an algorithm suite is supported

---

Makefile.am

This was the behavior before commit 77a08e4bb989.

Makefile.am: on “make clean” delete the generated man pages

---

Makefile.am

So there is no need to tell the linker to consider $(LIB_COMMON), when it already considers $(LDADD).

Makefile.am: $(LDADD) contains $(LIB_COMMON)

---

lib/tpm2_util.c

Before this change input of "4294967295" generated output of 4294967295, which is UINT32_MAX = 2**32 - 1.  But input "4294967296" created output of 0.  The function is supposed to fail if the number is too big, rather than silently convert unsigned long int to uint32_t, ignoring some bits.

lib/tpm2_util.c:string_to_uint32: ensure the string does not overflow in uint32

---

tools/tpm2_changeauth.c

Introduced by commit ed4c389f7.  This parameter is neither described nor handled.

tools/tpm2_changeauth.c:tpm2_tool_onstart() there is no command line parameter -S

---

CHANGELOG.md
man/tpm2_hash.1.md
man/tpm2_policyauthorize.1.md
man/tpm2_quote.1.md
man/tpm2_sign.1.md
man/tpm2_verifysignature.1.md
scripts/utils/analyze.py
test/integration/tests/checkquote.sh
test/integration/tests/hash.sh
test/integration/tests/import.sh
test/integration/tests/loadexternal.sh
test/integration/tests/output_formats.sh
test/integration/tests/quote.sh
test/integration/tests/sign.sh
test/integration/tests/verifysignature.sh
tools/tpm2_hash.c
tools/tpm2_quote.c
tools/tpm2_sign.c
tools/tpm2_verifysignature.c

Fixes : #1315
Work is already done on `tpm2_certify`
Some files are left to be checked for the same kind of fix (-G while it can be -g) :
> tools/tpm2_hash.c
> tools/tpm2_quote.c
> tools/tpm2_sign.c
> tools/tpm2_import.c
> tools/tpm2_getmanufec.c
> tools/tpm2_createek.c
> tools/tpm2_create.c
> tools/tpm2_createprimary.c
> tools/tpm2_listpersistent.c
> tools/tpm2_createak.c
> tools/tpm2_encryptdecrypt.c
> tools/tpm2_loadexternal.c
> tools/tpm2_verifysignature.c
Do i proceed on the same PR ?

tools/tpm2_quote: Fix -G option to -g

---

tools/tpm2_createak.c
tools/tpm2_getmanufec.c

The marshaling implementation will set the size field automatically.
Signed-off-by: Jeffrey Ferreira <jeffpferreira@gmail.com>

tools: TPM2B_PUBLIC can be initialized with TPM2B_EMPTY_INIT

---

lib/tpm2_session.c

If an allocation error or a failure on Esys_StartAuthSession occur
when creating the new session object, `s` would eventually be NULL.
The following statement `s->internal.path` would then trigger
a null pointer dereference.
Instead, check for the pointer being invalid and return the error

lib: Fix potential null pointer dereference in tpm2_session

---

lib/pcr.c
lib/pcr.h
lib/tpm2_alg_util.c
test/integration/tests/pcrextend.sh
test/unit/test_tpm2_alg_util.c
tools/tpm2_pcrreset.c

From an undefined variable in "pcrextend.sh" test suite, i carved up to PCR indexes on extend being allowed to be greater to `TPM2_MAX_PCRS`
Fixing everything i noticed from that pertaining PCR ids up to the test i was actually linting :)

Multiple fixes for handling PCR indexes

---

Makefile.am
lib/pcr.c
lib/pcr.h
man/common/pcr.md
man/tpm2_pcrallocate.1.md
test/integration/tests/pcrallocate.sh
tools/tpm2_getcap.c
tools/tpm2_pcrallocate.c

This is mostly an RFC on the command parameter structure.
This is the idea:
```
$ tpm2_pcrallocate     #Will set a default of sha1 + sha256 with pcrs 0-23
$ tpm2_pcrallocate sha1: all sha256: all sha384: all sha512: all
$ tpm2_pcrallocate -P "" sha1: 7 8 9 10 16 17 18 19  sha256: 0 1 2 3 4 5 6
```
What do you think ?
Fixes: #852

Add tool tpm2_pcrallocate

---

test/integration/helpers.sh

From time to time, CI return the following error :
```
tpm2-abrmd command: tpm2-abrmd --allow-root --session --dbus-name=com.intel.tss2.Tabrmd48689 --tcti=mssim:port=48689
WARNING:tcti:src/util/io.c:248:socket_connect() Failed to connect to host ::1, port 48690: errno 99: Cannot assign requested address
** (tpm2-abrmd:17364): WARNING **: failed to initialize device TCTI context: 0xa000a
** (tpm2-abrmd:17364): CRITICAL **: init_thread_func: failed to create TCTI with name "mssim" and conf "port=48689"
```
The rationale behind this fix is that the way we stop simulator and tpm2-abrmd can
leave used TCP sockets in a timeout state. These sockets will eventually be closed
by the system after a certain delay.
Meanwhile, if a test suite's shuffled port match (or is off by one) with a previously …

test/integration: Fix CI random errors on port being unassignable

---

lib/tpm2_error.c
test/integration/tests/rc_decode.sh

Fixes #1399 
I also modified the `rc_decode` test to check output messages.
I based my checks on comments from TSS2 header. The main advantage of that is the test is more comprehensive but IMO not the best solution. 
As the ticket showed that errors can be introduced at this level, as strings from header and internal `tpm2_error` structures are pretty close and no header nor file exist in `tpm2-tools` to provide reliable mapping between values and error strings i assumed this was correct for now.

Fix error messages

---

Makefile.am
man/tpm2_gettestresult.1.md
scripts/utils/analyze.py
test/integration/tests/gettestresult.sh
tools/tpm2_gettestresult.c

- Added command to makefile
- Added manual entry for tpm2_selftest
- Added command relying on ESAPI
- Added integration test for coverage

tools/tpm2_gettestresult: Add tool to get status on tests made by TPM

---

test/integration/tests/incrementalselftest.sh

* If tpm2_incrementalselftest returns "all tested" status for the initial "Get the list of remaining algs to be tested", the test immediately quits with error.
* tpm2_incrementalselftest does not work with an string:
```
$ tpm2_incrementalselftest "sha1 sha256"
ERROR: Got invalid or unsupported algorithm: "sha1 sha256"
```

Fix test incrementalselftest.sh

---

test/integration/tests/rc_decode.sh

The header file location depends on the way tpm2-tss is installed, see https://github.com/tpm2-software/tpm2-tools/pull/1401#discussion_r273539639. Attempt to determine the file location using pkg-config (pending https://github.com/tpm2-software/tpm2-tss/pull/1372), falling back to the default locations `/usr/include` and `/usr/local/include`.

test/integration: don't hardcode header file location

---

CHANGELOG.md
man/tpm2_getrandom.1.md
test/integration/tests/getrandom.sh
tools/tpm2_getrandom.c

Per 16.1 of:
- https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf
It is recommended that TPMs bound entropy available to max hash size in
bytes and always make that available. TPMs do not issue an error when
size requested comes up short. Thus add checks for these two conditions
and allow a --force flag to override this behavior. Document and test.
$ tpm2_getrandom 2000
ERROR: TPM getrandom is bounded by max hash size, which is: 48
Please lower your request (preferred) and try again or use --force (advanced)
ERROR: Unable to run ./tools/tpm2_getrandom
echo $?
1
Fixes: #1405

tpm2_getrandom: bound on max hash size

---

scripts/utils/analyze.py

Also fixed an error exit issue when a tool has not
been found. Python was actually interpreting the
comma as being part of function argument splitter instead
of string expansion delimiter

scripts/utils: Add pcr_allocate in analyze

---

test/integration/helpers.sh
test/integration/tests/clearlock.sh
test/integration/tests/tcti/abrmd/extended-sessions.sh
test/integration/tests/tcti/abrmd/policyauthorize.sh
test/integration/tests/tcti/abrmd/policycommandcode.sh
test/integration/tests/tcti/abrmd/policyor.sh
test/integration/tests/tcti/abrmd/policypassword.sh
test/integration/tests/tcti/abrmd/policysecret.sh

TCTI abrmd tests wasn't shutting down TPM simulator, leaving processes behind.
This could lead also to port being bound and unavailable for testing.
Unfortunately, an outdated option on 'tail' prevented to detect it correctly
on port selection. This has been also fixed while also improving processes
shutdown

test: Add shut_down for abrmd unit tests and fix port detection

---

tools/tpm2_sign.c

The sign context structure should be static as the code depends
on initialization of 0. This can cause weird sideaffects, without
it, like the validation ticket being garbage and the TPM rejecting
signatures.

tpm2_sign: make context static

---

test/integration/helpers.sh
test/integration/tests/activecredential.sh
test/integration/tests/getcap.sh
test/integration/tests/listpersistent.sh
test/integration/tests/print.sh

`yaml.load` is [deprecated since PyYAML 5.1](https://msg.pyyaml.org/load) because it is unsafe, therefore it now emits a warning
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```
A safer alternative is `yaml.safe_load`, which is available in all PyYAML versions. It only parses a subset of YAML, but this is enough for our purposes. I successfully tested this with PyYAML 3.13 and 5.1, the latter does not emit `YAMLLoadWarning`s any more with this PR.
Fixes #1420

test/integration: replace yaml.load by yaml.safe_load

---

Makefile.am

The variables $(builddir) and $(abs_builddir) were introduced in Autoconf 2.53 back in 2002.
Thus if $(builddir) is available, so is $(abs_builddir).  There is no need to duplicate the functionality of the latter by using $(abs_build_dir).

Makefile.am: substitute $(abs_build_dir) → $(abs_builddir)

---

test/integration/helpers.sh

Only a few lines later the variable TPM2TOOLS_TCTI is set to a new value:
```diff
diff --git a/test/integration/helpers.sh b/test/integration/helpers.sh
--- a/test/integration/helpers.sh
+++ b/test/integration/helpers.sh
@@ -290,9 +290,8 @@ function start_up() {
echo "Setting TCTI to use abrmd"
echo "export TPM2TOOLS_TCTI=\"$tpm2_tcti_opts\""
export TPM2TOOLS_TCTI="$tpm2_tcti_opts"
elif [ -n "$TPM2_SIM" ]; then
-        export TPM2TOOLS_TCTI="socket:port=$tpm2_sim_port"
echo "Not starting tpm2-abrmd"
echo "Setting TCTI to use mssim"
echo "export TPM2TOOLS_TCTI=\"mssim:port=$tpm2_sim_port\""
export TPM2TOOLS_TCTI="mssim:port=$tpm2_sim_port"
```

test/integration/helpers.sh:start_up: remove unused line

---

dist/bash-completion/tpm2-tools/tpm2_completion.bash

* Align `dist/bash-completion/tpm2-tools/tpm2_completion.bash` to the conventions used in github.com/scop/bash-completion/completions
* Don’t leak the variable suggestions in the environment
* Handle `--tcti=<TAB>` and `-tcti<SPACE><TAB>` the same way (and all other --long-options)
* Skip calling `tpm2_… --help no-man`, when the results of the call are irrelevant
* Complete on `--help <TAB>` with "man no-man", not with "summary manpage"

Bash completions refinements

---

man/tpm2_readpublic.1.md

The tool uses --context, not --context-object.
https://github.com/tpm2-software/tpm2-tools/blob/0a326e5b5d716c4552a5b5e31dcb5f9ec52ba4fa/tools/tpm2_readpublic.c#L152
Fixed the man-page.

MAN: Fix context parameter for tpm2_readpublic

---

.ci/docker.run
.ci/download-deps.sh

Also backport #1437 to the 3.0.X branch.

[3.0.X] Fix Travis CI build

---

.ci/docker.run
.ci/download-deps.sh

The new Dockerfile-based container has `tpm_sever` on the path (in `/usr/local/bin`) instead of in `/ibmtpm974/src`. This should hopefully fix the build failures observed by #1390 and #1430.

[3.X] Fix Travis CI build

---

test/system/test_tpm2_quote.sh
tools/tpm2_quote.c

It looks like the code to take in an AK password existed in tpm2_quote, but wasn't actually wired in to the tool (so it was basically ignored).  
This PR wires in the AK password so it can be used if an AK password is set.

Wire up support for ak auth password in tpm2_quote tool

---

Makefile.am
man/tpm2_pcrreset.1.md
test/system/test_tpm2_pcrreset.sh
tools/tpm2_pcrreset.c

Backport the tpm2_pcrreset tool to 3.X branch (based on commit [0ef0f31775](https://github.com/tpm2-software/tpm2-tools/commit/0ef0f3177532205fa6ed8e8ecc384d7a8fb3457b))

Backport tpm2_pcrreset tool to 3.X

---

lib/tpm2_options.c
lib/tpm2_options.h
man/common/tcti.md
man/tpm2_activatecredential.1.md
man/tpm2_certify.1.md
man/tpm2_encryptdecrypt.1.md
man/tpm2_makecredential.1.md
test/integration/tests/getrandom.sh
test/integration/tests/makecredential.sh
tools/tpm2_makecredential.c

The -X option was introduced as a global option, which presented some
issues, notably:
1. Possible NULL pointer dereferences on tools unaware of a possible
NULL ESAPI.
2. Globaly reserved option for many tools that don't need it.
To correct this, make a new ESAPI flag for optional SAPI initialization
and couple it with a new TCTI called "none". Tools that have this
optional SAPI flag set, will also support --tcti=none. Tools that don't
support the "none" tcti, will throw an error. Update the makecredential
test which was using -X and and a negative test to getrandom to make
sure the none tcti fails properly when a tool requires a SAPI.
Fixes: #1442
Also, correct some other issues noticed along the way:
- man page -X in examples
- UINT32/UINT8 to uint32_t uint8_t.

remove option: -X|--openssl-backend

---

lib/tpm2_alg_util.c
man/common/alg.md
man/common/object-alg.md
man/tpm2_createprimary.1.md
tools/tpm2_createprimary.c

Set `DEFAULT_PRIMARY_KEY_ALG` of `tpm2_createprimary` to `rsa` instead of `rsa2048:aes256`.
So default algorithm of `tpm2_createprimary` is also compliant with "TCG PC Client Platform TPM Profile (PTP)", where AES256 is still optional.

Set default aes key size to 128 bit

---

Makefile.am
lib/tpm2_identity_util.c
lib/tpm2_identity_util.h
lib/tpm2_openssl.c
lib/tpm2_openssl.h
lib/tpm2_options.c
lib/tpm2_options.h
man/common/tcti.md
man/tpm2_activatecredential.1.md
man/tpm2_certify.1.md
man/tpm2_create.1.md
man/tpm2_encryptdecrypt.1.md
man/tpm2_getpubak.1.md
man/tpm2_makecredential.1.md
test/system/test_tpm2_makecredential.sh
tools/tpm2_makecredential.c

Backport the tpm2_makecredential tool changes that allow off-TPM (openssl) functionality to 3.X
Used some functions from tpm2_import for off-TPM functionality
- Move needed, overlap code into tpm2_identity_util
Add new global -X/--openssl-backend option for any tools that can operate w/o TPM

Backport ability to run tpm2_makecredential off-TPM to 3.X

---

man/tpm2_changeauth.1.md
man/tpm2_create.1.md

Based on 9f4d93f7945ef9e1aa797afb8535556e4414e3fb, the option changed.
Need to update man page too.

man/tpm2_changeauth: Fix typo

---

configure.ac

* avoid defining `unit_test_checks`, just call its body, when `test $enable_unit!=no`
* skip the third parameter of `AS_IF`, if it is [].
* if the second parameter of `AS_IF` is [], negate the condition and remove the second parameter
* replace `x"yes"` with `xyes`

configure.ac: subjective simplifications

---

Makefile.am
man/tpm2_flushcontext.1.md
test/system/test_tpm2_flushcontext.sh
tools/tpm2_flushcontext.c

Not the whole program was backported, because of the ESYS-SAPI conversion. Only flushing of all handles of a group and a particular handle are supported in this.
And since I'm completely unbeknown to the old SAPI conventions, please give this a deep review. Hope it works ok for addition.
Fixes: #1452

Backport tpm2_flushcontext to 3.X

---

CHANGELOG.md
lib/tpm2_auth_util.c
man/common/authorizations.md
man/tpm2_nvincrement.1.md
man/tpm2_nvread.1.md
man/tpm2_nvwrite.1.md
test/integration/tests/nv.sh
test/integration/tests/nvinc.sh
test/integration/tests/unseal.sh
tools/tpm2_nvincrement.c
tools/tpm2_nvread.c
tools/tpm2_nvwrite.c
tools/tpm2_unseal.c

Drop the -F and -L options on nvread, nvwrite, nvincrement and unseal and support via a pcr authorization mini-language. By default, all tools will now support satisfying simple PCR policies via authorization strings.
Fixes: #1016

pcr policy: drop -L and -F options and move to policy lang

---

tools/tpm2_getmanufec.c

This is a compile error on some systems.
I have no idea why the tabrmd test is failing...
tabrmd upstream issue ?

Tools: Fix unused return value of BIO_flush

---

tools/tpm2_evictcontrol.c

With commit 9c3e6387 ("tpm2_evictcontrol: support saving ESYS_TR") the
persistent handle is printed twice, with two different names
('persistentHandle' vs 'persistent-handle').
Only one of them is needed, and the latter is closer to other similar
outputs.

Remove duplicated output of persistent handle

---

configure.ac
lib/tpm2_options.c
lib/tpm2_tcti_ldr.c

Default configure passes all configure options like #defines through the
command line which can result in over-length commandlines.  Its better
to use a config.h
Fixes: #1262

configure: switch to autoheader

---

CHANGELOG.md
lib/.gitignore
man/tpm2_createak.1.md
man/tpm2_createprimary.1.md
man/tpm2_load.1.md
man/tpm2_loadexternal.1.md
man/tpm2_startauthsession.1.md
test/integration/tests/activecredential.sh
test/integration/tests/checkquote.sh
test/integration/tests/createak.sh
test/integration/tests/makecredential.sh
test/integration/tests/output_formats.sh
test/integration/tests/print.sh
test/integration/tests/quote.sh
test/unit/test_files.c
tools/tpm2_createak.c
tools/tpm2_load.c
tools/tpm2_loadexternal.c
tools/tpm2_startauthsession.c

- get rid of the default file names and make them required options.
- update gitignore file to ignore config.h
- get rid of the persistent option in tpm2_createak, that can be done with tpm2_evictcontrol.

Default file fixes

---

Makefile.am

Some files were missing from the distribution tarball, add them:
- tests
- scripts
- bootstrap
Add a disthook to remove things we want to ignore from recursively
included directories.
Fixes: #1469

Makefile.am: make dist include missing files

---

test/integration/tests/activecredential.sh
tools/tpm2_activatecredential.c

This solves issue #1453.
Thanks @dgptha for raising the issue and also proposing the fix going into this commit.

Fix an issue where credential activation fails if Ak password is set

---

configure.ac

Currently trying to build the Git version of tpm2-tools fails with 
```
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
^~~~~~~
```
The reason is that `AX_CHECK_ENABLE_DEBUG([yes])` introduced by #1486 disables optimisation, but `_FORTIFY_SOURCE` set as part of the default hardening requires at least `-O1`. (The CI is not affected because it uses `--disable-hardening`.) According to the [Autoconf Archive manual](https://www.gnu.org/software/autoconf-archive/ax_check_enable_debug.html), the solution is to use `info` instead of `yes` to retain optimisation:
> Specifying ’yes’ adds ’-g -O0’ to the compilation flags for all languages. Specifying ’info’ adds ’-g’ to the compilation flags. Specifying ’profile’ adds ’-g -pg’ …

configure: use AX_CHECK_ENABLE_DEBUG([info])

---

.ci/docker.run

Currently the whitespace error check is always performed against the master branch. Therefore it fails on different branches because Travis CI only does a shallow clone of the current branch. Replacing it with `$TRAVIS_BRANCH` allows to test against the correct base branch for pull requests and is a no-op if a branch is built directly. In case the CI scripts are used locally without Travis, use the master branch as a default for `$TRAVIS_BRANCH` to retain the current behaviour.
This fixes #1482, see https://travis-ci.org/diabonas/tpm2-tools/builds/533291219 for a successful build of a feature branch on a personal repository.

ci: check for whitespace errors against $TRAVIS_BRANCH

---

Makefile.am
test/integration/tests/tcti/abrmd/policypassword.sh

For it to work, This change is contingent on an ESAPI change in the PR below
esys_iutil.c: Update session attribute in cmdauths structure for policy sessions #1407

policypassword: Fix policypassword integration test and revert it from XFAIL list

---

Makefile.am
man/tpm2_clearcontrol.1.md
scripts/utils/analyze.py
test/integration/tests/clearcontrol.sh
tools/tpm2_clearcontrol.c

This PR commit simply renames the tool from tpm2_clearlock to tpm2_clearcontrol.
It partially addresses issue #1147. Need to add more commits for sanitizing tool options.

Rename the tool tpm2_clearlock to tpm2_clearcontrol to match spec TPM command name

---

lib/tpm2_tcti_ldr.c
lib/tpm2_util.h

The TCTI option string is allowed to remain NULL, and thus
passing it as an argument to printf("%s") is not portable.
GLIBC will print (null) but some systems will crash.
Define a macro that will return the string "(null)" when the
string is NULL so other LIBC's have the same behavior as
GLIBC.
Fixes: #1241

tpm2_tcti_ldr: safe print option string

---

test/integration/tests/attestation.sh
tools/tpm2_activatecredential.c

Together with fix from https://github.com/tpm2-software/tpm2-tools/pull/1499 this now matches the docs at [tss2-esys/api/Esys_ActivateCredential.c](https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-esys/api/Esys_ActivateCredential.c#L18) (so comment was removed). 
Added attestation test (already on 3.X branch) to test out the full attestation process (which also tests that the included fix works correctly).

Fix eauth activate and add attestation test (prevent regression)

---

Makefile.am
test/unit/test_tpm2_auth_util.c

A foobar file is created but not cleaned at end of tpm2_auth_util unit test. 
This fixes the issue #1496 

test_tpm2_auth_util.c: Remove foobar file created as part of tpm2_auth_util unit test run

---

configure.ac

Backport #1512 to 3.X: existence of tss2-mu was already checked, albeit in a separate `PKG_CHECK_MODULES` call, which means that `SAPI_LIBS` only contains `-ltss2-sys` from the first call. Make sure that it contains `-ltss2-mu` as well by using only a single `PKG_CHECK_MODULES` for both libraries.
As per https://github.com/tpm2-software/tpm2-tss/pull/1417#issuecomment-494036214, this should go into the 3.2 release so that building works correctly for tss2-sys ≩ 2.3.

[3.X] build: link against tss2-mu

---

test/integration/tests/import.sh

In the test `import.sh`, the decryption was broken due to two problems:
- `openssl enc` expects the ciphername as a parameter (either `-aes-128-cfb` or `-aes-256-cfb`). Previously we always passed `-aes-128-cfb` (which broke decryption for aes256)
- `xxd` is used to convert binary data into a hex string. However, `xxd` eventually breaks the line. To prevent this, `-c 256` is added to be able to convert to up to 256 chars without line break. Fixes #1146 
Also, a minor indentation issue is fixed.
Unfortunately, this test passed even if it was broken. This is due to the fact that bash traps are not inherited to bash functions. See #1535.

test: aes256 key trunctuated in import.sh

---

configure.ac

When unit tests are requested, include in the summary which prerequisite was found.

configure.ac: print summary at the end

---

lib/object.c
lib/object.h
lib/tpm2.c
lib/tpm2.h
lib/tpm2_util.c
lib/tpm2_util.h
tools/misc/tpm2_checkquote.c
tools/tpm2_activatecredential.c
tools/tpm2_certify.c
tools/tpm2_changeauth.c
tools/tpm2_create.c
tools/tpm2_createak.c
tools/tpm2_duplicate.c
tools/tpm2_encryptdecrypt.c
tools/tpm2_evictcontrol.c
tools/tpm2_flushcontext.c
tools/tpm2_hmac.c
tools/tpm2_import.c
tools/tpm2_load.c
tools/tpm2_policysecret.c
tools/tpm2_quote.c
tools/tpm2_readpublic.c
tools/tpm2_rsadecrypt.c
tools/tpm2_rsaencrypt.c
tools/tpm2_sign.c
tools/tpm2_startauthsession.c
tools/tpm2_unseal.c
tools/tpm2_verifysignature.c

This PR continues work on plumbing back the Esys_ and TSS2_ calls to a flattened RC and moving the calls into tpm2.c so we can ensure consistent error logging and error returns across tooling (#1193). Additionally it starts looking at #1539 and places the tpm2_session data for an object in the object itself and moves the logic for converting these data structures to Esys ones inside the tpm2.c calls for create and createloaded.

continue work on exit codes and update tpm2_create to a new interface

---

test/integration/tests/import.sh

import.sh: Remove spurious tpm2_evictcontrol usage in the cleanup routine

---

man/tpm2_loadexternal.1.md
test/integration/helpers.sh
test/integration/tests/activecredential.sh
test/integration/tests/attestation.sh
test/integration/tests/checkquote.sh
test/integration/tests/create.sh
test/integration/tests/createak.sh
test/integration/tests/createek.sh
test/integration/tests/createprimary.sh
test/integration/tests/dictionarylockout.sh
test/integration/tests/evictcontrol.sh
test/integration/tests/getmanufec.sh
test/integration/tests/gettestresult.sh
test/integration/tests/hmac.sh
test/integration/tests/import.sh
test/integration/tests/incrementalselftest.sh
test/integration/tests/load.sh
test/integration/tests/loadexternal.sh
test/integration/tests/nv.sh
test/integration/tests/nvinc.sh
test/integration/tests/pcrevent.sh
test/integration/tests/quote.sh
test/integration/tests/sign.sh

As discussed in #1535, the bash ERR trap is not inherited to bash functions. As a consequence, commands in bash functions will not lead to a failed test even if they return a non-zero error code.
To inherit the trap, the option `-E` has to be passed:
If set, any trap on ERR is inherited by shell functions, command substitutions,
and commands executed in a subshell environment. The ERR trap is normally not
inherited in such cases.
Due to this issue, quite some problems have been missed. This PR also fixes those. Additionally, a man typo is fixed.
Fixes #1535.

Tests might not fail since traps are not inherited to bash functions

---

lib/object.c
lib/tpm2.c
lib/tpm2.h
lib/tpm2_hierarchy.c
lib/tpm2_hierarchy.h
lib/tpm2_util.c
man/common/ctxobj.md
man/tpm2_changeauth.1.md
test/integration/tests/attestation.sh
test/integration/tests/changeauth.sh
test/integration/tests/checkquote.sh
test/integration/tests/createak.sh
test/integration/tests/getmanufec.sh
test/integration/tests/nv.sh
test/integration/tests/nvinc.sh
test/integration/tests/tcti/abrmd/policysecret.sh
tools/tpm2_changeauth.c
tools/tpm2_startauthsession.c

tpm2_changeauth has the ability to change multiple TPM objects at once,
which made the interface complicated and difficult to use. Change the
interface to only be able to set one object at a time.
Fixes: #1289

tpm2_changeauth: reconfigure options

---

.ci/docker.run

Similar to https://github.com/tpm2-software/tpm2-tss/pull/1446, most of the CI time is spent on running the integration test suite, which is not CPU bound, so allowing more parallel jobs allows for some speedup. This reduces the CI time from about [00:12 real-time/00:23 total](https://travis-ci.org/diabonas/tpm2-tools/builds/546159523) to about [00:08 real-time/00:12 total](https://travis-ci.org/diabonas/tpm2-tools/builds/546161799).

ci: don't limit the amount of parallel jobs for make check

---

test/integration/helpers.sh
test/unit/test_tpm2_policy.c

Currently the CI seems to have some problems (cf. the failed builds [#3004](https://travis-ci.org/tpm2-software/tpm2-tools/builds/546173212) and [#3005](https://travis-ci.org/tpm2-software/tpm2-tools/builds/546342459)) due to PR #1553 starting all integration tests in parallel. Unfortunately I can't reproduce this problem locally on my system or with the Dockerfile, but from the CI logs, this seems like this is a [TOCTOU](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) problem between checking whether the simulator ports are free and actually starting the simulator on the specified ports. Fix this by trying to start the simulator first, then check whether it is listening on the port and retry if necessary.
While testing this, I once came across a different race condition in …

 test/integration: check if port is bound to the simulator

---

tools/tpm2_encryptdecrypt.c

After 75b60808, `iv_out` is dereferenced before the error check of `Esys_EncryptDecrypt2()` or `Esys_EncryptDecrypt()`. This lead to a Segmentation Fault if `Esys_EncryptDecrypt()` failed. Consequently, the error check has to be moved up again.

tools: fix dereferencing of null pointer in tpm2_encryptdecrypt

---

lib/tpm2_hierarchy.c

Fixes #1510
This commit fixes an issue wherein the filtering of the valid
hierarchies is skipped if value is specified as a hex number
as supposed to a string. Eg: 0x40000007 vs "null"

tpm2_hierarchy.c: Fix hierarchy filtering bug

---

man/tpm2_checkquote.1.md
tools/misc/tpm2_checkquote.c

Rename `--sig` to `--signature` for both the man page and the tool to align the options of `tpm2_checkquote` with `tpm2_quote`.
Fixes #1488.

man/tools: rename option --sig to --signature for tpm2_checkquote

---

lib/tpm2_alg_util.c
test/integration/tests/incrementalselftest.sh

Add CMAC to the list of known algorithms. This PR requires https://github.com/tpm2-software/tpm2-tss/pull/1437 to be merged first so that `TPM2_ALG_CMAC` is defined. The new algorithm is also accidentally included in `eccmethods` and `rsamethods` in `incrementalselftest.sh`, rework the conditions to avoid that.
These are the minimal changes to fix the test suite for the most recent TPM simulator version 1332, please advise if there are more places within tpm2-tools where the new algorithm needs to be added.
Fixes: #1532

 tpm2_alg_util: add CMAC algorithm

---

Makefile.am
lib/tpm2_cc_util.c
lib/tpm2_cc_util.h
man/tpm2_policycommandcode.1.md
test/integration/tests/abrmd_policycommandcode.sh
test/integration/tests/import_tpm.sh
test/unit/test_cc_util.c
tools/tpm2_policycommandcode.c

Ass support for passing nice names to the tool, like duplicate instead
of 0x14B. Keep raw numeric support in place and add tests.
Fixes: #1242

tpm2_policycommandcode: add nice name resolution

---

man/tpm2_encryptdecrypt.1.md
test/integration/tests/encryptdecrypt.sh
tools/tpm2_encryptdecrypt.c

Progresses #1547
1. Rename cmdline option to pkcs7-pad
2. Separate out a function for pkcs7 padding
3. Use memset instead of for loops to allow compiler to optimize padding
4. Fix: Padding is necessary also for data that is aligned at block length
5. Add tests for checking padding on data that is aligned at block length 
6. Fix: Strip padding data when decrypting
7. Add tests for checking pad data is stripped on input data with aligned block length
8. Add tests for checking pad data is stripped on input data with unaligned block length

tpm2_encryptdecrypt: Update encryptdecrypt tool and man page

---

lib/tpm2_errata.c

The commit ac9a5d78 wrongly clears up all attributes, resulting in
a zeroed attribute returned when applying errata.
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>

tpm2_errata: Fix zeroed attribute returned by errata handler

---

lib/tpm2_alg_util.c
man/common/alg.md
test/integration/tests/abrmd_policycommandcode.sh
test/integration/tests/create.sh
test/integration/tests/readpublic.sh
test/integration/tests/rsadecrypt.sh
test/integration/tests/rsaencrypt.sh
test/integration/tests/sign.sh
test/integration/tests/testparms.sh
test/integration/tests/verifysignature.sh
test/unit/test_tpm2_alg_util.c

If one attempts to specify such algorithm permutation:
- ecc256<insert_something_here>
For example:
-  ecc256funnytexthere
The tool will silently convert the algorithm specifier into ecc256:null:null.
The same behavior can be obtained by using RSA or any algorithm specification
that has data between identifier and the colon (or NULL) and where beginning
of the spec. is correct (all permutations of ecc/rsa with a valid curve/key size)
On top of that, algorithms defaults changes between restricted and non restricted modes.
ecc256:null:null in non restricted
ecc256:null:aes128cfb in restricted
Correct this by issuing errors when invalid text strings are presented.
Fixes: #1371

tpm2_alg_util: fix extended specifier errors

---

test/integration/tests/testparms.sh

When using the latest version 1332 of the TPM simulator, the integration test [`testparms.sh`](https://github.com/tpm2-software/tpm2-tools/blob/master/test/integration/tests/testparms.sh) fails with
```
[...]
tpm2_testparms rsa:rsapss
tpm2_testparms rsa:cmac
ERROR: Could not handle algorithm spec: "rsa:cmac"
ERROR: Invalid or unsupported by the tool : rsa:cmac
tpm2_testparms "rsa:${i}" on line 34 failed: 1
[...]
```
The cause for this is the same as in #1533, and the same solution as in  333cfcaabadea98c0d2a741ade23b71f87fdcaf5 applies.

test/integration: remove cmac from eccmethods and rsamethods

---

configure.ac

Rather than warn some tests might fail, just fail during ocnfigure.
Fixes: #1368

configure: make missing executables for test fail

---

man/tpm2_activatecredential.1.md
man/tpm2_certify.1.md
man/tpm2_clear.1.md
man/tpm2_clearcontrol.1.md
test/integration/tests/activecredential.sh
test/integration/tests/attestation.sh
test/integration/tests/changeauth.sh
test/integration/tests/clear.sh
test/integration/tests/clearcontrol.sh
tools/tpm2_activatecredential.c
tools/tpm2_certify.c
tools/tpm2_clear.c
tools/tpm2_clearcontrol.c

tpm2_clearcontrol: Change short option for -a to -c
tpm2_clear: Add a test for evaluating tpm2_clear implementation
tpm2_clear: Change option to specify the hierarchy used to clear
tpm2_clear: Change input password option to argument
certify: Change tool options
activatecredential: Change tool options
Progresses #1042

Tools options changes

---

test/integration/tests/clear.sh

The new test `clear.sh` introduced in 8821cff6 changes the platform auth but does not change it back after it is done. If possible, tests should always clean up after themselves.
After 8821cff6, when running `tpm2_clearcontrol` after the test is done, an authorization failure (`0x9A2`) occurs. Hence, `tpm2_changeauth` has to be called in the end of the test to reverse the change.

test: undo change of platform auth in clear.sh after test is done

---

man/tpm2_clear.1.md
test/integration/tests/toggle_options.sh

618e7e21c2f79ee3f49e4bbffa318e7ce0792b9a changed the long option name `--platform` of `tpm2_clear` to `--auth-hierarchy` without updating the man page to the new name.
Problems like this are supposed to be detected by the integration test [`toggle_options.sh`](https://github.com/tpm2-software/tpm2-tools/blob/master/test/integration/tests/toggle_options.sh), but this doesn't always work properly: the test uses [`grep -R` without specifying a directory](https://github.com/tpm2-software/tpm2-tools/blob/4ccd3cd6e9bd1e58f264f2d8d111bfdd42f3133f/test/integration/tests/toggle_options.sh#L29), therefore the current directory is searched, which is the build directory in this case. This works as expected when using the source directory as the build directory. However the CI builds in a separate …

 test/integration: specify search directories for toggle_options.sh

---

configure.ac

Enabling optimisation is necessary for fortification, otherwise compilation fails with the error
```
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
|    ^~~~~~~
```
The optimisation level `-O2` chosen here is the default level also used by [`AC_PROG_CC`](https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/C-Compiler.html) (which isn't used here since [`AX_CHECK_ENABLE_DEBUG`](https://github.com/tpm2-software/tpm2-tools/blob/3535ed92281bf975c8b46ab07808480ef23ac96c/configure.ac#L6) explicitly sets `CFLAGS="$CFLAGS -g"`).
Also replace the manual definition of `_FORTIFY_SOURCE` by an Autoconf Archive macro as in …

configure: add -O2 and use AX_ADD_FORTIFY_SOURCE

---

lib/tpm2_hierarchy.c
lib/tpm2_hierarchy.h
test/unit/test_tpm2_hierarchy.c
tools/tpm2_nvincrement.c
tools/tpm2_nvread.c
tools/tpm2_nvreadlock.c
tools/tpm2_nvwrite.c

Progresses #1462
Progresses #880
1. Add filter for checking handle is in valid NV index range
2. Add option to specify NV indices simply as an offset. Eg. 1 for NV index @ 01000001
3. Add unit tests for the added functionality.

lib/tpm2_hierarchy: Add filtering for NV Indices

---

lib/tpm2.c
test/integration/tests/encryptdecrypt.sh
tools/tpm2_encryptdecrypt.c

Fixes #1547 
In order to make the tpm2_encryptdecrypt interoperable with openssl, below fixes have been implemented:
1. Do not apply pkcs7 padding to all aes modes and in particular to aes cfb mode
2. The input iv for aes ecb mode should be set to null
3. Padded block length was wrongly set to key size; instead it should have been fixed to AES block length of 16 bytes or 128 bits.

Fix tpm2_encryptdecrypt pcks7 padding scheme

---

lib/tpm2_options.c
test/unit/test_options.c

As described in #1617, the tools currently return with a zero exit status signalling success if the TCTI could not be initialised. This is because the variable `rc` is used for both return codes of type `TSS2_RC` as well as `tpm2_option_code` internally used by tpm2-tools. Using separate variables for both types fixes the problem. I also added a unit test to verify that an invalid TCTI results in a non-zero exit status.
While fixing this issue, I noticed that for the long option only `--tcti=<value>` is accepted while `--tcti <value>` does not work. This is because 56710b6e1c4d3e02ff77ad367c216a59b51ca765 changed the long option from `required_argument` to `optional_argument`, and optional arguments only work with the equals sign syntax. Since this does not match the definition of the …

 tcti: use separate rc variable for Tss2_TctiLdr_* 

---

tools/tpm2_policyor.c

-L is only needed if raw access to the policy digest is needed, ie trial sessions. When satisfying a policy one doesn't need it.

tpm2_policyor: make -L optional

---

lib/tpm2_attr_util.c
lib/tpm2_policy.c
lib/tpm2_policy.h
tools/misc/tpm2_checkquote.c
tools/misc/tpm2_rc_decode.c
tools/tpm2_policyor.c
tools/tpm2_rsadecrypt.c
tools/tpm2_send.c
tools/tpm2_verifysignature.c

The newly added LGTM analysis (#1620) found [some alerts](https://lgtm.com/projects/g/tpm2-software/tpm2-tools/alerts/). Nothing really critical, but it might be nice to keep the number of alerts close to zero to see real problems more easily.

Fix LGTM alerts

---

lib/tpm2_policy.c
lib/tpm2_policy.h
tools/tpm2_policyauthorize.c
tools/tpm2_policycommandcode.c
tools/tpm2_policyduplicationselect.c
tools/tpm2_policylocality.c
tools/tpm2_policyor.c
tools/tpm2_policypassword.c
tools/tpm2_policypcr.c
tools/tpm2_policysecret.c

Make sure that policy tools have consistent output behavior by creating a
common output routine.
Fixes: #1623

tpm2_policy: update policy tools output

---

lib/tpm2_policy.c

Backport #780 to avoid a crash of `tpm2_createpolicy` if more than 8 PCRs are specified.
Fixes: #1632

[3.X] Backport "Limit selected PCRs to 8" (PR #780)

---

man/tpm2_nvincrement.1.md
man/tpm2_nvread.1.md
man/tpm2_nvreadlock.1.md
man/tpm2_nvwrite.1.md
tools/tpm2_nvincrement.c
tools/tpm2_nvread.c
tools/tpm2_nvreadlock.c
tools/tpm2_nvwrite.c

Consider the following example:
```
tpm2_createpolicy --policy-pcr --pcr-list sha256:0,1,2,3 --policy policy.data
tpm2_nvdefine --size 5 --attributes 'policyread|ownerwrite|read_stclear' --policy policy.data 0x1500018
echo test | tpm2_nvwrite --hierarchy o --input - 0x1500018
tpm2_nvread --auth pcr:sha256:0,1,2,3 0x1500018
tpm2_nvreadlock --auth pcr:sha256:0,1,2,3 0x1500018
```
The last command fails with
```
WARNING:esys:src/tss2-esys/api/Esys_NV_ReadLock.c:303:Esys_NV_ReadLock_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_NV_ReadLock.c:109:Esys_NV_ReadLock() Esys Finish ErrorCode (0x0000012f) 
ERROR: Failed to lock NVRAM area at index 0x1500018
ERROR: Esys_NV_ReadLock(0x12F) - tpm:error(2.0): authValue or authPolicy is not available for selected entity
ERROR: Unable to …
```

 tpm2_nvreadlock: use index auth if no --hierarchy is specified

---

man/tpm2_pcrread.1.md

While working on #1638, I noticed an example on the `tpm2_pcrread` man page that has not been updated to the latest syntax yet.

man/tpm2_pcrread: remove spurious -L in example

---

lib/tpm2_policy.c

One of the issues addressed in #1638 is already present in tpm2-tools 3.X, leading to errors like
```
$ tpm2_unseal -L sha256:0+sha1:0 -F file
ERROR: Failed parse_policy_type_and_send_command
ERROR: Building PCR policy failed: 0x1c4
ERROR: Unable to run tpm2_unseal
```
Backport the fix to 3.X as well, also see #1390.

[3.X] lib/tpm2_policy: fix population of pcr_values->digests[].size

---

lib/tpm2_auth_util.c
lib/tpm2_policy.c
man/common/authorizations.md
man/tpm2_unseal.1.md
test/integration/tests/nv.sh
test/integration/tests/nvinc.sh
test/integration/tests/unseal.sh

Fix #1635 by changing the separator for `raw-pcr-file` from `+` to `=`. The equals sign was chosen as the new separator to have a syntax somewhat similar to `tpm2_pcrextend`.
While fixing this issue, I came across a different, unrelated problem with using multiple banks: the feature to use a `raw-pcr-file` of expected PCR values is broken due to a [broken loop counter in `tpm2_policy.c`](https://github.com/tpm2-software/tpm2-tools/blob/d381875156eb9352b1a1ef4cc7d0c903cba878b6/lib/tpm2_policy.c#L56-L59), resulting in errors like
```
$ tpm2_unseal -p pcr:sha256:0+sha1:0=file
WARNING:esys:src/tss2-esys/api/Esys_PolicyPCR.c:288:Esys_PolicyPCR_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_PolicyPCR.c:100:Esys_PolicyPCR() Esys Finish ErrorCode (0x000001c4)
ERROR on line: "53" in …
```

Add ability to use multiple banks in the PCR mini language

---

CHANGELOG.md
lib/tpm2_util.c
lib/tpm2_util.h
man/tpm2_encryptdecrypt.1.md
man/tpm2_policycommandcode.1.md
man/tpm2_policypassword.1.md
man/tpm2_rsadecrypt.1.md
man/tpm2_rsaencrypt.1.md
man/tpm2_send.1.md
man/tpm2_sign.1.md
man/tpm2_startauthsession.1.md
man/tpm2_startup.1.md
man/tpm2_stirrandom.1.md
test/integration/tests/abrmd_policycommandcode.sh
test/integration/tests/abrmd_policypassword.sh
test/integration/tests/encryptdecrypt.sh
test/integration/tests/import.sh
test/integration/tests/import_tpm.sh
test/integration/tests/loadexternal.sh
test/integration/tests/output_formats.sh
test/integration/tests/rsadecrypt.sh
test/integration/tests/rsaencrypt.sh
test/integration/tests/sign.sh
test/integration/tests/verifysignature.sh
tools/tpm2_encryptdecrypt.c
tools/tpm2_rsadecrypt.c
tools/tpm2_rsaencrypt.c
tools/tpm2_sign.c

* tpm2_sign:
- Drop -m and -d option arguments and make them sole argument.
- Remove the -m option and make -d toggle if input is a digest.
* tpm2_encryptdecrypt: drop -i input option and make argument.
* tpm2_rsadecrypt: drop -i input option and make argument.
* tpm2_rsaencrypt: make output binary and either stdout or file based on -o.
* tpm2_rsadecrypt: add support for label via -l.
* tpm2_rsaencrypt: add support for label via -l.

manpage audit

---

tools/tpm2_policyauthorize.c

Fixes #1658 
Fixed option descriptions in the is_check_input_options_ok routines
Changed the global variable from verifying_pubkey_path to verifying_pubkey_name_path.

tpm2_policyauthorize: Fix incorrect text in error logging

---

INSTALL.md
test/integration/tests/getekcertificate.sh

If there is no internet connection, `tpm2_getekcertificate.sh` will always fail.
With this fix, a sanity check is performed:
-   If `curl` is installed:   
If there is no internet connection or if `ekop.intel.com` is down, 77 (`SKIP`) is returned.
-  If `curl` is **not** installed:   
No sanity check is performed. This means the test will fail if the website cannot be reached.

test: add internet connection check for tpm2_getekcertificate.sh

---

tools/tpm2_nvread.c
tools/tpm2_nvwrite.c

This fixes build failures when the gcc -Wmaybe-uninitialized option is enabled.

Fix uninitiailized return vars

---

lib/tpm2_identity_util.c
lib/tpm2_kdfe.c
lib/tpm2_kdfe.h
lib/tpm2_openssl.c
test/integration/tests/import.sh
tools/tpm2_import.c
tools/tpm2_loadexternal.c

Added support for importing an OpenSSL generated private key file using ECC parent key.
I made this patch to (partially) solve issues of tpm2-tss-engine: 
https://github.com/tpm2-software/tpm2-tss-engine/issues/39
https://github.com/tpm2-software/tpm2-tss-engine/issues/12

tpm2_import: add support for ECC parent key

---

tools/tpm2_getekcertificate.c

Fixes #1697
The test is using an equality comparison for the value of
TPM_PT_PERMANENT property with 0x400 whic is a bitset property

tpm2_getekcertificate.c: Fix issue with TPM_RNG_EPS bit comparison

---

.ci/download-deps.sh

Set the test version to the stable TSS release for the upcoming
tpm2-tools 4.0 release.
Fixes: #1709

ci: set tpm2-tss version to 2.3.1

---

.ci/docker.run

This fixes the failing whitespace check when running CI builds for a specific tag, see this [successful build of a custom tag for this PR](https://travis-ci.org/diabonas/tpm2-tools/builds/580333407).

ci: skip whitespace checking if running CI for a specific tag

---

configure.ac

Man pages are only built if pandoc is installed, but it's easy to miss
checking for pandoc... no
configure: WARNING: Required executable pandoc not found, man pages will not be built
in the middle of the 120 lines of configure output. This commit adds
an explicit "Man pages: yes/no" message to the end of configure
output.
Signed-off-by: Matthew Dempsky <matthew@dempsky.org>

configure.ac: be clearer whether man pages will be installed

---

lib/tpm2.c
lib/tpm2.h
lib/tpm2_hash.c
lib/tpm2_nv_util.h
tools/tpm2_createek.c
tools/tpm2_evictcontrol.c
tools/tpm2_flushcontext.c
tools/tpm2_getekcertificate.c
tools/tpm2_getrandom.c
tools/tpm2_gettestresult.c
tools/tpm2_incrementalselftest.c
tools/tpm2_loadexternal.c
tools/tpm2_makecredential.c
tools/tpm2_nvreadpublic.c
tools/tpm2_pcrevent.c
tools/tpm2_pcrreset.c
tools/tpm2_rsaencrypt.c
tools/tpm2_selftest.c
tools/tpm2_startup.c
tools/tpm2_stirrandom.c
tools/tpm2_verifysignature.c

Move all the ESys_ calls from tools into the lib/tpm2.c interface and use a slightly higher level interface. The igher interface should use tpm2_session *'s, remove unused session handles and tpm2_loaded_object *'s where appropriate.
Fixes: #1520
Fixes: #1539
Replaces PR #1688

tpm2.c layer updates

---

lib/tpm2_convert.c
lib/tpm2_openssl.c
lib/tpm2_openssl.h

No need to hand jam ASN1 structure if you just populate
an ECDSA_SIG object and work on that by setting the R
and S fields.
Fixes: #1649

tpm2_convert: fix ecdsa signature generation

---

lib/tpm2_identity_util.c
lib/tpm2_identity_util.h
tools/tpm2_import.c
tools/tpm2_makecredential.c

This commit changes the
tpm2_identity_util_encrypt_seed_with_public_key in two ways:
1. It changes the callee to always be responsible for generating the
seed, independent of the public key algorithm. Previously, the caller
had to generate a random seed for RSA keys, which was unnecessary for
ECC keys.
2. It renames "encrypt_seed" to "share_secret" to be more consistent
with the name that the TPM 2.0 Library Specification uses for this
mechanism.
Fixes #1730.
Signed-off-by: Matthew Dempsky <matthew@dempsky.org>

tpm2_identity_util: replace "encrypt_seed" with "share_secret"

---

tools/tpm2_policyauthorizenv.c

tpm2_policyauthorize.c: Remove unused variable

---

.ci/travis.run

* LeakSanitizer is making a ptrace call which gets blocked by seccomp.
This patch disables seccomp syscall allowlist which fixes the CI for
clang builds.
Signed-off-by: John Andersen <john.s.andersen@intel.com>

travis: Disable seccomp for docker

---

test/integration/tests/abrmd_policysigned.sh
test/integration/tests/abrmd_policyticket.sh

Fixes #1774
Piping stdout output to OpenSSL command line application is causing
failures at random when run under travis. To address this the shell
commands are split to avoid piping data to OpenSSL command line tool.

abrmd_policysigned.sh: Fix for failing openssl calls in travis

---

configure.ac
lib/tpm2.c
lib/tpm2.h
tools/tpm2_loadexternal.c

To continue discussion started in https://github.com/tpm2-software/tpm2-tss/pull/1531 the tools can handle the API change by some internal remapping like this.

Map TPMI_RH_HIERARCHY type to Esys_TR type

---

man/tpm2_createprimary.1.md
test/integration/tests/createprimary.sh
tools/tpm2_createprimary.c

Add option to tpm2_createprimary to specify outside info to be included in the creation data.

Outside-info

---

.ci/travis.run

Rather than disabling secomp, just use cap ptrace.

travis: use cap sys_ptrace instead of unconfined

---

CHANGELOG.md
Makefile.am
lib/tpm2.c
lib/tpm2.h
lib/tpm2_attr_util.c
man/common/nv-attrs.md
man/tpm2_nvdefine.1.md
man/tpm2_nvsetbits.1.md
man/tpm2_nvwritelock.1.md
test/integration/tests/nv.sh
tools/tpm2_nvdefine.c
tools/tpm2_nvsetbits.c
tools/tpm2_nvwritelock.c

add the nvwritelock and nvsetbits tool, enhance nt field specifiers with friendly names and a few clean up commits.
Fixes: #850
Fixes: #848

tpm2_nvwritelock & tpm2_nvsetbits: add tool

---

CHANGELOG.md
Makefile.am
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvextend.1.md
test/integration/tests/nv.sh
tools/tpm2_nvextend.c

Implement the tpm2_nvextend which will extend, like a PCR, an NV index
with attribute nt=extend.
Fixes: #844

tpm2_nvextend: implement tpm2_nvextend tool

---

CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvundefine.1.md
test/integration/tests/abrmd_nvundefinespecial.sh
tools/tpm2_nvundefine.c

Support CC TPM2_CC_NV_UndefineSpaceSpecial within tpm2_undefine.
Undefine special is used to delete NV indices witrh attribute
TPMA_NV_POLICY_DELETE. Internally the tool looks at the attribute
set of a given NV index and determines which undefine command
to use.
Because the command requires a policy session, the command now
supports option -S for specifying said policy session. This
option is only valid if the NV index attributes contain
TPMA_NV_POLICY_DELETE.
Fixes: #849

tpm2_nvundefine: support undefinespace special

---

lib/files.c
lib/files.h
test/integration/helpers.sh
test/integration/tests/encryptdecrypt.sh
test/integration/tests/stirrandom.sh
tools/tpm2_encryptdecrypt.c
tools/tpm2_nvwrite.c
tools/tpm2_policynv.c
tools/tpm2_stirrandom.c

Fixes #1800 
Makes a test skip helper, I noticed a test was "skipping" but not exiting with code 77 as defined for skip condition on automake.

files_load_bytes_from_buffer_or_file_or_stdin: fix

---

CHANGELOG.md
lib/tpm2_capability.c
lib/tpm2_capability.h
test/integration/tests/evictcontrol.sh
tools/tpm2_createek.c
tools/tpm2_evictcontrol.c

1. Fix the platform flushing issue
2. While fixing one, noticed that the output was wrong when using an ESYS_TR handle. So fix the output for that. This is only a partial fix and #1816 has been filed to deal with the rest of it.

tpm2_evictcontrol: fixes

---

lib/files.c
lib/files.h
lib/tpm2_policy.c
lib/tpm2_policy.h
lib/tpm2_util.c
lib/tpm2_util.h
man/tpm2_certifycreation.1.md
man/tpm2_checkquote.1.md
man/tpm2_create.1.md
man/tpm2_createprimary.1.md
man/tpm2_gettime.1.md
man/tpm2_nvcertify.1.md
man/tpm2_nvextend.1.md
man/tpm2_policyauthorize.1.md
man/tpm2_policysecret.1.md
man/tpm2_policysigned.1.md
man/tpm2_policyticket.1.md
man/tpm2_quote.1.md
tools/misc/tpm2_checkquote.c
tools/tpm2_certifycreation.c
tools/tpm2_create.c
tools/tpm2_createprimary.c
tools/tpm2_gettime.c
tools/tpm2_nvcertify.c
tools/tpm2_policysecret.c
tools/tpm2_policysigned.c
tools/tpm2_policyticket.c
tools/tpm2_quote.c

- Unify qualifying data like options so the data argument can be a hex string or binary file.
- Fix the tpm2_nvextend manpage.
Fixes: #1631 
Fixes: #1820

qualifying data as hex string or binary file and manpage fix

---

man/tpm2_getcap.1.md
tools/tpm2_getcap.c

in tpm2_getcap.c:
- Remove obsolete case using -c parameter.
- Delete reference of -c parameter in an error message.
- Delete reference of -c parameter in a code comment.
and update the list of capability groups in the tpm2_getcap man page to match the list from `tpm2_getcap -l`
Fixes #1785

tpm2_getcap: delete unused references of -c parameter

---

CHANGELOG.md

* tpm2\_certifycreation: New tool enabling command TPM2\_CertifyCreation.
* tpm2\_checkquote:
- Fix YAML output bug.
- \-g option for specifying hash algorithm is optional and defaults to
sha256.
* tpm2_\changeeps: A new tool for changing the Endorsement hierarchy primary seed.
* tpm2_\changepps: A new tool for changing the Platform hierarchy primary seed.
* tpm2\_clockrateadjust: Add a new tool for modifying the period on the TPM.
* tpm2\_create: Add tool options for specifying output data for use in
certification
- \--creation-data to save the creation data
- \--creation-ticket or -t to save the creation ticket
- \--creation-hash or -d to save the creation hash
- \--template-data for saving the template data of the key
- \--outside-info or -q for specifying unique data to include in …

CHANGELOG.md: Update to version 4.1-rc0

---

tools/tpm2_getcap.c

'>>' has a higher precedence than '&' which results in the value of cHandles
being computed as tpma_cc & 0xE. This just adds some parentheses to correct
the operator order so that cHandles is calculated and displayed correctly.

Fix getcap

---

lib/pcr.c
test/unit/test_pcr.c

Backport from master to fix buffer length issue to support all defined hash algorithm. #1836

backport: Fix issue #1836

---

CHANGELOG.md

* New tools added to support commands:
TPM2_CertifyCreation, TPM2_ChangeEPS, TPM2_ChangePPS, TPM2_ClockRateAdjust,
TPM2_GetTime, TPM2_NV_Certify, TPM2_NV_Extend, TPM2_NV_Setbits,
TPM2_NV_UndefineSpaceSpecial, TPM2_NV_Writelock, TPM2_PolicyAuthorizeNV,
TPM2_PolicyAuthValue, TPM2_PolicyCounterTimer, TPM2_PolicyNameHash,
TPM2_PolicyNV, TPM2_NV_Written, TPM2_PolicySigned, TPM2_PolicyTemplate,
TPM2_PolicyTicket, TPM2_ReadClock, TPM2_ClockSet, TPM2_SetPrimaryPolicy,
TPM2_Shutdown.
* Bug fixes and additional options to existing tools.
1. tpm2_checkquote: Fix YAML bug
2. tpm2_policysecret: Add options to specify expiration, ticket, timeout,
qualification data.
3. tpm2_create/ tpm2_createprimary: Add options to specify creation-data,
creation-ticket, creation-hash, outside-info, pcr-list
4. …

CHANGELOG.md: Update to version 4.1-rc1

---

CHANGELOG.md

* New tools added to support commands:
TPM2_CertifyCreation, TPM2_ChangeEPS, TPM2_ChangePPS, TPM2_ClockRateAdjust,
TPM2_GetTime, TPM2_NV_Certify, TPM2_NV_Extend, TPM2_NV_Setbits,
TPM2_NV_UndefineSpaceSpecial, TPM2_NV_Writelock, TPM2_PolicyAuthorizeNV,
TPM2_PolicyAuthValue, TPM2_PolicyCounterTimer, TPM2_PolicyNameHash,
TPM2_PolicyNV, TPM2_NV_Written, TPM2_PolicySigned, TPM2_PolicyTemplate,
TPM2_PolicyTicket, TPM2_ReadClock, TPM2_ClockSet, TPM2_SetPrimaryPolicy,
TPM2_Shutdown.
* travis: bump abrmd version 2.3.0
* Bug fixes and additional options to existing tools.
1. tpm2_checkquote: Fix YAML bug
2. tpm2_policysecret: Add options to specify expiration, ticket, timeout,
qualification data.
3. tpm2_create/ tpm2_createprimary: Add options to specify creation-data,
creation-ticket, …

CHANGELOG.md: Update to version 4.1

---

CHANGELOG.md
test/integration/tests/import.sh
tools/tpm2_import.c

When importing a raw key, specifying policy via -L would not
work. Correct this and allow -L to be used for raw keys.

tpm2_import: support setting policy on imported key

---

lib/pcr.c
lib/tpm2_openssl.c
lib/tpm2_policy.c
tools/tpm2_pcrread.c

Fix several small alerts found by LGTM:
- [`TPML_PCR_SELECTION.count`](https://github.com/tpm2-software/tpm2-tss/blob/1c99117f4d102fd465655ed86aca58909a13c10d/include/tss2/tss2_tpm2_types.h#L1046) is `UINT32`, so the counter variable needs to be `UINT32` as well.
- [`TPMS_PCR_SELECTION.sizeofSelect`](https://github.com/tpm2-software/tpm2-tss/blob/1c99117f4d102fd465655ed86aca58909a13c10d/include/tss2/tss2_tpm2_types.h#L951) is `UINT8`, but after multiplication with 8 it might only fit into an `int` (which is guaranteed to be at least 16 bits long) due to integer promotion.

Match types of counter variable and comparison bound

---

Makefile.am

tpm2_shutdown.1 manpage is missing. We need to add it in Makefile.am
for generation.
Signed-off-by: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>

man: add tpm2_shutdown.1

---

test/integration/tests/certify.sh
tools/tpm2_certify.c

signing key is loaded as certified key and vice versa
Fixes https://github.com/tpm2-software/tpm2-tools/issues/1871

tpm2_certify: fix key arguments

---

tools/tpm2_verifysignature.c

Fixes #1869
If you don't give the correct combination of "-d -m -g" to
verifysignature, then it gives an error and explains how to
use "--digest". The manual says that it's "-d", however the
error from the tools says that it's "-D".

tpm2_verifysignature: Fixed a typo

---

man/tpm2_changeeps.1.md

Fixes #1887
Man page had a type where PPS was mentioned instead of EPS.

tpm2_changeeps.1.md: Fixed typos

---

tools/tpm2_nvdefine.c

Fixes #1861
NV define failure error message had the wording to suggest NV index
was successfully defined.

tpm2_nvdefine.c: Fixed error reporting message

---

man/tpm2_certify.1.md

tpm2_certify.1.md: Add a working example to show how to certify key objects

---

CHANGELOG.md
lib/tpm2_policy.c
man/tpm2_policyor.1.md
test/integration/tests/abrmd_policyor.sh
tools/tpm2_policyor.c

Fixes #1893 
Fixes #1894 
Fixes #1896 
Fixes #1895

tpm2_policyor: Bug Fixes

---

test/integration/tests/getekcertificate.sh
tools/tpm2_getekcertificate.c

Currently only Intel (R) PTT certificates are hosted online.
A default web address pointing to the endorsement key certificate
hosting will help reduce user input.

tpm2_getekcertificate: add default web address

---

lib/tpm2_alg_util.c

tpm2_alg_util.c: fix a bug where the string rsa3072 wasnt being parsed

---

tools/misc/tpm2_eventlog.c

In `tpm2_eventlog`, a `size_t *` pointer is passed to a function which expects an `unsigned int long *`. That caused build failure on e.g. Raspberry Pi.

tools: fix incompatible pointers in tpm2_eventlog

---

lib/tpm2_eventlog_yaml.c
lib/tpm2_tool_output.c
lib/tpm2_tool_output.h
test/unit/test_tpm2_eventlog_yaml.c
tools/tpm2_tool.c
tools/tpm2_tool.h

Defining the 'output_enabled' global variable in the tpm2_tool module
makes it unusable from any executable that defines it's own 'main'
function (mostly affecting unit tests). e2b7f1b1752f works around this
by defining the variable in the test. This works but requires all unit
tests using `tpm2_tool_output` to do the same. This may be a source of
mysteries for those working on unit tests in the future.
This commit removes this burden from unit test writers by moving
`output_enabled` out of the tpm2_tool module and into one of it's
own: tpm2_tool_output. This causes the symbol to be included in the
local utility library where any executable may link against it. This
commit also adds a new macro 'tpm2_tool_output_disable` to allow the
tpm2_tool module to disable output without having to …

tpm2_tool_output: Move tool output variable and macros to new module.

---

tools/tpm2_policycountertimer.c

tpm2_policycountertimer: Fix an issue where operandB array was reversed

---

lib/tpm2_eventlog_yaml.c

lib/tpm2_eventlog.c: Fix for illegal pointer cast

---

test/integration/helpers.sh

For FAPI there will be a PR which will change the provisioning behaviour. An error will be returned if no certificate for the generated EK exists.
To enable FAPI integration tests with the simulator and also with physical
TPMS the cert less option was added to the helper. So no error is signalled
in simulator tests without certificates and the certificate verification is
skipped in tests with physical TPMs.

 test/integration/helpers.sh: Add cert less option to FAPI test config.

---

lib/tpm2_util.c

The routine converting TPM2B_PUBLIC to YAML was just outputting the
exponent as is, and in hex. The TPM uses 0 to indicate the default
exponent which 65537. The YAML would just output 0x0. So add a condition
where if 0, output 65537, and update the output to unsigned singe that
is commonly how exponents are reported.
Before:
type:
value: rsa
raw: 0x1
exponent: 0x0
bits: 2048
After:
type:
value: rsa
raw: 0x1
exponent: 65537
bits: 2048
Fixes: #1919

tpm2_util: fix public to yaml exponent handling

---

lib/tpm2_nv_util.h

Fixes #1958
tpm2_nvread and tpm2_nvwrite tools both rely on lib/tpm2_nv_util to
determine the adequate transmission size for a buffer
(TPM2_PT_NV_BUFFER_MAX).
The function used, tpm2_util_nv_max_buffer_size(), will silently fail
on modules conforming to the TPM2 Library Specification rev0.98 and
older. TPM2_PT_NV_BUFFER_MAX has been around since revision 0.99 [1],
and function TPM2_GetCapability is not specified to fail if the
requested property does not exist.

lib/tpm2_nv_util.h: Set default NV buffer size if cap is missing info

---

Makefile.am
configure.ac
test/integration/helpers.sh
test/integration/tests/abrmd_nvundefinespecial.sh
test/integration/tests/abrmd_policyauthvalue.sh
test/integration/tests/abrmd_policypassword.sh
test/integration/tests/changeeps.sh
test/integration/tests/changepps.sh
test/integration/tests/clockrateadjust.sh
test/integration/tests/create.sh
test/integration/tests/encryptdecrypt.sh
test/integration/tests/hierarchycontrol.sh
test/integration/tests/import.sh
test/integration/tests/loadexternal.sh
test/integration/tests/nv.sh
test/integration/tests/nvinc.sh
test/integration/tests/setclock.sh

Some of the commands fail since certain requirements are not met, e.g. ECC curves or algorithms are not supported etc. In this case the tests in question should skip such algorithms or have the test return `77` (SKIP) altogether.
To make the tests more portable, I introduce following changes:
- Introduce  new tool `tpm2_getname` which returns the name of a TPM object. This tool is used in tests later. Any feedback is welcome!
- Use `tpm2_getname` in tests as an alternative to `tpm2_encryptdecrypt` if `tpm2_encryptdecrypt` is not supported
- Add `try` function to `helpers.sh` which is used to handle expected errors (e.g. algorithm not supported). In this case, sub-tests are skipped.
- Skip tests `toggle_options` if required files are not present (e.g. directory `man`)
- Replace …

Portable tests

---

test/integration/tests/abrmd_policycphash.sh

`tpm2_encryptdecrypt` expects some input to encrypt. The only reason the CI build works at the moment is because tests are run in parallel, which does special things to stdin. Running the single test however hangs indefinitely unless the user manually provides input on the terminal:
```
make check TESTS=test/integration/tests/abrmd_policycphash.sh
```

tests/abrmd_policycphash: provide plaintext for tpm2_encryptdecrypt

---

Makefile.am
lib/files.c
test/unit/test_tpm2_auth_util.c
tools/misc/tpm2_eventlog.c

When using tpm2_eventlog directly on the sysfs file `/sys/kernel/security/tpm0/binary_bios_measurements`, an empty buffer is allocated because its file size is reported as 0. As we cannot know the correct buffer size in advance, allocate a buffer for the maximum amount of data and determine the correct buffer size from a full file read.
Fixes: #1975

tools/misc/tpm2_eventlog: do not rely on reported file size

---

tools/tpm2_getcap.c

tpm2_getcap was missing raw on a property, and it should always be
specified.

tpm2_getcap: add raw to TPM2_PT_REVISION

---

lib/tpm2_convert.c
lib/tpm2_kdfe.c
lib/tpm2_openssl.c
lib/tpm2_openssl.h

ECC Functions with suffix GFp will become deprecated (DEPRECATED_1_2_0).

OpenSSL: Fix deprecated OpenSSL functions.

---

configure.ac
test/integration/fapi/fapi-encrypt-decrypt.sh
test/integration/fapi/fapi-key-change-auth.sh
tools/fapi/tss2_template.c

Enable support for Auth-Callbacks of tpm2-tss FAPI >= 3.0 while retaining the ability to talk to FAPI < 3.0 style auth callbacks.
This is needed for https://github.com/tpm2-software/tpm2-tss/pull/1719
This can be merged right away, since it also works with FAPI 2.4.x which current CI depends upon.

FAPI: Enable new style auth callback

---

man/tpm2_pcrread.1.md
tools/tpm2_pcrread.c

Previously tpm2_pcrread used to display PCR values with no padding
(aka `0x`). This change reverts back to the original non padded
format.
Signed-off-by: Luke Hinds <lhinds@redhat.com>

Remove PCR Padding

---

.cirrus.yml

Something wrong happened with the cached FreeBSD-12 image.
The install step fails with:
[7/134] Fetching git-2.26.2.txz: .......... done
pkg: cached package git-2.26.2: size mismatch, fetching from remote
[8/134] Fetching git-2.26.2.txz: .......... done
pkg: cached package git-2.26.2: size mismatch, cannot continue
Consider running 'pkg update -f'
Exit status: 3
Added the recommended 'pkg update -f' step.

cirrus: fix install step

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_loadexternal.c

Fix those cases of TPM2_RH_ to ESYS_TR_RH_ translations that were missed in 780800c0be69a49b9097f8eae653cdb0623d2100 as discovered in https://github.com/tpm2-software/tpm2-tools/pull/1994
I hope I did not miss any further cases, but at least tests are now successful.
This should also be backported to 4.1.x and 4.2.x as well.

Fix ESYS_TR hierarchy transition

---

man/tpm2_sign.1.md
tools/tpm2_sign.c

Ideally this should never have been in the sign tool but in hash tool instead, but this needs to go in for options portability.
~~- [ ] Add hierarchy support~~
Since an auth isnt required, let's stick with the owner hierarchy for the validation ticket and use it internally in the tool.

tpm2_sign: Fix for signature failures when key is restricted type

---

lib/tpm2_eventlog.c

Fixes:
CC lib/lib_libcommon_a-tpm2_eventlog.o
lib/tpm2_eventlog.c: In function ‘foreach_digest2’:
lib/tpm2_eventlog.c:40:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
for (size_t i = 0; i < count; ++i) {
^
lib/tpm2_eventlog.c:40:5: note: use option -std=c99 or -std=gnu99 to compile your code
lib/tpm2_eventlog.c: In function ‘specid_event’:
lib/tpm2_eventlog.c:243:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
for (size_t i = 0; i < sizeof(event->digest); ++i) {
^
make: *** [lib/lib_libcommon_a-tpm2_eventlog.o] Error 1
This fixes that bug without explicitly having to set the build -std
options, which would have to be gnu99. We may wish to specify that in
the future.
Fixes: #2011

(4.2.X) lib/tpm2_eventlog: drop for loop declerations

---

lib/tpm2_eventlog.c

Fixes:
CC lib/lib_libcommon_a-tpm2_eventlog.o
lib/tpm2_eventlog.c: In function ‘foreach_digest2’:
lib/tpm2_eventlog.c:40:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
for (size_t i = 0; i < count; ++i) {
^
lib/tpm2_eventlog.c:40:5: note: use option -std=c99 or -std=gnu99 to compile your code
lib/tpm2_eventlog.c: In function ‘specid_event’:
lib/tpm2_eventlog.c:243:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
for (size_t i = 0; i < sizeof(event->digest); ++i) {
^
make: *** [lib/lib_libcommon_a-tpm2_eventlog.o] Error 1
This fixes that bug without explicitly having to set the build -std
options, which would have to be gnu99. We may wish to specify that in
the future.
Fixes: #2011

(master) lib/tpm2_eventlog: drop for loop declerations

---

.cirrus.yml

After #1999 - Fix ESYS_TR hierarchy transition we can
switch cirrus to TSS master.

cirrus: switch TSS to master branch

---

lib/tpm2_options.c
tools/fapi/tss2_template.c

scan-build in llvm-10 complains about:
../tools/fapi/tss2_template.c:57:14: warning: Although the
value stored to 'pid' is used in the enclosing expression,
the value is never actually read from 'pid'
if ((pid = waitpid(pid, &status, 0)) == -1) {
^     ~~~~~~~~~~~~~~~~~~~~~~~~
../lib/tpm2_options.c:141:14: warning: Although the value
stored to 'pid' is used in the enclosing expression, the
value is never actually read from 'pid'
if ((pid = waitpid(pid, &status, 0)) == -1) {
^     ~~~~~~~~~~~~~~~~~~~~~~~~

scan-build: fix value is never read from variable issue

---

.cirrus.yml

After the PR has been merged to abrmd it doesn't need to
be patched anymore.
Fixes: #2001
Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>

cirrus: drop abrmd on the flight patching

---

tools/tpm2_create.c

HARD NACK. This was there so that if someone creates an object with a policy and no password, they wouldn't implicitly be getting a null password allowed on their object. What you need to do is check if they specified -a. If they specified -a, then we don't turn it down.
I think you want:
```diff
diff --git a/tools/tpm2_create.c b/tools/tpm2_create.c
index 17709a4aba92..36c2fbc2a8ac 100644
--- a/tools/tpm2_create.c
+++ b/tools/tpm2_create.c
@@ -405,7 +405,7 @@ tool_rc tpm2_tool_onrun(ESYS_CONTEXT *ectx, tpm2_option_flags flags) {
return tool_rc_general_error;
}
-    if (ctx.flags.L && !ctx.object.auth_str) {
+    if (!ctx.flags.b && ctx.flags.L && !ctx.object.auth_str) {
ctx.object.public.publicArea.objectAttributes &=
~TPMA_OBJECT_USERWITHAUTH;
}
```
note that flags.b is actually the -a …

Revert "tpm2_create.c: Fix an issue where userwithauth attr cleared if policy specified"

---

lib/tpm2_eventlog.c
lib/tpm2_eventlog_yaml.c
test/unit/test_tpm2_eventlog.c

According the TCG 2.3.4.1, `EV_POST_CODE` are byte strings, not firmware blobs. This patch adds string display to the event handling code and renames the firmware blob test function.

Parse EV_POST_CODE as strings

---

tools/fapi/tss2_template.c

This PR addresses the comments in #2035/#2036
- Deallocate the version pointer before reseating again. 
- Improve code by letting sscanf allocate memory itself.

tss_*: Fix orphaned pointer and let sscanf allocate memory

---

doc/CHANGELOG.md
lib/files.c
lib/files.h
lib/tpm2_openssl.c
lib/tpm2_openssl.h
lib/tpm2_util.c
lib/tpm2_util.h
man/tpm2_createak.1.md
man/tpm2_print.1.md
man/tpm2_readpublic.1.md
test/integration/tests/createak.sh
test/integration/tests/print.sh
tools/misc/tpm2_print.c
tools/tpm2_createak.c
tools/tpm2_readpublic.c

Add qualified name output to:
- tpm2_readublic: missing a file output
- tpm2_createak: missing qualified name
Add support for tpm2_print to print TPM2B_PUBLIC and TPMT_PUBLIC data structures.

Qualified name and tpm2_print additions

---

Makefile.am
man/common/protection-details.md
man/tpm2_changeauth.1.md
man/tpm2_create.1.md
man/tpm2_createak.1.md
man/tpm2_duplicate.1.md
man/tpm2_import.1.md
man/tpm2_loadexternal.1.md

Detail how **-r** options are protected by the TPM at a high level and
link to the spec detailing the nitty gritty parts for those so inclined.
Fixes: #2056

man: update private file output protection details

---

dist/bash-completion/tpm2-tools/tss2_setappdata
doc/CHANGELOG.md
man/tss2_setappdata.1.md
test/integration/fapi/fapi-set-get-app-data.sh
tools/fapi/tss2_setappdata.c

Another fix for the tss2 tools to be back ported to 4.2.X branch: 
- tss2_setappdata now reads from file or stdin allowing to store also binary data

TSS2 Tools Backport Fixes (4.2.X) Part2

---

dist/bash-completion/tpm2-tools/tss2_setappdata
doc/CHANGELOG.md
man/tss2_setappdata.1.md
test/integration/fapi/fapi-set-get-app-data.sh
tools/fapi/tss2_setappdata.c

Another fix for the tss2 tools which also should be back ported to 4.2.X: 
- tss2_setappdata now reads from file or stdin allowing to store also binary data

TSS2 Tools Backport Fixes Part2

---

man/tpm2_create.1.md

The seal data was incorrectly stated at 256 bytes, when it is limited by
the spec to 128 bytes.
See section 12.7 of:
- https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part3_Commands_pub.pdf
Fixes: #2083

man/tpm2_create: fix seal data size to 128 from 256

---

lib/tpm2_eventlog.c
lib/tpm2_eventlog.h
lib/tpm2_eventlog_yaml.c
lib/tpm2_eventlog_yaml.h
lib/tpm2_openssl.c
lib/tpm2_openssl.h
lib/tpm2_util.h
test/integration/tests/eventlog.sh
test/unit/test_tpm2_eventlog.c
tools/misc/tpm2_checkquote.c

This patch computes the PCR values for the sha1 and sha256 hashes based on the events in the log and outputs an additional yaml section with the predicted PCRs to make it easy to compare to the attested quote.

tpm2_eventlog: compute PCR values based on the events

---

Makefile.am

Using absolute symlinks does not work when using DESTDIR, e.g. for distribution packaging, because the files will not be found any more once the installation directory has been moved to its final location. Using relative symlinks works fine since all files are in the same directory and seems to be the norm for symlinks in `@bindir@` anyway.
Fixes: 61d4ae3e7b4b5c1d3cd9a2e66e6ca589929e2d4e
Fixes: #2102

Makefile.am: use relative instead of absolute symlinks for tpm2_*

---

lib/tpm2_options.c
tools/fapi/tss2_authorizepolicy.c
tools/fapi/tss2_createseal.c
tools/fapi/tss2_decrypt.c
tools/fapi/tss2_nvextend.c
tools/fapi/tss2_nvwrite.c
tools/fapi/tss2_pcrextend.c
tools/fapi/tss2_verifyquote.c
tools/fapi/tss2_verifysignature.c

This PR fixes the following issues
- tss2_createseal: Make parameters data or size mandatory
- tpm2_print_usage: Do not try to print a short option if there is none
- tss2_*: Fix some memory leaks and use correct free function

tss2 tools: Some fixes

---

tools/tpm2_send.c
tools/tpm2_tool.c

Rather than sending a single command, send N commands from the file and
recieve N responses. Any errors (EINTR) or EOF will cause an exit
condition.

tpm2_send: send more than one tpm command

---

test/integration/tests/send-tcti-cmd.sh

Add test that runs a tpm2-tools command, tpm2 getrandom, with the
command tcti and the tpm2 send command. Skip if the tss2-tcti-cmd
package is not installed. This will keep this test backwards compat with
older versions of the TSS.

test: add tcti-cmd test

---

Makefile.am

The tss2 tools were getting symlinked to the tpm2 tools execitable,
correct this by linking tss2_<tool> to the tss2 executable.

tss2: fix symlink to wrong toolbox

---

man/tpm2_duplicate.1.md

Fixes #2135
Add end-to-end example that transfers an RSA key from TPM-A to TPM-B
Signed-off-by: salmaan rashid <salrashid123@gmail.com>

Add duplicate and transfer example man page

---

doc/CHANGELOG.md
tools/fapi/tss2_decrypt.c
tools/fapi/tss2_encrypt.c
tools/fapi/tss2_exportpolicy.c
tools/fapi/tss2_getinfo.c
tools/fapi/tss2_getrandom.c
tools/fapi/tss2_gettpmblobs.c
tools/fapi/tss2_nvread.c
tools/fapi/tss2_pcrread.c
tools/fapi/tss2_quote.c
tools/fapi/tss2_template.c

This commit fixes a memory leak in cases when an returned empty non-char
output value was passed to file output.

tss2_*: Fix a memory leak caused by empty output (for master)

---

doc/CHANGELOG.md
tools/fapi/tss2_decrypt.c
tools/fapi/tss2_encrypt.c
tools/fapi/tss2_exportpolicy.c
tools/fapi/tss2_getinfo.c
tools/fapi/tss2_gettpmblobs.c
tools/fapi/tss2_nvread.c
tools/fapi/tss2_pcrread.c
tools/fapi/tss2_quote.c
tools/fapi/tss2_template.c

This commit fixes a memory leak in cases when an returned empty non-char
output value was passed to file output.

tss2_*: Fix a memory leak caused by empty output (for 4.2.x)

---

Makefile.am
configure.ac
man/tpm2_certifyX509certutil.1.md
test/integration/tests/X509certutil.sh
tools/misc/tpm2_certifyX509certutil.c

For TPM2_CertifyX509 command one of the params is partial cert,
which contains only a few fields of the X509 certificate.
This adds a new misc tool that can be used to generate
this input parameter.

tools: add tpm2_certifyX509certutil tool

---

tools/fapi/tss2_template.c

The umask affects files and directories alike, see [man umask(2)](https://man7.org/linux/man-pages/man2/umask.2.html). Creating FAPI objects entails creating new directories as well, which will not be searchable, leading to failures like
```
ERROR:fapi:src/tss2-fapi/ifapi_helpers.c:986:create_dirs() mkdir not possible: -1 /tmp/tpm2_test_umRcf1/tss2_fapi.6tZ4O8/keystore_system/P_RSA/HE/
ERROR:fapi:src/tss2-fapi/ifapi_helpers.c:1013:ifapi_create_dirs() ErrorCode (0x0006000b) Create directories for /P_RSA/HE/EK
ERROR:fapi:src/tss2-fapi/ifapi_keystore.c:710:ifapi_keystore_store_async() ErrorCode (0x0006000b) Directory /P_RSA/HE/EK could not be created.
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:835:Fapi_Provision_Finish() ErrorCode (0x0006000b) Could not open: HE/EK …
```

tss2-tools: retain executable permission for user and group in umask

---

doc/CHANGELOG.md
man/tpm2_makecredential.1.md
test/integration/tests/abrmd_policycphash.sh
test/integration/tests/activecredential.sh
test/integration/tests/attestation.sh
test/integration/tests/makecredential.sh
tools/tpm2_makecredential.c

Fixes #2054
Fixes #2055
Fixes #2051
~- [ ] Make name optional if public key for encryption is provided in tss format~ This is invalid since we need the name of the AIK which is not the public encryption-key. The public encryption-key is the EK.
~- [ ] Add **-c**, **--context** option to use key handles loaded by loadexternal~ This is invalid since we can now load public encryption key in directly in both PEM and TSS format.

Add changes to make credential tool to simplify/ reduce options.

---

doc/CHANGELOG.md
man/tpm2_getekcertificate.1.md
test/integration/tests/getekcertificate.sh
tools/tpm2_getekcertificate.c

tpm2_getekcertificate: Add capability to scan NV indices for EK cert

---

tools/misc/tpm2_certifyX509certutil.c

On arm the compilation fails with `tools/misc/tpm2_certifyX509certutil.c:110:17: error: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘ssize_t {aka int}’`.
This is due to a wrong format specifier.

Use correct formatspecifier for size_t

---

tools/fapi/tss2_pcrextend.c

The check if a PCR is set requires that the PCR value be greater than 0.
However, PCR index 0 is valid, so use another variable to track if the
PCR index is specified.
Fixes Error:
tss2_pcrextend --pcr=0
No pcr provided, use --pcr
Usage: tss2_pcrextend [<options>]
Where <options> are:
[ -x | --pcr=<value>] [ -i | --data=<value>] [ -l | --logData=<value>] [ -h | --help=<value>]
[ -v | --version]
Fixes: #2167

tss2_pcrextend: fix extending PCR 0

---

tools/fapi/tss2_pcrread.c

The check if a PCR is set requires that the PCR value be greater than 0.
However, PCR index 0 is valid, so use another variable to track if the
PCR index is specified.
Similar to #2168
Fixes Error:
$ tss2_pcrread -x 0 -o -
No PCR index provided, use --pcrIndex
Usage: tss2_pcrread [<options>]
Fixes: #2167

tss2_pcrread: fix reading PCR 0

---

tools/tpm2_verifysignature.c

--format was changed to --scheme in e275ba54e585c. However, the option
for --format was set to '0' (ASCII 0)  in the selector char. However,
the case statement was set to 0, thus --format was being silently
ignored. Fix this by setting the getopt selector charactar to 0.
Fixes: #2169

tpm2_verifysignature: fix --format to --scheme fallback

---

.cirrus.yml

The build time outs with the fapi tests enabled.

cirrus: disable fapi tests

---

doc/CHANGELOG.md
lib/tpm2_alg_util.c
man/tpm2_sign.1.md
test/integration/tests/sign.sh
test/unit/test_tpm2_alg_util.c
tools/tpm2_sign.c

Fixes #2071
~~- [ ] Add signature verification~~

Fixes for ECC ecdaa signing scheme

---

Makefile.am
lib/tpm2_options.c
man/tpm2.1.md

lib/tpm2_options.c: Fix MAN pages were not displayed for tpm2<spc>toolname

---

tools/fapi/tss2_template.c

If no number was received, but EOF the error TSS2_FAPI_RC_GENERAL_FAILURE will be returned.

fapi: return error if no number for policy branch selection was entered.

---

configure.ac

The `AC_CHECK_PROG` invocations now use "no" instead of "missing" to signal that a required program is not available. Since the `AS_IF` statements were not adapted to match, missing dependencies did not trigger a warning message or error at all.

configure: properly fail if required programs are missing

---

lib/tpm2_eventlog_yaml.c

The output buffer `dest` should usually have an odd length (two characters per byte in hexadecimal representation, plus one for the null terminator). If the buffer had an even `dest_size` <= 2*`size`, the null terminator was written out of bounds to `dest[dest_size]`. Ensure that the null terminator is stored within the array bounds by omitting the last byte from the hex representation if necessary.
This issue was triggered by the recent commit 46942ef1731f36ca862067130c211854368aef67, leading to the compiler warning/error
```
In function ‘bytes_to_str’,
inlined from ‘yaml_sha1_log_eventhdr_callback’ at lib/tpm2_eventlog_yaml.c:344:5:
lib/tpm2_eventlog_yaml.c:90:13: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
90 |     dest[j] = '\0';
|     ~~~~~~~~^~~~~~ …
```

lib/tpm2_eventlog_yaml.c: fix buffer overflow in bytes_to_str()

---

tools/tpm2_tool.c

Fixes #2222
The version string wasn't displayed despite supplying the -v or
--version option. Instead the option was identified as an unknown
tool.

tpm2: Fix for version string not being displayed

---

lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_policysigned.1.md
test/integration/tests/abrmd_policysigned.sh
tools/tpm2_policysigned.c

The signature used for PolicySigned includes `nonceTPM`, `expiration`, `cpHash` and `policyRef`. Add support for `cpHash` by adding the parameter `--cpHash` to `tpm2_policysigned`.

tpm2_policysigned: add cpHashA support

---

lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_policysigned.1.md
test/integration/tests/abrmd_policysigned.sh
tools/tpm2_policysigned.c

This reverts commit 5ad61880a65bd208976e6f01ad5ece8def002ace.
Reason: The --cphash option in all other tools is an output to save
the resulting cphash of a command without executing it.
Solution: Rename the --cphash option in context of how it is used
in this change.

Revert "tpm2_policysigned: add cpHashA support"

---

lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
tools/tpm2_create.c
tools/tpm2_createprimary.c

Handle the loading of the unique data upfront in the create object
tool. This will make it flexible for at least two reasons, namely:
1. Option to input data from stdin.
2. Anticipate the key type and process stdin data so as to remove
end user overhead to format data as TPMU_PUBLIC_ID.
Look at issue #2091 for more details.

Refactor handling of unique data in object creation commands.

---

tools/tpm2_nvreadpublic.c

Fix the shifting of TPM2_HT_NV_INDEX to the most significant octet (MSO).
tpm2_util_hton_32(TPM2_HT_NV_INDEX) would only shift the TPM2_HT_NV_INDEX
on little endian systems and do nothing on big endian ones, so we use an
explicit shift toaccomplish this also on big endian systems.
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

Fix tpm2_nvreadpublic for big endian systems

---

lib/pcr.c
lib/pcr.h
lib/tpm2_openssl.c
lib/tpm2_openssl.h
lib/tpm2_systemdeps.h
tools/misc/tpm2_checkquote.c
tools/tpm2_quote.c

Various PCR related structures read by tpm2_checkquote are written
in little endian format, which needs to be taken into account when
run on a big endian system. Although little endian is unusual for
TPM, it is better to leave these data structures in little endian
format to not disrupt existing systems.
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

Fix tpm2_checkquote when run on a big endian system

---

tools/misc/tpm2_checkquote.c

Fixes this compilation error:
```In file included from tools/misc/tpm2_checkquote.c:12:0:
tools/misc/tpm2_checkquote.c: In function ‘parse_selection_data_from_file’:
tools/misc/tpm2_checkquote.c:270:17: error: format ‘%zu’ expects
argument of type ‘size_t’, but argument 6 has type ‘__uint64_t {aka long
long unsigned int}’ [-Werror=format=]
LOG_ERR("Malformed PCR file, pcr count cannot be greater than
%zu, got: %zu",
```
`le64toh `always returns an `uint64_t`, thus `%PRIu64`

tpm2-checkqoute: fix wrong format specifier

---

lib/tpm2_eventlog_yaml.c

In the eventlog output, an UEFI event is currently showing as a list of events, e.g.,
```
Event:
- VariableName: cbb219d7-3a3d-9645-a3bc-dad00e67656f
UnicodeNameLength: 3
VariableDataLength: 3724
UnicodeName: dbx
VariableData: ""
```
Instead, it should be
```
Event:
VariableName: cbb219d7-3a3d-9645-a3bc-dad00e67656f
UnicodeNameLength: 3
VariableDataLength: 3724
UnicodeName: dbx
VariableData: "
```
as there is only a single event associated with each event entry. This fixes this issue, and also some indentation inconsistencies.

some yaml lists should be a dictionary instead

---

lib/files.c
lib/tpm2_eventlog.c
tools/misc/tpm2_certifyX509certutil.c
tools/misc/tpm2_eventlog.c

Because pcr_index is used for array indexing and bit-shift
operations it is 1 less than the max value.
Also moving the check to the top to fail fast/ early.

tpm2_eventlog.c: Fix for possible bad bit shift operation

---

tools/tpm2_getekcertificate.c

tpm2_getekcertificate: Fix tool failing to return error/non-zero for HTTP 404

---

test/integration/fapi/fapi-branch-select.sh
test/integration/fapi/fapi-provision.sh

This PR fixes two issues with the tss2 * tools:
1. tss2 *: Fix integration test fapi-branch-select: With the new TSS version also PolicyRef is included into the search for valid policies. Thus, the test is adapted to include PolicyRef in the authorization policy. This should fix the errors in PR tpm2-software#2264.
2. tss2 *: Fix parameter in provision test: The provision test still had an outdated parameter.

tss2 * tools: Fix for fapi-branch-select

---

test/integration/fapi/fapi-branch-select.sh
test/integration/fapi/fapi-provision.sh

This PR fixes two issues with the tss2 * tools:
1. tss2 *: Fix integration test fapi-branch-select: With the new TSS version also PolicyRef is included into the search for valid policies. Thus, the test is adapted to include PolicyRef in the authorization policy. This should fix the errors in PR tpm2-software#2264.
2. tss2 *: Fix parameter in provision test: The provision test still had an outdated parameter.

tss2 * tools: Fix for fapi-branch-select (Backport for 4.2.x)

---

test/integration/fapi/fapi-branch-select.sh
test/integration/fapi/fapi-provision.sh

This PR fixes two issues with the tss2 * tools:
1. tss2 *: Fix integration test fapi-branch-select: With the new TSS version also PolicyRef is included into the search for valid policies. Thus, the test is adapted to include PolicyRef in the authorization policy. This should fix the errors in PR tpm2-software#2264.
2. tss2 *: Fix parameter in provision test: The provision test still had an outdated parameter.

tss2 * tools: Fix for fapi-branch-select (Backport for 4.x)

---

Makefile.am
configure.ac
lib/tpm2_alg_util.c
test/integration/helpers.sh
test/integration/tests/testparms.sh

tpm2-tss supports the [swtpm](https://github.com/stefanberger/swtpm) TPM simulator since version 3.0.0. Two small changes (adding Triple DES to the algorithm list, choosing a different unsupported algorithm for negative testing in [`testparms.sh`](https://github.com/tpm2-software/tpm2-tools/blob/26f60611a045320ceb2554b6929a54bb3e3de06b/test/integration/tests/testparms.sh#L66)) were necessary, other than that everything works out of the box after adapting [`test/integration/helpers.sh`](https://github.com/tpm2-software/tpm2-tools/compare/master...diabonas:add-swtpm?expand=1#diff-7e13f2fcb4dce9b9de0bb58c89995153).
Support for ibmswtpm (aka `tpm_server`) is kept for backwards compatibility, but swtpm is preferred if it is available. Since the Docker images come with swtpm preinstalled, this …

test: add support for swtpm simulator

---

lib/tpm2_options.c

On a musl based system argv[optind] && strcmp(...) where optind > argc might read random memory and segfault.

Don't assume end of argv is NULL

---

tools/misc/tpm2_checkquote.c

The build fails for example on the RaspberryPI.
tools/misc/tpm2_checkquote.c:271:17: error: format ‘%llu’ expects argument of type
‘long long unsigned int’, but argument 6 has type ‘size_t {aka unsigned int}’
When size_t is 32-bit and when le64toh() is just a fall-through with no
type change, we need an explicit cast to match the PRIu64 specifier.

Fix tpm2_checkquote build on 32b little-endian platforms

---

lib/tpm2_eventlog_yaml.c

Now that more types of events are parsed, it would be nice to be able to differentiate (by a human or by a script) eventlog entries that are parsed vs. unparsed. One possible way is to look at the the data type of what is after `Event: `. If it's a string, then it's unparsed. Otherwise, it's parsed.
Additionally, added yaml annotation to handle parsed strings that could consist multiple lines.

tpm2_eventlog differentiate parsed events vs. unparsed and better handle parsed strings that could consistent multiple lines

---

.ci/download-deps.sh
lib/tpm2_convert.c
lib/tpm2_convert.h
lib/tpm2_util.c
lib/tpm2_util.h
test/integration/fapi/fapi-policy_signed.sh
test/integration/fapi/fapi-policy_signed_delegation.sh
tools/fapi/tss2_template.c

The callback function Fapi_SetSignCB for the PolicySigned command
and the corresponding integration tests were implemented.

tss2 *: Implement callback function Fapi_SetSignCB

---

tools/fapi/tss2_template.c

The Fapi callback API changed for TSS versions >= 3.0.0. This
commit adds backward compatibility to the old callback API.

tss2 *: Enable backward compatibility to old Fapi callback API

---

lib/efi_event.h
lib/tpm2_eventlog_yaml.c

This PR parses EV_EFI_GPT_EVENT. In `test/integration/fixtures/event-bootorder.bin`, an example event is:
```
- EventNum: 24                                                                         
PCRIndex: 5                                                                          
EventType: EV_EFI_GPT_EVENT                                                          
DigestCount: 2                                                                       
Digests:                                                                             
- AlgorithmId: sha1                                                                
Digest: "d35cb7d68eaa9de91261f18f3077b7ba9dd32974"                               
- AlgorithmId: sha256                                                              
Digest: …
```

tpm2_eventlog: parse EV_EFI_GPT_EVENT

---

Makefile.am
man/tpm2_sessionconfig.1.md
test/integration/tests/sessionconfig.sh
tools/tpm2_sessionconfig.c

tools/tpm2_sessionconfig: Add tool to display and configure session
```bash
tpm2_createprimary -c prim.ctx -p "primepass"
tpm2_startauthsession -S session.ctx --policy-session -c prim.ctx
tpm2_sessionconfig session.ctx
session-version:        2
session-type:           1
session_hash_algorithm: 000b
context-version:        1
hierarchy:              null
handle:                 0x3000000
sequence:               55
iesys-reserved:         00000000
integrity-size:         64
integrity-buffer:       8CA5368AD816EF4E95D65B43D0CA0A426A7B9E6A6558DFB373B1A1C98460CBFA
C2BD8B0D770742ECC05B4955324C43E6DA5F31E52F9C37B5208ADF8E7AD4B28F
encrypted-session-data-size: 322
encrypted-session-data: B28F137B5A4040A225D69877DF70555143AA29FEF700E8B9E3A2AE57210352 …
```

getcap/ readpublic equivalent for displayin and configuring session info from a session context

---

man/tpm2_policycphash.1.md
test/integration/tests/abrmd_policycphash.sh
tools/tpm2_policycphash.c

Rename the `--cphash` parameter to `--cphash-input` for `tpm2_policycphash` to clarify that this is an input parameter as opposed to the `--cphash` output parameter for most other tools.

tpm2_policycphash: rename --cphash to --cphash-input

---

lib/efi_event.h
lib/tpm2_eventlog_yaml.c
lib/tpm2_eventlog_yaml.h

In the secureboot mode, the eventlog contains various keys (e.g., PK, KEK, db, and dbx) used to perform boot-time verification. For anyone doing attestation of the eventlog, it would be useful to verify that the keys are genuine. In the current state, the keys are part of a blob. This PR allows the keys (and other fields) to be parsed out separately, resulting in something like the following:
```
- EventNum: 4
PCRIndex: 7
EventType: EV_EFI_VARIABLE_DRIVER_CONFIG
DigestCount: 2
Digests:
Digest: "74695203091adbb40c8420f1b499a6ac1a723962"
Digest: "b161e0347f5f040997f97ff52642d43b3a87b986dae8d776d6af27e6468675e6"
EventSize: 1011
Event:
UnicodeNameLength: 2
VariableDataLength: 975
UnicodeName: PK …
```

tpm2_eventlog: Parse keys used for secure boot (i.e., PK, KEK, db, dbx)

---

doc/CHANGELOG.md
tools/fapi/tss2_quote.c

The tss2 quote now correctly supports to quote
against a list of passed PCR registers.

Fapi fix tss2 quote pcr selection (Backport for 4.2.x)

---

doc/CHANGELOG.md
tools/fapi/tss2_quote.c

The tss2 quote now correctly supports to quote
against a list of passed PCR registers.

Fapi fix tss2 quote pcr selection (Backport for 4.x)

---

test/integration/fapi/fapi-quote-verify.sh
tools/fapi/tss2_quote.c

The tss2 quote now correctly supports to quote
against a list of passed PCR registers.

tss2 *: Fix PCR selection for tss2 quote

---

lib/tpm2_eventlog.c
lib/tpm2_eventlog.h
lib/tpm2_eventlog_yaml.c
lib/tpm2_eventlog_yaml.h
test/unit/test_tpm2_eventlog.c
test/unit/test_tpm2_eventlog_yaml.c
tools/misc/tpm2_eventlog.c

`SecureBoot` is a variable that appears in every eventlog. This PR makes it more "obvious" what various numeric values mean. Instead of 
```
UnicodeName: SecureBoot
VariableData: "01"
```
it spells it out as
```
UnicodeName: SecureBoot
VariableData:
Enabled:'Yes'
```

tpm2_eventlog: parse secureboot variable

---

configure.ac
lib/tpm2_convert.c
lib/tpm2_openssl.c
lib/tpm2_openssl.h
tools/misc/tpm2_checkquote.c

Fixes builds on CentOS 7 which notably has:
1. An ancient version of GCC: 4.8.5
2. An older version of OSSL, 1.0.2k
Patches in the series:
- tools/tpm2_checkquote: fix missing initializer
- tpm2_convert: fix EVP_EncodeUpdate usage for OSSL < 1.1.0
- openssl: fix EVP_ENCODE_CTX_(new|free)
- configure: make build gnu99
- configure: make -Wbool-compare non fatal

Fix Build on CentOS 7

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvdefine.1.md
test/integration/tests/nv.sh
tools/tpm2_nvdefine.c

tpm2_nvdefine: Add support for specifying aux sessions for audit/enc

---

.cirrus.yml

CI is failing, try its suggestion and set environment variable:
IGNORE_OSVERSION=yes
Per the logs:
pkg update -f
Updating FreeBSD repository catalogue...
Fetching meta.txz: . done
Fetching packagesite.txz: .......... done
Processing entries:
Newer FreeBSD version for package webalizer:
To ignore this error set IGNORE_OSVERSION=yes
- package: 1202000
- running kernel: 1201000
Ignore the mismatch and continue? [Y/n]: pkg: repository FreeBSD contains packages for wrong OS version: FreeBSD:12:amd64
Processing entries... done
Unable to update repository FreeBSD
Error updating repositories!

cirrus ci: fix FreeBSD package mismatch

---

.ci/download-deps.sh

Theirs no need to build the doxygen docs, so avoid it and pick up some
CI time.

ci: disable doxygen for tpm2-tss

---

lib/tpm2_eventlog_yaml.c

This PR parses the event type EV_EFI_VARIABLE_AUTHORITY using the data structure previously defined. To avoid backward compatibility issue, it will only be parsed with `--eventlog-version=2` flag

tpm2_eventlog: parse EV_EFI_VARIABLE_AUTHORITY

---

lib/tpm2_eventlog_yaml.c

tpm2_eventlog: fix missing space for secureboot

---

lib/tpm2_eventlog_yaml.c

In the current tpm2_eventlog YAML output, there are 2 ways items are indented, e.g.,
```
SpecID:
- Signature: Spec ID Event03
platformClass: 0
specVersionMinor: 0
specVersionMajor: 2
specErrata: 0
uintnSize: 2
numberOfAlgorithms: 2
Algorithms:
- Algorithm[0]:
algorithmId: sha1
digestSize: 20
- Algorithm[1]:
algorithmId: sha256
digestSize: 32
vendorInfoSize: 0
```
OTOH, it can also be indented like the following:
```
Event:
UnicodeNameLength: 2
VariableDataLength: 975
UnicodeName: PK
VariableData:
- SignatureType: a159c0a5-e494-a74a-87b5-ab155c2bf072
SignatureListSize: 975
SignatureHeaderSize: 0
SignatureSize: 947
```
According to the YAML spec, they are both correct, but it would be good to stick with a single style. This PR standardizes …

tpm2_eventlog: Standardize yaml spacing (cosmetic)

---

lib/tpm2_eventlog_yaml.c

The BootOrder variable is currently shown in raw bytes, e.g.,
```
- EventNum: 12
PCRIndex: 1
EventType: EV_EFI_VARIABLE_BOOT
DigestCount: 2
Digests:
Digest: "ea3f530d2b261b5a945812c15858c09de04abe9c"
Digest: "263d99957c7b574c63a265b32da7fff8b8ad831828946bfbff650d7074dd9198"
EventSize: 56
Event:
UnicodeNameLength: 9
VariableDataLength: 6
UnicodeName: BootOrder
VariableData: "010000000200"
```
This PR parses it in a more human-readable format, i.e.,
```
VariableData:
- Boot0001
- Boot0000
- Boot0002
```
showing the boot ordering of all the boot devices configured in the system.
This will only parse when `--eventlog-version` is set to `2`. The file `test/integration/fixtures/event-bootorder.bin` is …

tpm2_eventlog: parse BootOrder variable

---

dist/bash-completion/tpm2-tools/tpm2_completion.bash
man/tpm2_nvdefine.1.md
tools/tpm2_nvdefine.c

This is especially useful in conjunction with endorsement authentication according to PolicyB as specified in ["TCG EK Credential Profile"](https://trustedcomputinggroup.org/wp-content/uploads/TCG_IWG_EKCredentialProfile_v2p3_r2_pub.pdf), specifically for defining Policy Index I-2 (SHA384).
Signed-off-by: Tobias Peter <tobias.peter@infineon.com>

tpm2_nvdefine: allow setting hash algorithm by command line parameter

---

man/tpm2_readclock.1.md

The description of the TPMS_TIME_INFO in the tpm2_readclock is a bit misleading.
The `time` value corresponds to the power on time,
the `clock` value corresponds to the power on time since last TPM2_Clear.
See https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part2_Structures_pub.pdf "Section 10.11.2 Clock"
Probably the short note about TPM2_Startup was mis-interpreted.

man: tpm2_readclock: dix description of TPMS_TIME_INFO structure

---

man/common/nv-attrs.md

The existing NV attrs man page doesn't reference the extend NT type, which is a valid one and works with current tools.
Add entry to the manual so that others can more easily use it.

Add missing extend NT type to NV attrs man page

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
lib/tpm2_util.c
lib/tpm2_util.h
man/tpm2_activatecredential.1.md
man/tpm2_certify.1.md
man/tpm2_certifycreation.1.md
man/tpm2_changeauth.1.md
man/tpm2_changeeps.1.md
man/tpm2_changepps.1.md
man/tpm2_create.1.md
test/integration/tests/abrmd_policycphash.sh
test/integration/tests/sessionaudit.sh
tools/tpm2_activatecredential.c
tools/tpm2_certify.c
tools/tpm2_certifycreation.c
tools/tpm2_changeauth.c
tools/tpm2_changeeps.c
tools/tpm2_changepps.c
tools/tpm2_create.c
tools/tpm2_getrandom.c
tools/tpm2_nvdefine.c
tools/tpm2_nvextend.c
tools/tpm2_unseal.c

Fixes #2372
Fixes #2373
Fixes #2374
Fixes #2371
Fixes #2370
Fixes #2369
Fixes #2366
Fixes #2365
Fixes #2364 
Fixes #2358
Fixes #2357
Fixes #2356 
Fixes #2350 
Fixes #2352 
Fixes #2351 
Fixes #2349
Fixes #2347
Fixes #2348 
Fixes #2340 
Fixes #2341
Fixes #2342
Fixes #2343
It should be noted that the auths aren't checked when calculating the cpHash,
instead the sessions are consumed to determine the cpHash algorithm.
1. If cphash_path is preceded with <halg>: use that as cphash-halg return
Otherwise
Consume session only if it is a policy-session or an hmac-session
1. If only hmac or policy session is specified, return that session's halg
2. If hmac-session with audit is specified, return that session's halg
3. If policy-session, then return policy-session's halg
Otherwise
return SHA256 …

CommandAudit and SessionAudit support

---

lib/efi_event.h
lib/tpm2_eventlog_yaml.c

Enabled only when `--eventlog-version=2` is set. This PR allows BOOT#### variables to be parsed, e.g.,
```
- EventNum: 15
PCRIndex: 1
EventType: EV_EFI_VARIABLE_BOOT
DigestCount: 2
Digests:
Digest: "df5d6605cb8f4366d745a8464cfb26c1efdc305c"
Digest: "4d387b02d63b2f4cd7f667feb0a387fe47a10a3e26bf3533ddd001c605f3dec5"
EventSize: 136
Event:
UnicodeNameLength: 8
VariableDataLength: 88
UnicodeName: Boot0002
VariableData:
Enabled: 'Yes'
FilePathListLength: 44
Description: EFI Internal Shell
DevicePath: "04071400c9bdb87cebf8344faaea3ee4af6516a10406140083a5047c3e9e1c4fad65e05268d0b4d17fff0400"
```

tpm2_eventlog: parse BOOT#### variables

---

Makefile.am
lib/tpm2_util.c
tools/tpm2_getekcertificate.c

This addresses some issues I encountered while trying to package the 5.0 release for openSUSE.

Fix compiler and packaging warnings

---

Makefile.am
configure.ac
lib/tpm2_eventlog_yaml.c

Device Path field in many event types is a complicated field to parse, fortunately, `libefivar` can be used to make sense out of it. E.g.,
```
Event:
ImageLocationInMemory: 0xbeeed018
ImageLengthInMemory: 205768
ImageLinkTimeAddress: 0x0
LengthOfDevicePath: 46
DevicePath: "02010c00d041030a000000000101060000030408180000000000005c010000000000ff7f0400000000007fff0400"
```
can be parsed as follows:
```
Event:
ImageLocationInMemory: 0xbeeed018
ImageLengthInMemory: 205768
ImageLinkTimeAddress: 0x0
LengthOfDevicePath: 46
DevicePath: "PciRoot(0x0)/Pci(0x3,0x0)/Offset(0x15c00,0x47fff)"
```
This is only parsed when `eventlog-version=2`. When `libefivar` is not installed, the device path field will be printed as raw bytes. The bootlog `test/integration/fixtures/event-bootorder.bin` was used for the …

tpm2_eventlog: pretty print devicepath

---

lib/tpm2_identity_util.c
lib/tpm2_identity_util.h
lib/tpm2_kdfe.c
lib/tpm2_kdfe.h
lib/tpm2_openssl.c
lib/tpm2_openssl.h
man/tpm2_duplicate.1.md
test/integration/tests/duplicate.sh
tools/tpm2_duplicate.c
tools/tpm2_import.c

Wrapping a key for a remote TPM2 right now requires loading the key into the local TPM. For some use cases it is not necessary to involve the local TPM, such as sending an openssl generated key to a remote machine.
`tpm2_duplicate` seems like the right place to put this functionality, although it shares a large amount of code with `tpm2_import`, and some with `tpm2_makecredential`.  If there is a better place to locate the code, please let me know.
Some todo's before it is ready for merging:

tpm2_duplicate: support duplicating external non-TPM keys

---

tools/misc/tpm2_eventlog.c

tpm2_eventlog: Flush the eventlog stream data pointed by the fileptr.

---

tools/tpm2_getekcertificate.c

tpm2_getekcertificate: sanitize the url path when concatenating

---

lib/tpm2_eventlog_yaml.c

DevicePath field can be included in multiple types of events, and at different indentation levels. Previous commit assumes it's always at the same indentation level, e.g.,
```
- EventNum: 15
PCRIndex: 1
EventType: EV_EFI_VARIABLE_BOOT
DigestCount: 2
Digests:
Digest: "df5d6605cb8f4366d745a8464cfb26c1efdc305c"
Digest: "4d387b02d63b2f4cd7f667feb0a387fe47a10a3e26bf3533ddd001c605f3dec5"
EventSize: 136
Event:
UnicodeNameLength: 8
VariableDataLength: 88
UnicodeName: Boot0002
VariableData:
Enabled: 'Yes'
FilePathListLength: 44
Description: "EFI Internal Shell"
DevicePath: "FvVol(7cb8bdc9-f8eb-4f34-aaea-3ee4af6516a1)/FvFile(7c04a583-9e3e-4f1c-ad65-e05268d0b4d1)"
```
The `DevicePath` field in the last line …

tpm2_eventlog: fix device path indentation issue

---

lib/pcr.c
man/tpm2_pcrallocate.1.md

For certain use cases (e.g. PCR allocation) an empty selection needs to be specifiable.
Since we have a keyword 'all' the opposite is 'none' is chosen for the empty selection.
Fixes: #2344

PCR: Allow empty PCR selection by specifying keyword none.

---

doc/CHANGELOG.md

5.1-rc0 2021-04-20
* Build
- Dependency-update: Minimum tpm2-tss version dependency bumped to 3.0.3
- Dependency-update: Minimum tpm2-abrmd version dependency bumped to 2.4.0
- tpm2_eventlog: Fix build errors on 64 bit arm systems.
- tpm2_checkquote: Fix build on 32b little-endian platforms.
- Fixes builds on CentOS 7 which notably has an ancient version of
GCC: 4.8.5 and an older version of OSSL, 1.0.2
- Configure handles searching for python executable more gracefully, thus
just having python3, will work.
- Moved to GitHub Actions for CI testing.
- Added fedora-32 to CI testing configurations and related fixes.
- FreeBSD testing is bumped up to version 12.2
- Fix compiler and packaging warnings for OpenSuse builds.
- configure: make build gnu99.
- configure: make -Wbool-compare non …

doc/CHANGELOG.md: Update tpm2-tools to version 5.1

---

doc/CHANGELOG.md

4.3.1-rc0 2021-05-03
tpm2_dictionarylockout: Fix issue where setting value reset others
tpm2_create.c: Fix an issue where userwithauth attr cleared if policy specified
tss2_quote: Tool now correctly supports to quote against a list of passed PCR registers
Fix fapi-branch-select integration test to correctly use the PolicyRef parameter (triggered by recent bug-fix in tpm2-tss)
Fix an outdated parameter in the fapi-provision integration test
tpm2_getekcertificate: Fix tool failing to return error/non-zero for HTTP 404

doc/CHANGELOG.md: Update information for 4.3.1-rc0

---

man/tpm2_create.1.md

Add details on that -c needs createloaded support in the TPM.

man: clarify tpm2_create createloaded

---

scripts/utils/icert_ondie_ca.sh

This follows the TCG EK Credentials profile 2.3 rev 2
Example usage:
tpm2_nvread 1c00100 > 1c00100.bin
icert_ondie_ca.sh 1c00100.bin

scripts/utils: Add a utility to read the cert chain of embedded CA

---

doc/CHANGELOG.md

* scripts/utils: Add a utility to read the cert chain of embedded CA
* .ci/download-deps.sh: Bump tpm2-tss version to 3.1.0
* build: only use -Werror for non-release builds

5.1-rc1 2021-05-19

---

tools/tpm2_import.c

The API returns tool_rc's not stdbool.

tpm2_import: fix return code

---

tools/tpm2_import.c

When you import from a TPM object, you're importing from a TPM2B_PRIVATE,
which is opaque to us. Thus we cannot modify it to change it. You can only
change the TPM object at creation time, when you have the clear text
TPM2B_SENSITIVE or through certain APIs like tpm2_changeauth.
However, when importing from an openssl key, we create the object from a
TPM2B_SENSITIVE and perform the parent key wrapping work of the TPM and
thus generate the TPM2B_PRIVATE. Thus we can modify it.
Thus complain when -p is set but the user is importing TPM objects.
Fixes: #2708

tpm2_import: do not allow -p with TPM objects

---

configure.ac
tools/tpm2_import.c

tpm2_import: fix fixed AES key CVE-2021-3565
tpm2_import used a fixed AES key for the inner wrapper, which means that
a MITM attack would be able to unwrap the imported key. Even the
use of an encrypted session will not prevent this. The TPM only
encrypts the first parameter which is the fixed symmetric key.
To fix this, ensure the key size is 16 bytes or bigger and use
OpenSSL to generate a secure random AES key.
Fixes: #2738

Fix import CVE-2021-3565

---

lib/tpm2.c
lib/tpm2_util.c

tpm2_util_calculate_phash_algorithm returns TPM2_ALG_ERROR when
trying to determine the session hash algorithm when a password
only session is the only available session object.

lib/tpm2_util.c: fix session halg returning TPM2_ALG_ERROR

---

man/tpm2_duplicate.1.md
test/integration/tests/duplicate.sh
tools/tpm2_duplicate.c

The duplicate key structures for OpenSSL keys can be protected by optional policy and authorization values.
Additionally there is no TCTI required for external key duplication, so the TPM2_OPTIONS_OPTIONAL_SAPI flag can
be passed to tpm2_options_new().
Signed-off-by: Trammell Hudson <hudson@trmm.net>

tpm2_duplicate: Add policy and authorization arguments.

---

.gitignore

Test files are brought in when running `./bootstrap`. This prevents git from showing them as untracked.
Signed-off-by: Joe Richey <joerichey@google.com>

Add test/ to gitignore

---

doc/CHANGELOG.md
lib/files.c
lib/tpm2_convert.c
man/tpm2_create.1.md
man/tpm2_createprimary.1.md
man/tpm2_print.1.md
man/tpm2_startauthsession.1.md
test/integration/tests/create.sh
test/integration/tests/createprimary.sh
test/integration/tests/print.sh
tools/misc/tpm2_print.c
tools/tpm2_create.c
tools/tpm2_createprimary.c

Support `-o` and `-f` options, like in tpm2_readpublic, in tpm2_createprimary, tpm2_create and tpm2_print. This way public PEM files can be generated along with the object. Also, document the netcat listener approach for working with non session-gapping RM's, like the in-kernel RM, in tpm2_startauthsession.

Support saving PEM/DER public keys in createprimary, create and print

---

lib/tpm2.c
lib/tpm2.h
lib/tpm2_nv_util.h
tools/tpm2_createek.c
tools/tpm2_getekcertificate.c
tools/tpm2_nvread.c

tools/tpm2_nvread: use phash_alg from lib/tpm2_util to calc cphash alg

---

tools/tpm2_createek.c

Even though the below error seems like a flase positive, lets just avoid
any other issues and ensure that if the function call doesn't initialize
size to 0, that the unmarshal won't go super crazy.
tools/tpm2_createek.c: In function ‘tpm2_tool_onrun’:
tools/tpm2_createek.c:144:19: error: ‘template_size’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
TSS2_RC ret = Tss2_MU_TPMT_PUBLIC_Unmarshal(template, template_size,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
NULL, &input_public->publicArea);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tools/tpm2_createek.c:133:12: note: ‘template_size’ was declared here
UINT16 template_size;
^~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:3797: recipe for target 'tools/tools_tpm2-tpm2_createek.o' failed
make: …

tools/tpm2_createek: initialize size to 0

---

tools/misc/tpm2_checkquote.c

The variable `temp_pcrs` is uninitialized, and later partially
uninitialized when reading the selection data from file.
When activating lto optimizations, this bug presents itself showing an
error during the read of the quote:
ERROR: Malformed PCR file, pcr count cannot be greater than 32, got: ...
Fixes: #2767
Co-authored-by: Martin Liska <marxin.liska@gmail.com>
Signed-off-by: Alberto Planas <aplanas@suse.com>

tpm2_checkquote: fix uninitialized variable

---

Makefile.am
dist/bash-completion/tpm2-tools/tpm2_completion.bash
lib/pcr.c
lib/pcr.h
lib/tpm2_convert.c
lib/tpm2_convert.h
man/common/pcrs_format.md
man/tpm2_pcrread.1.md
man/tpm2_quote.1.md
test/integration/tests/pcrs_format.sh
tools/tpm2_pcrread.c
tools/tpm2_quote.c

for tpm2_pcrread and tpm2_quote, with backward compatible defaults.
Signed-off-by: Hanson Char <hchar@amazon.com>

Support pcrs output file formats "values" and "serialized"

---

lib/files.c
lib/files.h
tools/misc/tpm2_eventlog.c

The eventlog file lives is securityfs, that do not return the file size.
The current implementation first try to do a "fseek(fp, 0, SEEK_END)"
for this file, and this will always return 0.
This generate an error, and tpm2_eventlog exit with:
ERROR: Unable to run tpm2_eventlog
This patch replace the reading logic, now reading in chunks of 16KB and
reallocating the buffer if needed. Also introduces a new function in
files.c ("files_read_bytes_chunk") that helps counting the total read
size, that now is different from the ammount of allocated memory.
Fixes #2775
Signed-off-by: Alberto Planas <aplanas@suse.com>

tpm2_eventlog: read eventlog file in chunks

---

lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
test/integration/tests/rsadecrypt.sh
tools/tpm2_rsadecrypt.c
tools/tpm2_rsaencrypt.c

Fixes #2691 
With this one the scheme halg can be specified in an already known nice name format.
Eg. oaep-sha1

Fix issue where oaep hash algorithm was hardcoded

---

tools/tpm2_makecredential.c

tpm2_makecredential: Error when stdin data-size > max-halg-size

---

lib/tpm2_nv_util.h
tools/tpm2_nvdefine.c
tools/tpm2_nvwrite.c

Progresses #2764 
The NV index size is constrained to different data sets read from
the GetCapability structures because there is a dependency on the
NV operation type: Define vs Read vs Write vs Extend.
This commit addresses those parameters and chooses a sane default
in the case where GetCapability fails or fails to report the
specific property/ data set. This is especially true because some
of the properties are TPM implementation dependent.

lib/tpm2_nv_util.h: parse info for NV op specific max nv buffer sz

---

lib/tpm2_openssl.c
man/tpm2_import.1.md
test/integration/tests/import.sh
tools/tpm2_import.c

This enables wrapping an external HMAC key or a data blob under a key hierarchy.
Fixes https://github.com/tpm2-software/tpm2-tools/issues/1597

tpm2_import: add support for importing HMAC keys and sealed data blobs

---

test/integration/tests/duplicate.sh
test/integration/tests/import.sh
test/integration/tests/loadexternal.sh

The `rsautl` is deprecated. The more generic `pkeyutl` has been there since OpenSSL 1.0.0, so it is safe to just replace it.

test: Replace openssl rsautl with pkeyutl

---

tools/misc/tpm2_eventlog.c

The event log is read in chunks of CHUNK_SIZE blocks (16KB), always
checking when the EOF is reached, so is compatible with virtual files
that lives in securefs and we do not know the full size.  The current
code is not taking care of adjusting the offset when the next chunk is
read.
This patch add "size" to the base buffer where the event log is stored
in memory.
Fix #2778
Signed-off-by: Alberto Planas <aplanas@suse.com>

tpm2_eventlog: fix buffer offset when reading the event log

---

tools/misc/tpm2_eventlog.c

Fix build error on my Raspberry Pi that occurred due to usage of data type `unsigned long` instead of `size_t`.

misc/tpm2_eventlog.c: fix build error on Raspberry Pi

---

configure.ac
doc/CHANGELOG.md
doc/INSTALL.md
doc/RELEASE.md
lib/tpm2_convert.c
lib/tpm2_identity_util.c
lib/tpm2_kdfa.c
lib/tpm2_openssl.c
lib/tpm2_openssl.h
tools/misc/tpm2_certifyX509certutil.c
tools/tpm2_getekcertificate.c
tools/tpm2_tool.c

This is a first step towards OpenSSL 3.0. This PR contains a set of simple 1-for-1 replacements and code removals (see individual commits), which:
- Remove support for OpenSSL < 1.1.0, following a discussion on the mailing list and a similar step in the tpm2-tss library
- Replace no longer necessary wrapper functions by direct calls to OpenSSL
- Remove functions that have no effect in OpenSSL >= 1.1.0 (and will be removed in OpenSSL 3.0.0)
- Replace deprecated SHA256_CTX by the EVP_MD_CTX, which works with OpenSSL 1.1.0 through 3.0.0
- Replace deprecated X509_get_ with X509_getm_, which is available since OpenSSL 1.1.0
Unfortunately, all OpenSSL 3.0 related PR's must be submitted and reviewed sequentially (step-by-step). It would be very huge or cause merge conflicts otherwise.

Remove support for OpenSSL < 1.1.0 and deprecated functions

---

lib/tpm2_identity_util.c
lib/tpm2_kdfa.c
lib/tpm2_kdfe.c
lib/tpm2_openssl.c
lib/tpm2_openssl.h
lib/tpm2_util.c
tools/misc/tpm2_checkquote.c

Before, two approaches were used for digest calculation:
1) `tpm2_openssl_halg_from_tpmhalg` and the EVP_Digest
2) `tpm2_openssl_halg_to_digester` and (deprecated) digesters such as SHA256 or SHA384 
After this PR, only a single approach is used: `tpm2_openssl_md_from_tpmhalg` and the EVP_Digest. The function name was changed to highlight it returns `EVP_MD *` (the term "halg" is not much used in openssl).

Convert deprecated digesters to EVP_Digest

---

lib/tpm2_openssl.c
lib/tpm2_openssl.h

The `RSA_KEY` and `EC_KEY` are not publicly available in OpenSSL 3.0 and the generic `EVP_PKEY` must be used instead.
Since import of raw keys still requires access to the internal structures the OpenSSL 3.0 introduced a completely new approach to access key internals.
This PR mainly:
* removes the unnecessary BN_bn2binpad compatibility function
* changes `PEM_read_RSA_PUBKEY`/`PEM_read_RSAPublicKey` and `PEM_read_EC_PUBKEY` to a generic `PEM_read_PUBKEY`
* changes `PEM_read_RSAPrivateKey` and `PEM_read_ECPrivateKey` to `PEM_read_PrivateKey`
* adds functions for key import from OpenSSL 3.0 key internals via the `EVP_PKEY_get_xxx_param` functions
* removes NULL checks before OpenSSL `xxx_free` functions as these checks are done internally; the OpenSSL itself heavily relies on that

openssl: Implement EVP_PKEY based key import

---

lib/tpm2_convert.c
lib/tpm2_convert.h
lib/tpm2_identity_util.c
lib/tpm2_kdfe.c

First, this PR implements a EVP_PKEY based key export, i.e. conversion of TPM2 public key to OpenSSL's EVP_PKEY. The functions `convert_pubkey_RSA` and `convert_pubkey_ECC` are made available in `tpm2_convert.h`.
Then, the next two commits use these conversion functions to
* Convert deprecated `ECDH_compute_key` to `EVP_PKEY_derive`
* Reimplement RSA OAEP encryption using EVP functions
For more details please see the individual commits.

openssl: Replace RSA and EC_KEY by EVP_PKEY operations

---

man/tpm2_duplicate.1.md

This PR fixes fenced block formatting that uses four backtick characters instead of three.

Fix formatting issue in tpm2_duplicate.1.md

---

tools/tpm2_createpolicy.c

tpm2_createpolicy: Fix silent failure when specifing wrong pcr str

---

lib/tpm2_alg_util.c
lib/tpm2_openssl.c
lib/tpm2_openssl.h
lib/tpm2_util.h
test/integration/tests/import.sh
tools/tpm2_create.c
tools/tpm2_duplicate.c
tools/tpm2_import.c
tools/tpm2_loadexternal.c
tools/tpm2_makecredential.c

This PR rectified the -G behavior between `tpm2_create` and `tpm2_createprimary` with `tpm2_import. -G keyedhash` will give you something akin to a "seal object" in `tpm2_create` and `tpm2_createprimary`, and hmac will give you an hmac object (keyedhash with an hmac hash alg). This also makes things like `-Ghmac:sha512` possible.

Import hmac keyedhash

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvsetbits.1.md
test/integration/tests/abrmd_policycphash.sh
tools/tpm2_nvsetbits.c

tpm2_nvsetbits: Add support to calculate cpHash with --tcti=none

---

test/integration/tests/testparms.sh

Commit e858dec76686bb4c42e74e0984b433231e530f93 is supposed to ensure that the negative test is run only if `ecc521` is *not* supported, but instead it runs the negative test if `ecc521` is *available*. This worked anyway for libtpms < 0.9.0 because `camellia` was not supported, but since [libtpms 0.9.0](https://github.com/stefanberger/libtpms/releases/tag/v0.9.0) added support for this algorithm, the test suite fails now with swtpm.

testparms: fix condition for negative test

---

man/tpm2_duplicate.1.md

Fix for man page example discussed in #2827 
1. Make it sufficiently clear that there are seperate examples.
2. Fix the example-1 so it works. The key had wrong attributes.

man/tpm2_duplicate.1.md: Fix the example section

---

lib/tpm2_eventlog_yaml.c

This removes the compilation warning/error:
```
In file included from ./tools/tpm2_tool.h:11,
from lib/tpm2_eventlog_yaml.c:16:
lib/tpm2_eventlog_yaml.c: In function 'yaml_uefi_var':
lib/tpm2_eventlog_yaml.c:479:38: error: format '%lc' expects argument of type 'wint_t', but argument 2 has type 'wchar_t' {aka 'long int'} [-Werror=format=]
479 |                     tpm2_tool_output("%lc", c);
|                                      ^~~~~  ~
|                                             |
|                                             wchar_t {aka long int}
./lib/tpm2_tool_output.h:26:20: note: in definition of macro 'tpm2_tool_output'
26 |             printf(fmt, ##__VA_ARGS__);         \
|                    ^~~
lib/tpm2_eventlog_yaml.c:479:41: note: format string is defined here
479 | …
```

lib/tpm2_eventlog_yaml: use char16_t for UEFI characters

---

tools/tpm2_nvwrite.c

The unused parameter leads to a compiler warning/failure with GCC 11.1.0:
```
tools/tpm2_nvwrite.c: In function ‘process_output’:
tools/tpm2_nvwrite.c:95:69: error: unused parameter ‘flags’ [-Werror=unused-parameter]
95 | static tool_rc process_output(ESYS_CONTEXT *ectx, tpm2_option_flags flags) {
|
cc1: all warnings being treated as errors
```

tools/tpm2_nvwrite.c: remove unused "flags" parameter from process_output()

---

tools/tpm2_nvincrement.c

The unused parameter leads to a compiler warning/error with GCC 11.1.0:
```
tools/tpm2_nvincrement.c: In function ‘check_options’:
tools/tpm2_nvincrement.c:169:44: error: unused parameter ‘ectx’ [-Werror=unused-parameter]
169 | static tool_rc check_options(ESYS_CONTEXT *ectx, tpm2_option_flags flags) {
|                              ~~~~~~~~~~~~~~^~~~
```

tools/tpm2_nvincrement: mark ectx as unused for check_options()

---

tools/tpm2_nvcertify.c
tools/tpm2_nvextend.c
tools/tpm2_nvincrement.c
tools/tpm2_nvread.c
tools/tpm2_nvsetbits.c
tools/tpm2_nvwrite.c
tools/tpm2_nvwritelock.c

nvtools: fixes for Esys_TR names when calc cphash with tcti=none

---

lib/tpm2_nv_util.h
tools/tpm2_nvwrite.c

Fixes #2875
Policy authorization session must be re-instantiated on multiple
iterations of nv read if the read size exceeds the allowed operating
size. To avoid this, only a single iteration is allowed when using
policy authorization session.
Re-instantiation is avoided because compounded policies are not
possible to be replayed to arrive at the same policy digest.

tools/tpm2_nvread: fix reads > TPM2_PT_NV_BUFFER_MAX with policy session

---

lib/tpm2_nv_util.h
tools/tpm2_nvwrite.c

`max_data_size` is uint16, therefore GCC 11.1.0 gives warnings/errors like
```
./lib/tpm2_nv_util.h: In function ‘tpm2_util_nv_read’:
./lib/tpm2_nv_util.h:238:17: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘int’ [-Werror=format=]
238 |         LOG_ERR("Cannot continue as the policy auth session must be "
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
......
241 |                 "read size of %lu", max_data_size, max_data_size);
|                                     ~~~~~~~~~~~~~
|                                     |
|                                     int
```

Use %u instead of %lu format specifier for uint16

---

lib/tpm2_alg_util.c

SM2 is an asymmetric algorithm defined by OSCCA, and SM4 is a symmetric
cryptographic algorithm. It is necessary to put these two algorithms in
the right position and set the correct flags.

lib/tpm2_alg_util: Place the SM2/4 algorithm to a suitable location

---

tools/tpm2_policylocality.c

This patch fixes a bug that caused tpm2_policylocality to almost
always generate PolicyLocality(0).
There was a logical inversion that caused almost any argument
(including invalid ones) to be interpreted as zero, except "zero"
would be interpreted as one.

Fix argument parsing in tpm2_policylocality

---

.ci/docker.run
tools/tpm2_nvreadpublic.c

Currently `-Werror` is disabled in CI as part of `--disable-hardening` because not all containers support `-Wformat-security`. This misses some compiler warnings, so enable at least `-Wall -Wextra -Werror` through custom `CFLAGS`. See the fix in the second commit as an example for the kind of warnings/errors that are otherwise missed by CI.

ci: enable -Werror for GCC builds

---

Makefile.am
man/tpm2_encodeobject.1.md
tools/misc/tpm2_encodeobject.c

This adds a new tool tpm2_encodeobject in tools/misc.  It takes public and private portions of an object and encode them in a combined PEM form used by tpm2-tss-engine and other applications.
Related: #1599

tpm2_encodeobject: New tool to encode TPM2 object

---

lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
man/common/alg.md
man/tpm2_createak.1.md
man/tpm2_createek.1.md
tools/tpm2_createak.c
tools/tpm2_createek.c

Newer TPM devices like the ST33HTPHAHD4 model from STMicroelectronics support **ECC NIST_P384** besides the default **ECC NIST_P256** curve.
This patch allows to create Endorsement Keys for all ECC curves for which default EK templates are defined by the **TCG EK Credential Profile Specification Version 2.1 Rev. 13** (NIST_P256, NIST_P384, NIST_P521, and SM2_P256). 
The attached file shows that the derived **ECC NIST_P384** EK key corresponds to the public key contained in the STMicroelectronics EK certificate:
[ECC_NIST_P384_EK.txt](https://github.com/tpm2-software/tpm2-tools/files/7712062/ECC_NIST_P384_EK.txt)

tpm2_createek/tpm2_createak: Support alternative ECC curves

---

lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
lib/tpm2_util.h
tools/tpm2_createak.c

Rather than going to the TPM to get the name alg for the EK via a
TPM2_ReadPublic call, just use the name as cached by ESYS. The name of
an object is the name algorithm followed by the hash itself.
Not only is this faster, but prevents a MITM from lying to use about the
EK properties as the TPM2_Readpublic was not protected with a session.

tpm2_createak: use Esys_TR_GetName over ReadPublic

---

tools/tpm2_nvdefine.c

When authenticating with the platform hierarchy, you need attribute
TPMA_NV_PLATFORMCREATE per table 214 of:
- https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part2_Structures_pub.pdf

tpm2_nvdefine: set TPMA_NV_PLATFORMCREATE

---

tools/tpm2_getcap.c

tools/tpm2_getcap: add escape character when string has quotes

---

Makefile.am
dist/bash-completion/tpm2-tools/tss2_gettpm2object
man/tss2_gettpm2object.1.md
test/integration/fapi/fapi-gettpm2object.sh
tools/fapi/tss2_gettpm2object.c

* The new command tss2_gettpm2object was added. With this command context
files which can be used for tpm2 tool commands can be created.
* For persistent objects only the textual representation of the handle as
hex number will be written and for keys a tpm2 tool context file will
be written.
* Creation of a context file: tss2_gettpm2object -p /HS/SRK/mykey -c mykey.ctx
* Output of an NV index: tss2_gettpm2object -p /nv/Owner/mynv -c-
* An Integration test and a man page with examples is also added.

fapi: add new command to enable the use of fapi objects for tpm2 tools

---

configure.ac

Rather than only allowing efivar to be autodetected and included, allow
packagers to specif --with-efivar and --without-efivar to control
packaging dependencies.
With this patch, the following behavior should be observed:
+----------------+-------------+------------------+
| config options | efi present |      result      |
+----------------+-------------+------------------+
| auto (default) | yes         | efi in build     |
| auto (default) | no          | efi not in build |
| --with-efi     | yes         | efi in build     |
| --with-efi     | no          | fail configure   |
| --without-efi  | yes         | efi not in build |
| --without-efi  | yes         | efi not in build |
+----------------+-------------+------------------+
Fixes #2835
Fixes #2927 
Signed-off-by: William Roberts …

configure: enable sane auto detetcion of efivar

---

test/integration/tests/getekcertificate.sh
tools/tpm2_getekcertificate.c

There were two places where the fix was needed
1. In the tool source code where a forward slash was always
appended irrespective of it already being part of the link
specified by the user.
2. In the integration test where curl tests the link to the
ekop.intel.com backend. It now requires the full link to
include the base64 encoded ek pub hash.

tools/tpm2_getekcertificate: fixed the url link to ekop.intel.com

---

lib/tpm2_options.c
tools/tpm2_makecredential.c

Fixes #2961 
Despite setting the 'quiet' flag with -Q the warning messages were
always displayed.

tools/tpm2_tool.c: Fix an issue where LOG_WARN is always displayed

---

lib/tpm2_nv_util.h
lib/tpm2_util.c
lib/tpm2_util.h
man/tpm2_nvread.1.md
test/integration/tests/nv.sh
tools/tpm2_createek.c
tools/tpm2_getekcertificate.c
tools/tpm2_nvread.c

Enable parsing and YAML-style output for the different NV index types.
Fixes #2253

tools/tpm2_nvread: add human readable output for NV content

---

test/integration/tests/nv.sh

FreeBSD version of the bash utility cmp does not use -i to specify
the skip bytes. Instead the skip bytes must be specified as args

test/integration/tests/nv.sh: non portable cmdline option in cmp

---

lib/efi_event.h
lib/tpm2_eventlog_yaml.c
test/unit/test_tpm2_eventlog_yaml.c

Patch set for handling of new event types in tpm2_eventlog: EV_EFI_PLATFORM_FIRMWARE_BLOB2, EV_EFI_HANDOFF_TABLES2, EV_EFI_VARIABLE_BOOT2
Found the need for handling newer entry types while looking at the UEFI boot event logs on recent HW acquisitions in IBM cloud.
Reference: https://trustedcomputinggroup.org/wp-content/uploads/TCG_PCClient_PFP_r1p05_v22_02dec2020.pdf

Adding new event types to tpm2_eventlog

---

.cirrus.yml

Fixes CI Error:
pkg update -f
Updating FreeBSD repository catalogue...
Fetching meta.conf: . done
Fetching packagesite.pkg: .......... done
Processing entries:
Newer FreeBSD version for package php74-pear-channel-pirum:
To ignore this error set IGNORE_OSVERSION=yes
package: 1203000
running kernel: 1202000
Ignore the mismatch and continue? [y/N]: pkg: repository FreeBSD contains packages for wrong OS version: FreeBSD:12:amd64
Processing entries... done
Unable to update repository FreeBSD
Error updating repositories!
Seems as though 12-2 is EOL so update to something newer.
Related to:
https://forums.freebsd.org/threads/pkg-repository-freebsd-contains-packages-for-wrong-os-version-freebsd-12-amd64.78856/
http://soulrace.top:3000/mirror_group/curl/commit/7db6bc5ecaef321f32639149ba3737b1c8393b …

.cirrus.yml: update freebsd version

---

tools/fapi/tss2_quote.c

pcrLog is an optional parameter. If pcrLog is not used as parameter currently
the pcr log is still calculated in Fapi_Quote.
To avoid this calculation a NULL pointer will be passed to Fapi_Quote if the
parameter pcrLog is not passed.
So tss2_quote can be executed for a user which has no access rights to the
files with the system measurements.

fapi: fix usage of parameter pcrLog for tss2_quote.

---

docs/CONTRIBUTING.md

Define a security policy outside of reporting to Intel.

SECURITY: initial commit of seperate policy file

---

tools/misc/tpm2_eventlog.c

Currently the code allocates an unnecessary extra chunk. Simplify the
code and avoid memory waste.
Signed-off-by: Matthias Gerstner <matthias.gerstner@suse.de>

tpm2_eventlog: simplify and optimize allocation for read loop

---

test/integration/tests/getekcertificate.sh

Signed-off-by: Alberto Planas <aplanas@suse.com>

tests/getekcertificate.sh: Skip the test if curl is not present

---

.ci/docker.run

Fixes:
fatal: unsafe repository ('/workspace/tpm2-tools' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /workspace/tpm2-tools

ci: mark /workspace/tpm2-tools safe

---

tools/tpm2_policyor.c

The TPML_DIGEST policy list was calloc'd for some reason, however it
could just be statically allocated in the context. The side effect is
that when no options or arguments were given a NPD occured when checking
the count of the policy list. TO fix this, just statically allocate it.

tpm2_policyor: fix unallocated policy list

---

Makefile.am
lib/files.c
lib/tpm2_util.h
man/tpm2_policyor.1.md
test/integration/tests/abrmd_policyor.sh
test/unit/test_tpm2_policy.c

this is fun, if a user specified `-l` with an argument the result was concatenation. These two commands are the same:
```bash
tpm2 policyor -l sha256:policy1 sha256:policy2
tpm2 policyor sha256:policy1,policy2
```
So while very unlikely in use, lets not break it, its easy enough to support.

policyor: test onscure -l and argument causing concatenation of policies

---

man/tpm2_eventlog.1.md

This is just a document update.
Add missing description of --eventlog-version option.
Signed-off-by: Misono Tomohiro <misono.tomohiro@fujitsu.com>

doc: Update tpm2_eventlog man for --eventlog-version option

---

lib/tpm2_options.c

In tpm2_handle_options there was an attempt to print a warning
message when TPM2_OPTIONS_NO_SAPI was set. However, it was done
in a location that was skipped after checking the boolean value.

lib/tpm2_options.c: relocate unreachable warning message

---

tools/fapi/tss2_gettpm2object.c

A potential resource leak would have occured by exiting in an error
check without freeing the file pointer in tss2_tool_onrun.

tools/fapi/tpm2_gettpm2object.c: fix resource leak

---

tools/tpm2_loadexternal.c

In process_input the return value of the function tpm2_tr_get_name
must be tested prior to continuing.

tools/tpm2_loadexternal.c: fix for unchecked return value

---

lib/tpm2_alg_util.c

Must test ext_alg_str before dereferencing in
tpm2_alg_util_handle_rsa_ext_alg
char *ext_alg_str = calloc(1, strlen(alg_spec) + strlen("rsa") +
RSA_KEYBITS_STRLEN)

lib/tpm2_alg_util.c: Fix potential null pointer dereference

---

man/tpm2_certify.1.md
test/integration/tests/certify.sh
tools/tpm2_certify.c

Fixes #3082
The short options for the signing-key-auth and certified-key-auth
were swapped. The case fix in the man page makes it less intuitive
but have to go through with the change so we don't break any
existing scripts.
This change does not affect the long options. Tests have been
added to ensure the functionality.

tools/tpm2_certify: fix man page for short options and add tests

---

tools/tpm2_pcrreset.c

The format specifier has been fixed.

tools/tpm2_pcrreset.c: fix build errors in 32 bit systems

---

tools/tpm2_sessionconfig.c

Currently their is no way to get the session digest without running a
policy command.

tpm2_sessionconfig: print digest

---

lib/tpm2_eventlog_yaml.c

Make the code a bit clearer by making it clear
we are subtracting the size of the EFI_GUID member
from the EFI_SIGNATURE_DATA size.

tpm2_eventlog: clean up some magic numbers

---

docs/CHANGELOG.md
scripts/utils/check_endorsement_cert.sh

This utility checks the endorsement key and it's certificate for the following:
1. Downloads intermediate and root certificate using authority information
access from the endorsement-key-certificate.
2. Endorsement-key-public match with the endorsement-key-certificate.
3. Subject and issuer hashes of certficates in the chain.
4. Validation of the certificate chain.
This utility assumes a typical cert chain: Root->Intermediate->Entity.
Requirements:
1. The ek-public and ek-certificate specified - in that order
2. The ekpublic be specified in TPM2B_PUBLIC format and the endorsement
certificate in PEM format.

check_endorsement_cert.sh: utility for validate ekcert validation

---

lib/tpm2_alg_util.c
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_create.1.md
man/tpm2_createprimary.1.md
man/tpm2_import.1.md
man/tpm2_loadexternal.1.md
test/integration/tests/create.sh
test/integration/tests/createprimary.sh
test/integration/tests/import.sh
test/integration/tests/loadexternal.sh
tools/tpm2_import.c
tools/tpm2_loadexternal.c

Support the ability to hardcode hex strings into the -L value over a
file. This allows for things like tpm2_create -L 1234...56abcd
Related-to: https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/AW2LZ35JSECRAW3VDE5ZF3AEP42PRCKY/

policy: support raw digest strings in -L options

---

tools/fapi/tss2_provision.c

The -L short parameter was not marked as parameter with required arg in the short opt list.
Fixes #3147.

tss2_provision: fix usage of -L parameter.

---

man/tss2_import.1.md

The man page repeats JSON encoded X and stores it under a path. De deuplicate the description to make it easier to grok and get the what it imports up front in the description so the reader knows immediately that this imports keys, policies and policy templates.

tss2_import: clarify tool description

---

lib/tpm2_eventlog_yaml.c
test/integration/fixtures/event-gce-ubuntu-2104-log.bin.yaml
test/integration/fixtures/event-moklisttrusted.bin.yaml

Now besides MokListTrusted only known variables are parsed any further:
- db, Shim: parsed as EFI_SIGNATURE_DATA
- SbatLevel: parsed as string
- other: variable data is printed as hex string
Fixes #3145

tpm2_eventlog_yaml: parse EV_EFI_VARIABLE_AUTHORITY variables explicitly

---

tools/tpm2_getekcertificate.c

print_intel_ek_certificate_warning is already called in process_input, no need to call it on this path as well.
@idesai I think we can drop this but I am not 100% sure, can you look?

tpm2_getekcertificate: drop redundant function call

---

.lgtm.yml

tpm2-tss depends on uuid since commit:
1448eee7468d FAPI: Add event logging for firmware and IMA events.
Fixes:
[2022-11-16 20:57:10] [build-stderr] installed software in a non-standard prefix. [2022-11-16 20:57:10] [build-stderr] Alternatively, you may set the environment variables UUID_CFLAGS [2022-11-16 20:57:10] [build-stderr] and UUID_LIBS to avoid the need to call pkg-config. [2022-11-16 20:57:10] [build-stderr] See the pkg-config man page for more details. [2022-11-16 20:57:10] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/work/lgtm-workspace/lgtm/extract.sh]) A fatal error occurred: Exit status 1 from command: [/opt/work/lgtm-workspace/lgtm/extract.sh]

lgtm: add uuid-dev dependency

---

man/tpm2_print.1.md
test/integration/tests/print.sh
tools/misc/tpm2_print.c

Support printing the handle and name from a serialized ESYS_TR. This could be useful for verifying an object is what's expected before using it to start an auth session for instance.

tpm2_print: support printing serialized ESYS_TR's

---

Makefile.am
configure.ac
lib/tpm2.c
lib/tpm2_capability.c
lib/tpm2_capability.h
man/tpm2_getcap.1.md
test/integration/tests/getcap.sh
test/scripts/echo_tcti.py
test/unit/vendor_tests.sh
tools/tpm2_getcap.c

Requires tpm2-tss 4.0
Support vendor properties as a vendor agnostic TPM2B buffer. This also introduces the -i or --ignore-more option to ignore the moreData byte returned from the TPM.
Introduce -i to ignore moreData when it's set to 1 but moreData does not follow.
Example output from my NUC:
./tools/tpm2 getcap -i --tcti=pcap:device:/dev/tpmrm0 vendor:1 0000000100000003

tpm2_getcap: support vendor properties

---

configure.ac
test/scripts/echo_tcti.py

Remove the whitespace errors and format with black formatter.

test/echo_tcti.py: format with black

---

configure.ac
lib/tpm2_util.h
man/tpm2_startauthsession.1.md
test/integration/tests/abrmd_extended-sessions.sh
tools/tpm2_startauthsession.c

When an AuthSession is used with a tpmKey, that key MUST be verified in order to trust the connection. Think of this as analagous to known hosts with ssh. With Serialized ESYS_TR's or Context Files, the name is associated with that handle and ESAPI is instrumented to perform all the required name checks. When loaded from a persistent handle, ESAPI does not have the associated metadata and reads the name from the handle with a ReadPublic call. Becuase of this, an attacker COULD MiTM the connection with their own key. Thus, with persistent handles we must verify the name from some other source. The TPM name could be thought of as an ssh key fingerprint.
To fix this, provide a -n argument for a name file as output by readpublic or could be generated as a binary array of the objects name. …

tpm2_startauthsession: VERIFY persistent handles

---

lib/tool_rc.c
tools/tpm2_create.c

tpm2_create option -c uses TPM2_CreateLoaded under the hood which is not always supported, thus add a note bolstering what users should do, which is to use tpm2_create -u -r with tpm2_load -u -r -c to get the desired result. This is already documented in the man page, but add a note.
$ ./tools/tpm2 create -C primary.ctx -c key.ctx
ERROR: Esys_CreateLoaded(0x143) - tpm:error(2.0): command code not supported NOTE: The TPM does not support CreateLoaded command!! Use tpm2_create with the -u and -r options and then call tpm2_load with -c and use the -u and -r outputs of tpm2_create in tpm2_load.
ERROR: Unable to run create
$ echo $?
5
Fixes: #3171

tpm2_create: add NOTE for CreateLoaded ENOTSUPP

---

.ci/download-deps.sh

The error undefined reference to curl_url_strerror when using curl less than 7.80.0 should be fixed.

ci: update default in download deps to tss 3.2.2

---

lib/tpm2.c

LOG_PERR(Eys_Load, rval);
The first parameter in the function should be Esys_Load.
Signed-off-by: yuxiaojun <yuxiaojun@uniontech.com>

fix:wrong function name of "Esys_Load"

---

test/integration/tests/abrmd_policycountertimer.sh
test/integration/tests/abrmd_policynv.sh

Errata TCG Trusted Platform Module Library Revision 1.59 Version 1.4, Section 2.5 TPM_EO – two’s complement states:
"The signed arithmetic operations are performed using twos-complement." The tests policynv and policycountertimer were adapted to work with the complement representation of signed numbers. If the tests return the error 0x126 the test will be skipped.
Fixes:  #3233

tpm errata: switch to twos-complement.

---

lib/tpm2_eventlog.c
lib/tpm2_eventlog.h
test/unit/test_tpm2_eventlog.c

EV_NO_ACTION events should not be extended to PCR registers. Fixes: #3224

tpm2_eventlog.c Fix pcr extension for EV_NO_ACTION

---

lib/tpm2_kdfa.c

The kdfa implementation did produce an error caused by the flags -flto -_FORTIFY_SOURCE=3 on Fedora rawhide.
This error can be avoided by switching off the optimization with pragma.
Fixes: #3210.

kdfa.c Fix problem with FORTIFY_SOURCE on Fedora

---

man/tpm2_ecdhzgen.1.md
test/integration/tests/ecc.sh
tools/tpm2_ecdhzgen.c

Currently the public parameter had to be an ECC point (format TPM2B_ECC_POINT). Now this point can also be used with a public key (format TPM2B_PUBLIC) by using the option (--public-key, -k).
The ecc integration tests are extended with an example were the shared secret with two ECC keys is added. 
Fixes: #3202

tpm2_ecdhzgen: Add public-key parameter.

---

.readthedocs.yml

python requirements were added because of the error: module 'jinja2' has no attribute 'contextfilter'

readthedocs.yml add python requirements

---

docs/requirements.in
docs/requirements.txt

The latest markdown version did produce the error: missing 1 required positional argument: 'md_globals' Markdown<3.2 was added to the requirement file.

readthedocs: Add markdown to requirement file.

---

man/tpm2_getekcertificate.1.md
test/integration/tests/getekcertificate.sh
tools/tpm2_getekcertificate.c

Adds support for fetching AMD EK certificates via tpm2_getekcertificate. Tested on my AMD Ryzen 9 3900XT fTPM. I haven't had the opportunity to check on Intel/other platforms.
Two changes were made to the original PR #3207:
*  scanbuild issues and problems were fixed.
* The corresponding integration test was adapted.
Signed-off-by: subtervisor <subtervisor@proton.me>
Co-authored-by: Juergen Repp <juergen_repp@web.de>

Add AMD EK certificate fetching support

---

man/tpm2_clear.1.md

Add a link to the spec about the details performed during a clear to help "clear up" confusion.

man/tpm2_clear: add more details about action

---

lib/efi_event.h
lib/tpm2_eventlog.c
lib/tpm2_eventlog.h
test/unit/test_tpm2_eventlog.c

According to the "TCG PC Client Platform Firmware Profile Specification Level 00 Version 1.05 Revision 23" section 10.4.5.3 the startup locality is the starting value of PCR0. This can be currently either 0 or 3.
This implements support for replaying logs where locality is not 0. 
Fixes: https://github.com/tpm2-software/tpm2-tools/issues/3146

tpm2_eventlog: add support for PCR0 replay with different StartupLocality

---

test/integration/fapi/fapi-nv-write-read-policy-or.sh
test/integration/fapi/fapi-nv-write-read-policy-or2.sh

fapi did not encrypt tpm2b parameters for objects with policy authorization. After this error is fixed the auth value is required to compute the key for parameter encryption. The affected tests were skipped or adapted.

fapi: fix tests with policy and auth value.

---

configure.ac
lib/tpm2_eventlog_yaml.c

I noticed during my testing `DevicePath`s are not decoded even when compiled with `--with-efivar`.
The reason was that the code checks for `HAVE_EFIVAR_EFIVAR_H`, but only `PKG_CHECK_MODULES` is used to detect if `libefivar.so` is present, not if the header is also there. This commit adds that check.

configure: check for efivar/efivar.h manually

---

man/tpm2_verifysignature.1.md

There is actually no -m option in tpm2_sign, the example command has made a mistake, so correct it, link what's in man/tpm2_sign.1.md.

man/tpm2_verifysignature.1.md: correct example command tpm2_sign

---

man/tpm2_verifysignature.1.md
tools/tpm2_unseal.c

Other tpm2_xxx.c have qualifier "static" before their "main function",
for example: static tool_rc load(ESYS_CONTEXT *ectx) in tpm2_load.c,
only function unseal in tpm2_unseal.c lacks it, so add it before unseal
function to enhance privacy.

tools/tpm2_unseal.c: add qualifier static to enhance privacy of unseal function

---

man/tpm2_encodeobject.1.md

There is no -c option in encodeobject, use the correct -o option for output instead.

man/tpm2_encodeobject: Correct example usage

---

.cirrus.yml

13-1 caused errors during package installation.

cirrus-ci update image-family to freebsd-13-2

---

test/integration/fapi/fapi-nv-write-read-policy-or.sh
test/integration/fapi/fapi-nv-write-read-policy-or2.sh

fapi now encrypts tpm2b parameters for objects with policy authorization in a second session. Thus the related tests which did not work because parameter encryption was done by the policy session now work again.
This reverts commit 7cb3fdf786ab6ad749174a4548f4662e56b9ae15.

Revert "fapi: fix tests with policy and auth value."

---

man/tpm2_duplicate.1.md
tools/tpm2_duplicate.c

The -G --wrapper-algorithm option was used for the symmetric algorithm used for the inner wrapper and the algorithm of the public key used to wrap an openSSL key for the destination TPM.
To match this parameter with the options used for tpm2_create the long option --key-algorithm is now also mapped to -G. Fixes #3259

tpm2_duplicate: add --key-algorithm option.

---

tools/tpm2_createek.c

I externally create the EK with a given template and nonce. And I wondered why `tpm2_createek` yields a different EK than what I retrieve. I eventually figured out that the `tpm2_createek` code falsely copies the pointer into the final template, instead of the actual nonce.
By fixing this with these changes, the EK from `tpm2_createek` and my code is consistent.

tpm2_createek: Fix integrating nonce

---

man/tpm2_createek.1.md

The example
```
tpm2_createek -G rsa -u ek.pub
```
from `man tpm2_createek` misses to provide `-c`.
It thus fails with
```
ERROR: Expected option -c
```
According to [tools/tpm2_createek.c:441](https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_createek.c#L441), the option must be present in any case. Adjust the man page example accordingly.

tpm2_createek: Correct man page example

---

test/integration/tests/sign.sh

fix syntax error (a space character is missing) making the test not ending correctly

test sign: fix syntax error

---

tools/tpm2_tool.c

When tpm2 is placed behind a wrapper, or if not immediately in the PATH, the argv0 may be the full path to the binary.
This commit reworks the parsing of the argv0 to only read from its basename.

tpm2: accept full path to tpm2 binary

---

test/integration/tests/checkquote.sh
tools/misc/tpm2_checkquote.c

Different padding versions are tested until one is successful.
An integration test with rsapss padding is added.
Addresses: #3283.

tpm2_checkquote.c Add rsapss padding.

---

tools/tpm2_getekcertificate.c

ek_uri was not freed if get_ek_server_address failed.

tpm2_getekcertificate.c Fix leak

---

lib/tpm2_options.c
lib/tpm2_options.h
tools/tpm2_nvcertify.c
tools/tpm2_nvdefine.c
tools/tpm2_nvextend.c
tools/tpm2_nvincrement.c
tools/tpm2_nvread.c
tools/tpm2_nvreadlock.c
tools/tpm2_nvreadpublic.c
tools/tpm2_nvsetbits.c
tools/tpm2_nvundefine.c
tools/tpm2_nvwrite.c
tools/tpm2_nvwritelock.c

A command that should work with no options would fail:
./tools/tpm2 nvdefine
ERROR:esys:src/tss2-esys/api/Esys_GetCapability.c:164:Esys_GetCapability_Async() esyscontext is NULL. ERROR:esys:src/tss2-esys/api/Esys_GetCapability.c:83:Esys_GetCapability() Error in async function ErrorCode (0x00070005) ERROR: Esys_NV_ReadPublic(0x70005) - esapi:A pointer is NULL that isn't allowed to be NULL. ERROR: Unable to run nvdefine
The handling for the optional and fake TCTI states would get conflated and not initialize an ESAPI context. Clean up the handling and make supporting a fake TCTI it's own option bit to make it less confusing to code.
After this the tool works as expected:
./tools/tpm2 nvdefine
nv-index: 0x1000000
Fixes: #3314

options: fix TCTI handling

---

tools/tpm2_nvread.c

Fixes:
./tools/tpm2 nvread
WARN: Reading full size of the NV index
ERROR: object string is empty
ERROR: Invalid handle authorization.
ERROR: Unable to run nvread
with:
./tools/tpm2 nvread
ERROR: Must specify NV index argument
Usage: nvread [<options>] <arguments>
Where <options> are:
[ -C | --hierarchy=<value>] [ -o | --output=<value>] [ -s | --size=<value>] [ --offset=<value>]
[ --cphash=<value>] [ --rphash=<value>] [ -n | --name=<value>] [ -P | --auth=<value>]
[ -S | --session=<value>] [ --print-yaml]

tpm2_nvread: fix input handling no nv index

---

tools/tpm2_tool.c

tpm2_tool.c did not compile without the include libgen.h on netbsd. Fixes: #3321

tpm2_tool.c Fix missing include for basename.

---

lib/tpm2_session.c
test/integration/tests/unseal.sh

If continue session was disabled a error did occur in the function for restoring the session context.
Now after usage of an session with continue session disabled the context will not be saved and the session context file will be deleted.
In one integration test continue session is now disabled and the flush for this session is removed.
Fixes: #3295

tpm2_sessionconfig fix usage of --disable-continuesession

---

lib/tpm2_session.c
test/integration/tests/unseal.sh

This behavior would not be backwards compat, but this patch does the bare minimum so we can just revert it on the next major release.

session: do not delete on flush

---

configure.ac

Ensure crypto function configure-time detection uses CRYPTO_LIBS.

---

.cirrus.yml

The tss compilation with tcti-libtpms is currently not possible for FreeBSD.

cirrus.yml fix tss compilation with libtpms

---

.github/workflows/main.yml

Ubuntu 18.04 will not be supported for the next tss version. Thus Ubuntu 18.04 has to be removed from the tool CI for master-tss-build-test.

CI: Remove Ubuntu 18.04 from the CI tss master test.

---

lib/files.c
lib/files.h
lib/tpm2.c
lib/tpm2.h
lib/tpm2_options.h
lib/tpm2_session.c
lib/tpm2_util.c
lib/tpm2_util.h
man/common/options.md
test/integration/tests/load.sh
test/unit/test_tpm2_session.c
tools/fapi/tss2_gettpm2object.c
tools/misc/tpm2_encodeobject.c
tools/tpm2_changeauth.c
tools/tpm2_create.c
tools/tpm2_createak.c
tools/tpm2_createek.c
tools/tpm2_createprimary.c
tools/tpm2_import.c
tools/tpm2_load.c
tools/tpm2_loadexternal.c

If the environment variable TPM2TOOLS_AUTOFLUSH exists transient objects will be removed after they were saved and stored to disk. Also a transient parent will be removed if a context file for this parent was used by this command.
For the commands which will check the autoflush also an option -R is added to enable the autoflush independent from the environment variable.
Addresses: #1511

Save Context: Add the possibility for autoflush.

---

.readthedocs.yml

To fix the error "Config validation error in build.os. Value build not found".

readthedocs: Add configuration key build to the readthedocs yaml file.

---

lib/tpm2_auth_util.c

When reading auths from a file, add a check that they are NULL terminated.

Auth input: Check for NULL termination

---

lib/tpm2_policy.c

The format directive %lu for size_t could not be compiled on 32 bit systems. %zu is now used instead of %l

lib/tpm2_policy.c Fix wrong format directive for size_t

---

lib/pcr.c

gcc version 10.2.1 on raspian 10.2.1 did produce the compile error "may be used uninitialized". The error was not possible. To enable compilation the affected variable is initialized.

lib/pcr.c Fix compile error may be used uninitialized.

---

lib/tpm2_util.c

The function tpm2_util_env_yes did check the name of the variable instead of the value. Fixes: #3353

tpm2_util.c: fix check of environment  variable.

---

test/integration/tests/certify.sh
test/integration/tests/certifycreation.sh
test/integration/tests/commandaudit.sh
test/integration/tests/gettime.sh
test/integration/tests/nvcertify.sh
test/integration/tests/sessionaudit.sh
tools/misc/tpm2_print.c

Not all types of TPMU_ATTEST were supported. The printing for the missing sub types is implemented.
For every new sub type a print is added to the corresponding integration test.
Fixes: #3362

tpm2_print: Extend printing of TPMS_ATTEST objects.

---

.github/workflows/main.yml
lib/pcr.c
lib/tpm2_session.c
test/integration/tests/unseal.sh

* The test with the tss master is now running on ubuntu 20.04 instead of 18.04
* If continue session was disabled a error did occur in the function for restoring the session context.
Now after usage of an session with continue session disabled the context will not be saved and the session context file will be deleted.
In one integration test continue session is now disabled and the flush for this session is removed.

tpm2_sessionconfig fix usage of --disable-continuesession (5.6.X)

---

tools/tpm2_getekcertificate.c
tools/tpm2_nvdefine.c
tools/tpm2_nvreadpublic.c

Wrong arguments are used in tpm2_getekcertificate and tpm2_nvdefine when accessing the list of NV indexes in use. This works fine on little-endian systems, but on big-endian systems this will not find any NV indexes, causing issues when using these functions without an argument. Also, use the same argument in tpm2_nvreadpublic.
Running on s390x system with upstream tpm2-tools:
```
[root@localhost ~]# /usr/local/bin/tpm2_nvdefine
WARNING:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:344:Esys_NV_DefineSpace_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:122:Esys_NV_DefineSpace() Esys Finish ErrorCode (0x0000014c)
ERROR: Failed to define NV area at index 0x1000000
ERROR: Esys_NV_DefineSpace(0x14C) - tpm:error(2.0): NV Index or persistent object already defined …
```

Fix issue with reading NV indexes

---

tools/tpm2_create.c

If the options --creation-hash,  --creation-ticket, or --creation-data were used together with --key-context context save for the handle ESYS_TR_NONE was called and did produce an error.
Now the object is loaded and context save is calles with the correct handle. Fixes: #3379

tpm2_create: Fix context save error.

---

tools/tpm2_gettestresult.c

The testResult returned from Esys_GetTestResult is unnecessarily masked, causing the tool to be unable to identify TPM2_RC_NEEDS_TEST.

Fix handling of testResult in tpm2_gettestresult

---

tools/tpm2_evictcontrol.c

If the -o parameter was used when a persistent handle should be evicted a segfault did occur.
Now the object is evicted an a warning is displayed.

tpm2_evictcontrol.c: Fix segfault for output of handle ESYS_TR_NONE

---

lib/tpm2_openssl.c

```
lib/tpm2_openssl.c: In function ‘do_open_file’:
lib/tpm2_openssl.c:433:31: error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
433 |     char *tmp = calloc(sizeof(char), file_size + 1);
|                               ^~~~
lib/tpm2_openssl.c:433:31: note: earlier argument should specify number of elements, later size of each element
lib/tpm2_openssl.c: In function ‘do_stdin’:
lib/tpm2_openssl.c:488:31: error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
488 |     void *buf = calloc(sizeof(BYTE), UINT16_MAX + 1);
|                               ^~~~
lib/tpm2_openssl.c:488:31: note: earlier argument should specify number of …
```

Fix build failure due to `-Werror=calloc-transposed-args`

---

man/tpm2_unseal.1.md

This fixes a small issue in the tpm2_unseal(1) markdown man page.

Remove duplicate text in tpm2_unseal.1.md

---

.cirrus.yml

* 14.0 did produce the error:
FreeBSD contains packages for wrong OS version: FreeBSD:14:amd64
* pyyaml is now installed via pip.

cirrus-ci update image-family to freebsd-14-1

---

tools/tpm2_createpolicy.c

The created session is flushed if a trial policy is only used to compute the policy digest.
Fixes: #3427

tpm2_createpolicy: flush session for trial policy.

---

docs/requirements.txt

markdown 3.1.1 is incompatible to mkdocs 1.6.1 therefore markdown 3.3.6 is now used.

readthedocs: update markdown

---

.github/workflows/codeql.yml

codeql cpp failed because the macro LT_LIB_DLLOAD was not found.

codeql: add libtltdl-dev

---

test/integration/tests/getekcertificate.sh
tools/tpm2_getekcertificate.c

Fixes #3435.
_Note_:
* The test case uses self-signed certificates because I didn't found a valid one in `https://ekop.intel.com` (e.g. RSA 3072 or ECC P384)

tpm2_getekcertificate: add support to high range NV indexes 

---

man/tpm2_getekcertificate.1.md
test/integration/tests/getekcertificate.sh
tools/tpm2_getekcertificate.c

The option --ek-public (-u) can now used to select the certifcate in NV ram that will be written to the output file. Example:
```
tpm2_createek -G ecc384 -u ek_ecc384.pub -c ek_ecc384.ctx 
tpm2_getekcertificate -o ek_ecc384.cert -u ek_ecc384.pub
```
An integration test for ecc and rsa certificates is added.

tpm2_getekcertificate: Provide option -u for certs in NV ram.

---

tools/tpm2_getrandom.c

The --force parameter did require an argument but was always set to true if used. Now no_argument is used in the option table.

tpm2_getrandom: Fix --force parameter

---

.ci/docker.run
.github/workflows/main.yml

The usage of https://codecov.io/bash is deprecated and replaced with a github action using codecov/codecov-action@v5.

ci: update codecoverage action.

---

.cirrus.yml

The resource projects/freebsd-org-cloud-dev/global/images/family/freebsd-14-1 was not found.

ci: Cirrus ci update freebsd-14-1 to freebsd-14-2

---

tools/misc/tpm2_encodeobject.c

emptyAuth was set to 1 if an auth value for the input key was used  and to 0 if an auth value was used.
Fixes: #3458

tpm2_encode: Fix setting emptyAuth in generated pem file.

---

Makefile.am

In parallel with https://github.com/tpm2-software/tpm2-tss/pull/2952

build: Remove deprecrated ACLOCAL_AMFLAGS

---

man/tpm2_getekcertificate.1.md
tools/tpm2_getekcertificate.c

New option to handle x509 DER with trailing data
ST micro's ST33HTPHF2ENIST TPM creates NIST P-256 ECC and RSA EK certificates with 0xff data padded to a fixed 1600 bytes length. The option "--x509-trunc" or "-t" parses the output of "nv_read" with a X509 parser and truncates the trailing data. This makes the output formate more accessable to GOLANG's X509.ParseCertificate(). Details about this issue can be found at: https://github.com/tpm2-software/tpm2-tools/issues/3474
Also, added the documentation to ./man/tpm2_getekcertificate.1.md mentioned at : https://github.com/tpm2-software/tpm2-tools/pull/3481#issuecomment-2848545759
Sorry to mess up the original PR by missing the --signed-off in a commit.
I'll be more careful next time.
Signed-off-by: Samuel Cheng <samuelogre@gmail.com>

 tpm2_getekcertificate: add option --x509-trunc 

---

configure.ac

Wformat is included only for Wformat-security and Wformat-security can't be checked without Wformat so they both might as well be checked together and doing the checks separately fails as described below. 
Keeping configure.ac the way it is fails to complete ./configure with GCC 14.2 on kernel 6.12.21-4-MANJARO

Add Wformat-security to Wformat check

---

man/common/options.md

Removal of a stray "x" in manual pages.

options.md: fix typo

---

lib/tpm2_eventlog.c
lib/tpm2_eventlog_yaml.c

latest revision (Level 00 Version 1.06 Revision 52 -- December 4, 2023) of the `TCG PC Client Platform Firmware Profile Specification` added a leading Scope section which shifted all the sections.
Latest spec:
<https://trustedcomputinggroup.org/wp-content/uploads/TCG-PC-Client-Platform-Firmware-Profile-Version-1.06-Revision-52_pub-2.pdf>
Previous revision:
<https://trustedcomputinggroup.org/wp-content/uploads/TCG_PCClient_PFP_r1p05_05_3feb20.pdf>

eventlog: TCG PC Client FPF renumbered its sections

---

lib/pcr.c
lib/pcr.h
lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
man/tpm2_pcrevent.1.md
man/tpm2_pcrextend.1.md
man/tpm2_pcrread.1.md
test/integration/tests/pcrevent.sh
test/integration/tests/pcrextend.sh
tools/tpm2_pcrevent.c
tools/tpm2_pcrextend.c
tools/tpm2_pcrread.c
tools/tpm2_quote.c

Session support is added for the following commands: tpm2_pcrextend, tpm2_event, and tpm2_pcrread.
Examples for usage:
```
tpm2_startauthsession -Q --session audit_session.ctx --audit
tpm2_pcrread sha256:0 -o pcr0  -S audit_session.ctx
tpm2_startauthsession -Q --session hmac_session.ctx --hmac 
tpm2_startauthsession -Q --session audit_session.ctx --audit
tpm2_pcrextend -S audit_session.ctx -P session:hmac_session.ctx \
16:sha256=b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
tpm2_startauthsession -Q --session hmac_session.ctx --hmac 
tpm2_startauthsession -Q   --session audit_session.ctx --audit
echo event |tpm2_pcrevent -S audit_session.ctx -Psession:hmac_session.ctx 10
``

pcr commands: session support added.

---

man/tpm2_certify.1.md
test/integration/tests/certify.sh
tools/tpm2_certify.c

The default for qualifying data is still 0x00, 0xff, 0x55, 0xaa. But the value now can be adjusted with the parameter --qualifying-data. Addresses: #3489

tpm2_certify: Add parameter qualifying-data.

---

.cirrus.yml
.github/workflows/tss2master.yml

* The check whether the tools still work with the tss master will be started one time in a week.
* The test also can be started manually.

ci: Add workflow to test with tss2/master

---

Makefile.am

With slibtool this results in a failure:
```
/usr/lib/gcc/x86_64-pc-linux-musl/14/../../../../x86_64-pc-linux-musl/bin/ld: cannot find : No such file or directory
```
While GNU libtool seems to implicitly remove it.

build: remove trailing comma
