bootstrap
sapi-tools/CatSizedByteBuffer.c
sapi-tools/CopySizedBuffer.c
sapi-tools/DecryptEncrypt.c
sapi-tools/Entity.c
sapi-tools/LoadExternalHMACKey.c
sapi-tools/Makefile.am
sapi-tools/SessionHmac.c
sapi-tools/StartAuthSession.c
sapi-tools/TpmCalcPHash.c
sapi-tools/TpmHandleToName.c
sapi-tools/TpmHash.c
sapi-tools/TpmHmac.c
sapi-tools/common.cpp
sapi-tools/debug.c
sapi-tools/debug.h
sapi-tools/kdfa.c
sapi-tools/platformcommand.c
sapi-tools/sample.h
sapi-tools/syscontext.c
sapi-tools/syscontext.h

Per request by @gwei3 in #5 the solution we're pursuing is to copy the common code from the TPM2.0-TSS into the tools repo.

Copycommon

---

manual
sapi-tools/Makefile.am
sapi-tools/common.c
sapi-tools/common.h
sapi-tools/tpm2_activatecredential.cpp
sapi-tools/tpm2_akparse.cpp
sapi-tools/tpm2_getpubak.cpp
sapi-tools/tpm2_getpubek.cpp
sapi-tools/tpm2_quote.cpp

Getpubek standardize

---

Makefile.am
configure.ac

build: Check for TSS2 library @ configure time.

---

src/tpm2_sign.cpp

tpm2_sign: fix one more TPM2B size check failure

---

src/tpm2_verifysignature.cpp

tpm2_verifysignature: fix one more TPM2B failure

---

src/common.c
src/debug.c
src/debug.h

Fix build issue with TPM2.0-TSS master

---

src/tpm2_getmanufec.cpp

Fix base64 encoding in tpm2_getmanufec

---

src/tpm2_nvwrite.cpp

tpm2-nvwrite: fix for unable to write 1024B+ data

---

manual
src/tpm2_activatecredential.cpp
src/tpm2_certify.cpp
src/tpm2_create.cpp
src/tpm2_createprimary.cpp
src/tpm2_encryptdecrypt.cpp
src/tpm2_evictcontrol.cpp
src/tpm2_getmanufec.cpp
src/tpm2_getpubak.cpp
src/tpm2_getpubek.cpp
src/tpm2_hmac.cpp
src/tpm2_load.cpp
src/tpm2_nvdefine.cpp
src/tpm2_nvread.cpp
src/tpm2_nvreadlock.cpp
src/tpm2_nvrelease.cpp
src/tpm2_nvwrite.cpp
src/tpm2_quote.cpp
src/tpm2_rsadecrypt.cpp
src/tpm2_sign.cpp
src/tpm2_takeownership.cpp
src/tpm2_unseal.cpp

Add -X option to enable password input in Hex format.

Hex password

---

Android.mk

Android Make file to build both tpm2.0-tools and TPM2.0-TSS.

Android Make file

---

coding_standard_c.txt

Intorduce a coding standard and style guide for the TPM2.0-tools.

introduce coding standard

---

MAINTAINERS

MAINTAINERS: Add Bill.

---

Makefile.am
src/tpm2_getmanufec.c

port tpm2_getmanufec to use common infrastructure #151

port tpm2_getmanufec to use common infrastructure #151

---

Makefile.am
src/tpm2_takeownership.c

Align with coding standard and perform general refactoring.
Fixes 148

tpm2_takeownership: port to use comon infrastructure

---

Makefile.am
src/tpm2_getpubek.c

Refactor to be inline with coding standard.

tpm2_getpubek: port to use common infrastructure

---

Makefile.am
src/tpm2_akparse.c

tpm2_akparse: convert to use dynamic TCTI

---

Makefile.am
src/tpm2_hash.c

re-work to coding standard while here.
Fixes #155

tpm2_hash: port to use common infrastructure

---

Makefile.am
lib/tpm_hash.c
lib/tpm_hash.h
man/tpm2_createpolicy.8.in
tools/tpm2_createpolicy.c

Adding a tool to create simple assertion policies.
(PS: Cannot assign reviewers yet)

Tpm2 createpolicy

---

configure.ac

Fix some minor mistakes made in the initial commit

configure.ac: minor cleanups

---

manual

Update the manual to refelect the common options change. At some point the manual needs to be replaced with proper wiki entries.

manual: update

---

CHANGELOG

CHANGELOG: updates for 2.0

---

.travis.yml
test/system/test_tpm2_encryptdecrypt.sh

travis.yml: Switch to version 1.0 of the TSS for old resourcemanager

---

tools/tpm2_listpcrs.c

Allow TPM to tell us PCRs that are available to be read in a bank
instead of assuming there will be 24. This resolves an issue on
a system where in the bios you can choose between hash functions
(sha1 and sha256 in this case). Both will show up as supported,
but when it tries reading the bank that isn't selected in the bios
it makes no progress, and then fails saying that there are too many
PCRs to read.
This consolidates the pcr_selections init code into one function.
Also a minor change to show_pcr_values to use sizeofSelect to
determine loop iteration instead of hardcoding 24.

tpm2_listpcrs: use TPM2_GetCapability to determine PCRs to read

---

lib/options.h

This pull request contains two trivial cleanups for lib/options.h.

Cleanups for lib/options.h

---

man/tpm2_nvdefine.8.in
test/system/test_tpm2_nv.sh
tools/tpm2_nvdefine.c
tools/tpm2_nvlist.c

Adding policy authorization options for NV Index read/ write/ delete operations

Policy authorization options for NV indexes

---

lib/pcr.c
lib/pcr.h
tools/tpm2_listpcrs.c
tools/tpm2_quote.c

Switch functions to use bool instead of int return values, and add empty string checking to prevent segfault

pcr.c: Update return values to use bool and add additional error checking

---

Makefile.am
man/tpm2_createpolicy.8.in
man/tpm2_evictcontrol.8.in
tools/tpm2_dictionarylockout.c

fix whitespace errors introduced by PR #334

---

tools/main.c
tools/tpm2_createpolicy.c
tools/tpm2_getrandom.c

* Fix optind resetting
* Fix an frpintf for error output by using LOG_ERR

optind fixes

---

tools/tpm2_createpolicy.c

This pull request contains two fixes for the tpm2_createpolicy tool.

Fixes for tpm2_createpolicy tool

---

tools/main.c
tools/tpm2_dump_capability.c

gcc7: Change two case fallthrough conditions that upset gcc7.

---

RELEASE

I've changed the release process first paragraph a little bit, to make it
easier to understand.

RELEASE: Fix a typo and reword release process first paragraph

---

tools/tpm2_certify.c
tools/tpm2_create.c
tools/tpm2_createprimary.c
tools/tpm2_encryptdecrypt.c
tools/tpm2_getmanufec.c
tools/tpm2_getpubek.c
tools/tpm2_load.c
tools/tpm2_loadexternal.c
tools/tpm2_nvlist.c
tools/tpm2_quote.c

This pull request contains several fixes for tools that were reporting the exit codes backwards and also cleanups for the propagation of the error values in several tools.
While being there, they also Fixes: #197

Tools exit codes fixes and cleanups

---

.ci/0001-TSS2_Sys_LoadExternal-Fix-marshaling-error.patch
.travis.yml

See TSS Bug: https://github.com/01org/tpm2-tss/issues/496

REVERTME: workaround patch to fix build

---

test/system/test_tpm2_evictcontrol.sh
test/system/test_tpm2_loadexternal.sh

Get rid of the else clause when the if exists.

test: tpm2_evictcontrol

---

.ci/coveralls-upload.sh
.ci/travis-build-and-run-tests.sh
.travis.yml

enable coveralls

---

.ci/patches/abrmd/0001-Fix-buffer-may-be-used-uninitialized.patch
.ci/patches/abrmd/0002-tpm2-command-fix-cast-error.patch
.ci/patches/abrmd/0003-tpm2-command-fix-cast.patch
.ci/patches/abrmd/0004-travis-use-master-branch-for-tss.patch
.travis.yml

travis: patch abrmd builds against master

---

test/system/test_all.sh
test/system/test_tpm2_rc_decode.sh

test: test tpm2_rc_decode

---

.travis.yml
CHANGELOG
Makefile.am
lib/options.h
lib/tpm2_util.h
man/common/options.md
man/common/tcti.md
man/tpm2_pcrevent.8.md
test/system/test_all.sh
test/system/test_tpm2_pcrevent.sh
test/system/yaml_get.py
tools/tpm2_pcrevent.c
tools/tpm2_pcrlist.c

This is the last set of changes in #422 and thus closes it.
Fixes: #422

Tpm2 pcrevent

---

tools/tpm2_akparse.c

tpm2_akparse had bigendian conversion and file saving routines.
These duplicated the routines available in files.h, drop them
and replace with the files.h versions.

tpm2_akparse: drop duplicate routines

---

Makefile.am
tools/tpm2_akparse.c
tools/tpm2_certify.c
tools/tpm2_create.c

work-in-progress pull request to port tools to the new options infrastructure. The tests in test/system are used to check that no regressions are introduced after the port.

[WIP] port some tools to the new options parsing infra

---

Makefile.am
tools/tpm2_createpolicy.c
tools/tpm2_createprimary.c
tools/tpm2_dictionarylockout.c
tools/tpm2_dump_capability.c
tools/tpm2_encryptdecrypt.c
tools/tpm2_evictcontrol.c
tools/tpm2_getmanufec.c

This pull request ports another set of tools to the new options parsing infrastructure.

port more tools to the new options parsing infra

---

Makefile.am
tools/tpm2_getpubak.c
tools/tpm2_getpubek.c
tools/tpm2_getrandom.c
tools/tpm2_hmac.c

Here are more tools ported to the new options infrastructure.

Another batch of tools ported to the new options porting logic

---

Makefile.am
tools/tpm2_verifysignature.c

tpm2_verifysignature: port to new option handling

---

man/tpm2_getmanufec.1.md
test/system/test_tpm2_getmanufec.sh
tools/tpm2_getmanufec.c

When testing the tool I noticed that it some bugs. These commits fixes them.

Fixes for tpm2_getmanufec

---

man/tpm2_create.1.md
man/tpm2_load.1.md

This PR contain trivial fixes for the tool man pages.

Fixes for tpm2_create and tpm2_load man pages

---

Makefile.am
lib/conversion.c
lib/conversion.h
lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
man/common/pubkey.md
man/common/signature.md
man/tpm2_quote.1.md
man/tpm2_readpublic.1.md
man/tpm2_sign.1.md
test/system/test.sh
test/system/test_output_formats.sh
tools/tpm2_quote.c
tools/tpm2_readpublic.c
tools/tpm2_sign.c

Follow-up on PR #427. I don't expect this to be accepted yet, I just would like to know if this matches your expectations, before I start touching a dozen of other tools and writing documentation for it.

OpenSSL output formats and interoperability draft

---

lib/conversion.c

Since OpenSSL version 1.1.0, the RSA structure (struct rsa_st) is opaque
to programs (https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes).
So the structure members can't be accessed directly and instead helpers
functions should be used.
Because the API changes, building tpm2-tools with OpenSSL 1.1.x leads to
the following compile error:
lib/conversion.c: In function ‘tpm2_convert_pubkey_ssl’:
lib/conversion.c:126:16: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
ssl_rsa_key->e = BN_bin2bn((void*)&exponent, sizeof(exponent), NULL);
^~
make: *** [Makefile:1842: lib/conversion.o] Error 1

conversion: fix build error with OpenSSL 1.1.x

---

tools/tpm2_import.c

The ssl_RSA_set0_key() function already has an error path, but the error
was not propagated to the caller. Since the function has basically the
same signature than the OpenSSL 1.1.0 RSA_set0_key() function, define it
for OpenSSL < 1.1.0 so there is no need for the ifdefery in the caller.
Suggested-by: Matthias Gerstner <matthias.gerstner@suse.de>

tpm2_import: remove unneeded ifdefery to call the RSA_set0_key function

---

.travis.yml

This reverts commit 03f51f5fd262de6b7deb459d5f1791a39efc8568.

Revert "[REVERTME] travis: get build working"

---

man/tpm2_import.1.md
tools/tpm2_import.c

[V2] tpm2_import: add -A option to specify the object attributes

---

test/system/test_tpm2_pcrextend.sh

The list of digest values used to extend a PCR are defined by passing a
TPML_DIGEST_VALUES to TPM2_PCR_Extend. By passing a list of values, the
PCR can be extended in all the supported banks on a single TPM2 command.
Since there's no check if the algorithm ID is different for each digest
used, different digest values could be passed for the same PCR bank so a
PCR will be extended multiple times for the same hash algorithm bank.
But this isn't the preferred way to use it, as explained in the TCG spec:
"While the semantics of this command allow multiple extends to a single
PCR bank, this is not the preferred use and the limit on the number of
entries in the list make this use somewhat impractical."
Also, the number of banks will vary depending of the hash algorithms that
are supported by …

test: don't extend a PCR with more digest values than supported banks

---

man/tpm2_nvread.1.md
man/tpm2_nvwrite.1.md
test/system/test_tpm2_nv.sh
tools/tpm2_nvread.c
tools/tpm2_nvwrite.c

Adds PCR policy support for nv read and write operations.
Fixes: #348

Nv cleanups

---

man/tpm2_pcrlist.1.md
test/system/test_tpm2_pcrextend.sh
tools/tpm2_create.c
tools/tpm2_createprimary.c
tools/tpm2_nvwrite.c

This pull request contains some trivial fixes I noticed when doing review in preparation for the upcoming 3.X release.

Trivial fixes for 3.X

---

man/tpm2_pcrlist.1.md
test/system/test_tpm2_pcrextend.sh
tools/tpm2_create.c
tools/tpm2_nvwrite.c

These are the same trivial fixes that are in PR #619, but against the master branch instead.

Trivial fixes

---

tools/tpm2_nvlist.c

This PR has commits for:
* Fixing a BE to host endian conversion
* tpm2_nvlist: output in yaml format
* changelog update

tpm2_nvlist: yaml output support

---

Makefile.am
test/unit/test_tpm2_errata.c

master-add unit tests for tpm2_errata

---

lib/tpm2_options.c

This pull request contains some simple cleanups for the option handling code.

Options handling cleanups

---

.travis.yml

This is just the 3.X version of PR #701 to fix the Travis CI build.

[for 3.x] Fix Travis CI build

---

.ci/patches/abrmd/0001-tcti-handle-NULL-conf-properly.patch

[REVERTME] abrmd: patch for tcti init

---

tools/tpm2_createprimary.c

Run the code formatter and stylize code in a way consistent
with the coding standard.

tpm2_createprimary: code cleanups

---

lib/tpm2_options.c
lib/tpm2_tcti_ldr.c

Fix tcti init

---

lib/tpm2_options.c
man/tpm2_rc_decode.1.md

This is an alternative pull request for PR #905.

[v2] tcti option cleanups

---

.ci/docker.run
lib/tpm2_attr_util.c
test/unit/test_tpm2_attr_util.c
tools/tpm2_getcap.c

tss2: Account for changes TPMA_* macros in upstream headers.

---

MAINTAINERS.md

This commit also removes Jimmy who hasn't been active for some time.

MAINTAINERS.md: Remove myself, add Joshua and Javier.

---

man/tpm2_create.1.md
man/tpm2_createak.1.md
man/tpm2_createek.1.md
man/tpm2_evictcontrol.1.md

This small series includes corrections to what I believe are errors/typos in several manual pages.

Various man page fixes

---

man/common/options.md
man/tpm2_createak.1.md
man/tpm2_dictionarylockout.1.md
man/tpm2_encryptdecrypt.1.md
man/tpm2_nvreadlock.1.md
man/tpm2_nvwrite.1.md
man/tpm2_unseal.1.md

Fixes up various things that caught my eye whilst skimming the man pages recently.

More man page tweaks

---

.ci/docker.run

Add scan-build Static Code Analysis to Travis

---

.ci/docker.run

This reverts commit 53882c15af007a8f37951fb393656c556070f79c.

Revert "Add scan-build Static Code Analysis to Travis"

---

tools/tpm2_import.c

Since OpenSSL version 1.1.0, the RSA structure (struct rsa_st) is opaque
to programs (https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes).
So the structure members can't be accessed directly and instead helpers
functions should be used.
Because the API changes, building tpm2-tools with OpenSSL 1.1.x leads to
the following compile error:
CC       tools/tpm2_import.o
In file included from tools/tpm2_import.c:39:
tools/tpm2_import.c: In function ‘load_rsa_key’:
tools/tpm2_import.c:684:36: error: dereferencing pointer to incomplete type ‘RSA’ {aka ‘struct rsa_st’}
int priv_bytes = BN_num_bytes(k->p);
^~
make: *** [Makefile:1982: tools/tpm2_import.o] Error 1
Fixes: d53fcf9b9264 ("tpm2_import: import from pem file")

tpm2_import: Allow to build with OpenSSL 1.1.0

---

test/integration/helpers.sh

Currently, the integration tests can't only be run either against in the
following configurations:
1) tpm2-abrmd + TPM simulator
2) the TPM simulator directly
But this doesn't cover some configurations that were previously supported:
3) tpm2-abrmd + the default TPM device (/dev/tpm0)
4) tpm2-abrmd + a TPM device that's not the default (i.e: /dev/tpm1)
5) a TPM device directly (i.e: /dev/tpmrm0)
This patch allows the integration tests to be run using all the possible
configurations, by setting TPM2_* environment variables instead of the
(unused) no-abrmd option.
For example:
1) $ TPM2_ABRMD=/path/to/tpm2-abrmd TPM2_SIM=/path/to/tpm_server ./tests/pcrlist.sh
2) $ TPM2_SIM=/path/to/tpm_server ./tests/pcrlist.sh
3) $ TPM2_ABRMD=/path/to/tpm2-abrmd ./tests/pcrlist.sh
4) $ …

tests: Allow to run the integration tests using a real TPM device

---

CHANGELOG.md
man/tpm2_nvdefine.1.md
man/tpm2_nvread.1.md
tools/tpm2_nvdefine.c

following the previous PR tpm2-software#970

Master changelog update

---

CHANGELOG.md
man/tpm2_verifysignature.1.md
scripts/utils/analyze.py
test/integration/tests/import.sh
tools/tpm2_verifysignature.c

This reverts commit d8d87a3876ecab882ec1986cf24f31eda792c45f.

Revert "tpm2_verifysignature: -f/--format becomes -i/--input-format"

---

lib/tpm2_util.c

Add the scheme, exponent, keysize and symmetric details to the YAML
output.

util: add more RSA information to YAML output

---

man/tpm2_import.1.md
man/tpm2_print.1.md

Minor formatting changes to man pages in order to make them more consistent with the style of our other manual pages.

Minor man page tweaks

---

test/integration/helpers.sh
test/integration/tests/createprimary.sh

Restore functionality of these tests.

tests: fix create.sh and createprimary.sh

---

CHANGELOG.md
lib/tpm2_openssl.c
lib/tpm2_openssl.h
man/tpm2_import.1.md
test/integration/tests/import.sh
tools/tpm2_import.c

When closed, make sure to twiddle task list items in: https://github.com/tpm2-software/tpm2-tools/issues/1079

support configurable parents and fix EVP issues between OSSL versions

---

CHANGELOG.md
man/tpm2_create.1.md
man/tpm2_createprimary.1.md
test/system/test_tpm2_unseal.sh
tools/tpm2_create.c

This pull-request contains a couple of fixes from the 3.X branch that should make to the 3.0.X branch. These will be included in an upcoming 3.0.5 release.

Fixes for upcoming 3.0.5 release

---

lib/tpm2_openssl.c
man/tpm2_import.1.md
test/integration/tests/import.sh
tools/tpm2_import.c

To support ECC, refactor the internals of tpm2_import to leverage the
work done on tpm2_loadexternal. Add tests, and document in the
manpage.

tpm2_import: support ECC

---

.ci/docker.run

travis: fix dbus address in use

---

lib/tpm2_capability.c

Add additional calls to Tss2_Sys_GetCapability when moreData is available.
Additional data is appended into the result capability data after each read out.
Closes #1150

Add support for moreData on GetCapability

---

INSTALL.md

Small change for INSTALL documentation

Use https for 'cloning' git repo

---

Makefile.am
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_policyor.1.md
scripts/utils/analyze.py
test/integration/tests/tcti/abrmd/policyor.sh
tools/tpm2_policyor.c

New tool to compound (OR) policies
Closes #863

tpm2_policyor: add tool

---

test/integration/tests/print.sh

A test to verify tpm2_print works with
TPMS_ATTEST quote files.
Signed-off-by: Haris Okanovic <haris.okanovic@ni.com>

test/integration/tests/print.sh: Add

---

tools/tpm2_getmanufec.c

Fix the following reported error:
```
In file included from tools/tpm2_getmanufec.c:42:0:
tools/tpm2_getmanufec.c: In function ‘Base64Encode’:
/home/travis/build/AndreasFuchsSIT/tpm2-tss-engine/tpm2-tools/../installdir/usr/local/include/openssl/bio.h:596:34: error: value computed is not used [-Werror=unused-value]
^
tools/tpm2_getmanufec.c:290:5: note: in expansion of macro ‘BIO_flush’
BIO_flush(bio);
^
/home/travis/build/AndreasFuchsSIT/tpm2-tss-engine/tpm2-tools/../installdir/usr/local/include/openssl/bio.h:589:34: error: value computed is not used [-Werror=unused-value]
^
tools/tpm2_getmanufec.c:292:5: note: in expansion of macro ‘BIO_set_close’
BIO_set_close(bio, BIO_NOCLOSE);
^
cc1: all warnings being treated as errors
make: *** [tools/tpm2_getmanufec.o] Error 1
make: *** Waiting for …
```

tpm2_getmanufc: fix OSSL build warnings

---

man/tpm2_activatecredential.1.md
man/tpm2_certify.1.md
man/tpm2_create.1.md
man/tpm2_createak.1.md
man/tpm2_createek.1.md
man/tpm2_encryptdecrypt.1.md
man/tpm2_evictcontrol.1.md
man/tpm2_flushcontext.1.md
man/tpm2_hmac.1.md
man/tpm2_import.1.md
man/tpm2_load.1.md
man/tpm2_quote.1.md
man/tpm2_readpublic.1.md
man/tpm2_rsadecrypt.1.md
man/tpm2_rsaencrypt.1.md
man/tpm2_sign.1.md
man/tpm2_unseal.1.md
man/tpm2_verifysignature.1.md

Change commmon/ctxobj.md to common/ctxobj.md

man: fix typo

---

man/tpm2_import.1.md
tools/tpm2_import.c

Created a new PR hope fully with no merge conflicts

Parent key auth and key auth support added to tpm2_import

---

man/tpm2_changeauth.1.md
tools/tpm2_changeauth.c

tpm2_changeauth: Augmenting tool with capabilities to handle auths for loadable handles and NV

---

lib/tpm2_hash.c

Fix for issue #1247 "Compile fails in tpm2_hash.c"

---

lib/files.c

There is no `fmemopen`, `open_memstream`, or equivalent functionality on QNX.
Changes to function `files_load_bytes_from_buffer_or_file_or_stdin`:
*   Modified code path for non-null `input_buffer` argument to use memcpy
instead.
*   Just use `files_load_bytes_from_path` when the `path` argument is non-NULL.
*   Use `read_bytes_from_file` and `fread` as before for `stdin`.
Signed-off-by: Safayet Ahmed <safayet.ahmed@ge.com>

lib/files.c: replace fmemopen call for QNX build

---

tools/tpm2_quote.c

change optarg value compare from tpm2_alg_util_flags_sig to tpm2_alg_util_flags_hash

fixed support option -G 'sha256'

---

lib/tpm2_convert.c
lib/tpm2_openssl.c
lib/tpm2_openssl.h
tools/tpm2_import.c

Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

build: fixup  libressl support and add libressl-2.7

---

RELEASE.md

I often forget the process, so rather than having to comb this
entire file each time I've summarised the contents into a step-by-step
release checklist for maintainers to follow when preparing a release.

RELEASE: add a release checklist

---

test/integration/tests/changeauth.sh
tools/tpm2_changeauth.c

Test that changing the authvalue on an object works.

tests/changeauth: test changeauth on object

---

tools/tpm2_createek.c

In the latest version of tpm2_createek, it appears that saving the context for non-persistent handles is not targeting the correct variable.  
According to the documentation, the "-c" option, which sets `ctx.ctx_obj.path`, specifies the context output file to use or "ek.ctx" if none is given.  The current implementation, however, will use `ctx.out_file_path` (set by "-p") which is supposed to be the public key output file.  This PR is designed to correct this.

Bugfix: tpm2_createek tool auto-save context used incorrect path

---

man/tpm2_activatecredential.1.md
man/tpm2_certify.1.md
man/tpm2_changeauth.1.md
man/tpm2_checkquote.1.md
man/tpm2_clear.1.md
man/tpm2_clearlock.1.md
man/tpm2_create.1.md
man/tpm2_createprimary.1.md
man/tpm2_encryptdecrypt.1.md
man/tpm2_evictcontrol.1.md
man/tpm2_getmanufec.1.md
man/tpm2_hmac.1.md
man/tpm2_load.1.md
man/tpm2_loadexternal.1.md
man/tpm2_nvdefine.1.md
man/tpm2_nvread.1.md
man/tpm2_nvreadlock.1.md
man/tpm2_nvrelease.1.md
man/tpm2_rsadecrypt.1.md
man/tpm2_sign.1.md
man/tpm2_verifysignature.1.md

Signed-off-by: Nicolas Oliver <dario.n.oliver@intel.com>

man: update common references to authorizations.md

---

man/tpm2_readpublic.1.md
tools/tpm2_readpublic.c

tools/tpm2_readpublic: Add option -n for saving object name
man/tpm2_readpublic.1.md: add description for option -n
Signed-off-by: Hui Li <leehui_hrbeu71102@163.com>

tools/tpm2_readpublic: add new option

---

Makefile.am
lib/tpm2_policy.c
lib/tpm2_policy.h
lib/tpm2_util.c
lib/tpm2_util.h
man/tpm2_policyduplicationselect.1.md
man/tpm2_policylocality.1.md
scripts/utils/analyze.py
tools/tpm2_policyduplicationselect.c
tools/tpm2_policylocality.c

tools/tpm2_policylocality: add tool and its man page
tools/tpm2_policyduplicationselect: add tool and its man page
lib: add supporting function for newly added tools
Fixes: #1286

add new tools and their supporting functions:

---

Makefile.am

see https://www.gnu.org/software/automake/manual/html_node/Default-_005fSOURCES.html.

Makefile.am: remove redundant test_unit_…_SOURCES

---

man/tpm2_getcap.1.md
tools/tpm2_getcap.c

Add the capability for querying allocated PCRs
Signed-off-by: Andreas Fuchs <andreas.fuchs@sit.fraunhofer.de>

GetCap: Add CAP_PCRS

---

MAINTAINERS.md

I'm moving on and don't know that I will have time to commit to the
project, therefore remove myself from the maintainers list.

MAINTAINERS: remove myself as project maintainer

---

lib/pcr.c
lib/pcr.h
man/tpm2_pcrlist.1.md
man/tpm2_quote.1.md

A bunch of fixes related to hardcoded values for PCR selections and bank algorithms.

Multiple fixes on PCR / Algorithms banks in lib/pcr.c

---

test/integration/helpers.sh

- Fixed syntax on `start_up`
- Fixed multiple coding style warnings (shellcheck)
- Added shebang
- Fixed tabs issues
- Added a check in `shut_down` to prevent `kill` to fail if the process has already been killed

test/integration: Several fixes to helpers.sh file

---

test/integration/tests/changeauth.sh

Add missing cleanup to test changeauth.sh

---

lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
man/tpm2_rsadecrypt.1.md
man/tpm2_rsaencrypt.1.md
test/integration/tests/rsadecrypt.sh
tools/tpm2_rsadecrypt.c
tools/tpm2_rsaencrypt.c

Extend tpm2_rsaencrypt & tpm2_rsadecrypt to support setting the padding scheme

tpm2_rsaencrypt|decrypt #1159

---

lib/tpm2_identity_util.c

Someone had finger trouble during a refactoring ... ? 
Signed-off-by: GlovePuppet <touched.by.his.noodley.appendage@gmail.com>

tools\tpm2_import - Bug fix

---

man/tpm2_create.1.md

Change common/object-attrs.md to common/obj-attrs.md

man: Fix typo link

---

lib/tpm2_session.c
test/integration/tests/createprimary.sh

Fixes the issue and adds a test

sessions: Fix for self created sessions' leak

---

test/system/test.sh

This reverts commit 2f82b93356e45024759e318e7026a1489b543c21.
Fixes: #1179

Revert "test.sh: test for lefotver obejcts in-between tests"

---

Makefile.am
test/integration/tests/tcti/abrmd/policysecret.sh

Fix policysecret integration test and revert it from XFAIL list

---

man/tpm2_takeownership.1.md
tools/tpm2_takeownership.c

Add platform hierarchy support and change typo in tpm2_takeownership.1.md.

Add platform hierarchy support on 3.X

---

man/tpm2_create.1.md
man/tpm2_dictionarylockout.1.md
man/tpm2_encryptdecrypt.1.md
man/tpm2_getmanufec.1.md
man/tpm2_nvdefine.1.md
man/tpm2_nvread.1.md
man/tpm2_takeownership.1.md
tools/tpm2_hash.c
tools/tpm2_loadexternal.c
tools/tpm2_nvdefine.c
tools/tpm2_nvreadlock.c
tools/tpm2_quote.c

Refer #1042 minor change for man page and tools.

Audit manpage to tools

---

man/tpm2_clearcontrol.1.md
test/integration/tests/clearcontrol.sh
tools/tpm2_clearcontrol.c

Change clear control tool options to accurately reflect spec language

---

test/integration/tests/incrementalselftest.sh

Fix test incrementalselftest.sh

---

test/integration/helpers.sh

Make helpers.sh python version (2 and 3) independent

---

test/integration/tests/incrementalselftest.sh

Rework test incrementalselftest.sh

---

lib/files.c
lib/files.h
lib/tpm2.c
lib/tpm2.h
lib/tpm2_auth_util.c
lib/tpm2_capability.c
lib/tpm2_capability.h
lib/tpm2_errata.c
lib/tpm2_session.c
lib/tpm2_session.h
test/unit/test_tpm2_auth_util.c
test/unit/test_tpm2_policy.c
test/unit/test_tpm2_session.c
tools/tpm2_activatecredential.c
tools/tpm2_createak.c
tools/tpm2_createek.c
tools/tpm2_createpolicy.c
tools/tpm2_evictcontrol.c
tools/tpm2_flushcontext.c
tools/tpm2_getcap.c
tools/tpm2_getmanufec.c
tools/tpm2_getrandom.c
tools/tpm2_listpersistent.c
tools/tpm2_policyrestart.c
tools/tpm2_readpublic.c
tools/tpm2_startauthsession.c

This finalizes the tpm calls in files.c

continued work on exit codes

---

lib/files.h
lib/tpm2.c
lib/tpm2.h
lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
lib/tpm2_auth_util.c
lib/tpm2_hierarchy.c
lib/tpm2_hierarchy.h
lib/tpm2_policy.c
lib/tpm2_policy.h
test/unit/test_tpm2_policy.c
tools/tpm2_createek.c
tools/tpm2_createpolicy.c
tools/tpm2_createprimary.c
tools/tpm2_policyauthorize.c
tools/tpm2_policycommandcode.c
tools/tpm2_policyduplicationselect.c
tools/tpm2_policylocality.c
tools/tpm2_policyor.c
tools/tpm2_policypassword.c
tools/tpm2_policypcr.c
tools/tpm2_policysecret.c
tools/tpm2_quote.c
tools/tpm2_sign.c

More progress on exit codes, progresses #1193

more progress on exit-codes

---

lib/tpm2_auth_util.c
tools/tpm2_clear.c
tools/tpm2_clearcontrol.c
tools/tpm2_create.c
tools/tpm2_createak.c
tools/tpm2_createek.c
tools/tpm2_createprimary.c
tools/tpm2_dictionarylockout.c
tools/tpm2_duplicate.c
tools/tpm2_encryptdecrypt.c
tools/tpm2_getmanufec.c
tools/tpm2_hmac.c
tools/tpm2_import.c
tools/tpm2_loadexternal.c
tools/tpm2_nvdefine.c
tools/tpm2_nvincrement.c
tools/tpm2_nvread.c
tools/tpm2_nvreadlock.c
tools/tpm2_nvrelease.c
tools/tpm2_nvwrite.c
tools/tpm2_pcrevent.c
tools/tpm2_quote.c
tools/tpm2_sign.c
tools/tpm2_unseal.c

Fix for tools printing auth values to stderr on failed auth attempts

---

Makefile.am
lib/tpm2_options.c
lib/tpm2_options.h
lib/tpm2_tcti_ldr.c
lib/tpm2_util.c
lib/tpm2_util.h
test/unit/test_options.c
tools/tpm2_createek.c

Test some of the options and env parameters.

option tests

---

bootstrap

Came up with 9381559b055b4b7e12a10aa4bcf65586f5571755

Remove dead code in bootstrap

---

test/integration/helpers.sh

The tests before made some asumptions about the environment in which
they were started, allow finer grained control of testing environment
for those wishing to use the test harness out of the automake
environment. This can be configured through:
TPM2_SIM: the simulator executable, or none to not use a simulator.
TPM2_SIMPORT: the port to use for the simulator, or none to autopick.
TPM2_ABRMD: the abrmd executable, or none to not use an RM.
TPM2ABRMD_TCTI: the abrmd tcti to use, or none to use simulator port.
TPM2TOOLS_TEST_TCTI: is specified it is the TCTI for the tools to use,
or autopick based on:
- if abrmd was started use it.
- if abrmd was not started use simulator.
- if neither was specified it's an error. Do not default to device,
we don't generally want to run test scripts at …

test: control setting which TCTI tests run to

---

test/integration/tests/import_tpm.sh

import_tpm.sh: Add missing license to the file

---

CHANGELOG.md
man/tpm2_createak.1.md
test/integration/tests/activecredential.sh
test/integration/tests/attestation.sh
test/integration/tests/checkquote.sh
test/integration/tests/createak.sh
test/integration/tests/makecredential.sh
test/integration/tests/output_formats.sh
test/integration/tests/print.sh
test/integration/tests/quote.sh
tools/tpm2_createak.c

Create ak option changes

---

tools/misc/tpm2_checkquote.c

They didn't make any sense or offer any real value.
Progresses: #1042

tpm2_checkquote: remove stdout outputs

---

LICENSE
misc/coding_standard_c.txt

LICENSE: retain copyrights in license file

---

CHANGELOG.md
man/tpm2_nvincrement.1.md
test/integration/tests/nvinc.sh
tools/tpm2_nvincrement.c

Progresses #1042
Update short option for specifying hierarchy auth from -a to -C.

tpm2_nvincrement: Update short option

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
man/tpm2_hierarchycontrol.1.md
scripts/utils/analyze.py
test/integration/tests/hierarchycontrol.sh
tools/tpm2_hierarchycontrol.c

tools/tpm2_hierarchycontrol: add tool and its man page
lib: add supporting function for newly added tools

tools/tpm2_hierarchycontrol: add new tool and man page

---

test/integration/tests/attestation.sh

For quoting, 20 random bytes are needed. However, the conversion of these random bytes into a hex stream is done two times, first with `--hex` (introduced with 460afc31) and then by calling `xxd`. This results in 80 characters (representing 40 bytes) which is not what we want.
With `tpm2_getrandom`'s internal conversion into a hex stream, the call of `xxd` should be ommitted.

test: remove external hex conversion of random bytes

---

test/integration/tests/attestation.sh

Reverts tpm2-software/tpm2-tools#1609

Revert "test: remove external hex conversion of random bytes"

---

man/tpm2_policyor.1.md

tpm2_policyor.1.md: Update example

---

CHANGELOG.md
man/tpm2_makecredential.1.md
tools/tpm2_makecredential.c

tpm2_makecredential: Long option output changed to credential-blob

---

tools/tpm2_certify.c
tools/tpm2_clear.c
tools/tpm2_createpolicy.c
tools/tpm2_nvdefine.c
tools/tpm2_pcrallocate.c

Error handling and random fixes

---

CHANGELOG.md
lib/tpm2_policy.c
man/tpm2_policyduplicationselect.1.md
test/integration/tests/abrmd_policyduplicationselect.sh
tools/tpm2_policyduplicationselect.c

Fixes #1629 
- Add a failing scenario to the test script
- Add a test script
- Add end to end example in the man page
- Fixed and issue where specifying object name should be optional.
- Fixed a session handling bug in the tool

Policy duplication select

---

CHANGELOG.md

CHANGELOG: audit through to tpm2_nvdefine

---

CHANGELOG.md
man/tpm2_rsadecrypt.1.md
man/tpm2_rsaencrypt.1.md
test/integration/tests/rsadecrypt.sh
tools/tpm2_rsadecrypt.c
tools/tpm2_rsaencrypt.c

Update change information
- tpm2_verifysignature
- tpm2_unseal
- tpm2_startauthsession
- tpm2_sign
- tpm2_createpolicy
- tpm2_nvdefine
- tpm2_nvreadlock
- tpm2_nvincrement
- tpm2_nvlist
- tpm2_nvread
- tpm2_nvwrite
- tpm2_nvrelease
- tpm2_pcrevent
- tpm2_pcrlist
- tpm2_pcrread
- tpm2_print
- tpm2_policyauthorize
- tpm2_policycommandcode
- tpm2_policyduplicationselect
- tpm2_policylocality
- tpm2_policypcr
- tpm2_policyor
- tpm2_policypassword
- tpm2_policysecret
- tpm2_quote
- tpm2_readpublic
- tpm2_rsaencrypt
- tpm2_rsadecrypt

CHANGELOG.md: Update information on tool changes

---

man/tpm2_activatecredential.1.md

Fixes #1662
Add an end to end example of how to activate credential.

tpm2_activatecredential.1.md: Update example section

---

tools/tpm2_getekcertificate.c

I tested on my Intel NUC (using PTT) that these commands successfully fetch certificates for both EKs:
```
$ tpm2_createek -G rsa -c rsa-ek.ctx -u rsa-ek.pub
$ tpm2_getekcertificate -u rsa-ek.pub -o rsa-ek.json https://ekop.intel.com/ekcertservice/
$ cat rsa-ek.json | jq -r .certificate | sed -e 's/%3D/=/g' | tr '_-' '/+' | fold -w40 | openssl base64 -d > rsa-ek.crt
$ openssl x509 -inform DER -in rsa-ek.crt -noout -text
$ tpm2_createek -G ecc -c ecc-ek.ctx -u ecc-ek.pub
$ tpm2_getekcertificate -u ecc-ek.pub -o ecc-ek.json https://ekop.intel.com/ekcertservice/
$ cat ecc-ek.json | jq -r .certificate | sed -e 's/%3D/=/g' | tr '_-' '/+' | fold -w40 | openssl base64 -d > ecc-ek.crt
$ openssl x509 -inform DER -in ecc-ek.crt -noout -text
```
I can add a test case if someone is willing to donate …

tpm2_getekcertificate: support ECC keys

---

man/tpm2_changeauth.1.md
man/tpm2_duplicate.1.md
man/tpm2_policycommandcode.1.md

tpm2_policycommand code inputs were updated but the examples were left behind, update them all.

man: update tpm2_policycommandcode examples

---

RELEASE.md

Make the checklist more thorough to help prevent release issues.
On tpm2-tools 4.0-rc1, the tag was uploaded but the commit was
not pushed to the release branch (master). This for RC2 we had
to merge RC1 into the master prior to the tag.

RELEASE: Update checklist

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
man/tpm2_policyauthorizenv.1.md
test/integration/tests/abrmd_policyauthorizenv.sh
tools/tpm2_policyauthorizenv.c

Fixes #855 
Add new tool: TPM2_CC_PolicyAuthorizeNV

Add tool tpm2_policyauthorizenv

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
man/tpm2_readclock.1.md
man/tpm2_shutdown.1.md
test/integration/tests/readclock.sh
test/integration/tests/startup.sh
tools/tpm2_readclock.c
tools/tpm2_shutdown.c

Fixes #870 
Fixes #874 
Implement:
1. tpm2_readclock
2. tpm2_shutdown
Authored by @williamcroberts. Replaces PR #1693

Introduce new commands

---

CHANGELOG.md
man/tpm2_nvdefine.1.md
test/integration/tests/nv.sh
tools/tpm2_nvdefine.c

- code cleanup.
- default attribute set.
- find free indices when index is not specified.

nv define enhancements

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
man/tpm2_policynv.1.md
test/integration/tests/abrmd_policynv.sh
tools/tpm2_policynv.c

Add new policy tool for command tpm2_Policynv

---

tools/tpm2_policycommandcode.c

tpm2_policycommandcode.c: Remove unused variable

---

lib/tpm2_alg_util.c
tools/misc/tpm2_checkquote.c
tools/tpm2_send.c

Coverity report can be found here:
https://scan.coverity.com/projects/01org-tpm2-0-tools?tab=overview

Coverity fixes

---

tools/tpm2_policypassword.c

tpm2_policypassword.c: Remove unused variable

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_policynvwritten.1.md
test/integration/tests/abrmd_policynvwritten.sh
tools/tpm2_policynvwritten.c

Add tool tpm2_policynvwritten

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_policyauthvalue.1.md
test/integration/tests/abrmd_policyauthvalue.sh
tools/tpm2_policyauthvalue.c

Add new tool tpm2_policyauthvalue

---

lib/tpm2_openssl.c

When reading an ECC key from a PEM file, one of it's parameters (private scalar, public coordinates x and y) can start with leading zero bytes. The `BN_num_bytes()` returns the bytes required to store such a parameter, e.g. for a `prime256v1` curve 31 bytes instead of 32 bytes if the parameter starts with `0x00`.
Additionally, `BN_bn2bin()` does not pad the parameter to its expected size which can lead to problems in the TPM. Hence, the key sizes need to be calculated properly and the ECC params padded.
Fixes #1759

lib/openssl: pad ECC key params

---

CHANGELOG.md
Makefile.am
lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_policyticket.1.md
test/integration/tests/abrmd_policyticket.sh
tools/tpm2_policyticket.c

Policyticket

---

CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_policysecret.1.md
test/integration/tests/abrmd_policysecret.sh
test/integration/tests/abrmd_policyticket.sh
tools/tpm2_policysecret.c

tpm2_policysecret: Add tool options for specifying
- \--expiration or -t
- \--ticket
- \--timeout
- \--nonce-tpm or -x
- \--qualification or -q

Policysecretadditions

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
man/tpm2_changeeps.1.md
test/integration/tests/changeeps.sh
tools/tpm2_changeeps.c

tpm2_changeeps: Add tool to enable command TPM2_ChangeEPS

---

CHANGELOG.md
Makefile.am
lib/tpm2.c
lib/tpm2.h
lib/tpm2_util.c
lib/tpm2_util.h
man/tpm2_clockrateadjust.1.md
man/tpm2_setclock.1.md
test/integration/tests/clockrateadjust.sh
test/integration/tests/setclock.sh
tools/tpm2_clockrateadjust.c
tools/tpm2_setclock.c

Add:
- Changelog entry for tpm2_readclock
- tpm2_setclock
- tpm2_clockrateadjust

tpm2_setclock: add new tool

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvcertify.1.md
test/integration/tests/nvcertify.sh
tools/tpm2_nvcertify.c

tpm2_nvcertify: Add tool to enable command TPM2_NV_Certify

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
man/tpm2_changepps.1.md
test/integration/tests/changepps.sh
tools/tpm2_changepps.c

tpm2_changepps: Add new tool to enable command TPM2_ChangePPS

---

man/tpm2_create.1.md
test/integration/tests/certifycreation.sh
test/integration/tests/create.sh
tools/tpm2_create.c

Add options for specifying data for certification

tpm2_create changes for key certification

---

CHANGELOG.md
Makefile.am
lib/tpm2.c
lib/tpm2.h
lib/tpm2_util.c
lib/tpm2_util.h
man/tpm2_gettime.1.md
test/integration/tests/gettime.sh
tools/tpm2_gettime.c
tools/tpm2_readclock.c

tpm2_gettime: add tool to get attested time

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_policynamehash.1.md
test/integration/tests/abrmd_policynamehash.sh
tools/tpm2_policyauthorize.c
tools/tpm2_policynamehash.c

tpm2_policynamehash: Add tool to enable policy command TPM2_PolicyNameHash

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
man/tpm2_policycountertimer.1.md
test/integration/tests/abrmd_policycountertimer.sh
tools/tpm2_policycountertimer.c

tpm2_policycountertimer: Add tool to enable command TPM2_PolicyCountertimer

---

tools/tpm2_listpersistent.c

tpm2_listpersistent: update to build against master

---

CHANGELOG.md
lib/tpm2_policy.c
lib/tpm2_policy.h
lib/tpm2_util.c
lib/tpm2_util.h
man/tpm2_policysecret.1.md
man/tpm2_policysigned.1.md
man/tpm2_startauthsession.1.md
test/integration/tests/abrmd_policysigned.sh
test/integration/tests/abrmd_policyticket.sh
tools/tpm2_policysecret.c
tools/tpm2_policysigned.c
tools/tpm2_startauthsession.c

Refactor nonce tpm

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_create.1.md
man/tpm2_createprimary.1.md
man/tpm2_policytemplate.1.md
test/integration/tests/abrmd_policytemplate.sh
tools/tpm2_create.c
tools/tpm2_createprimary.c
tools/tpm2_policytemplate.c

tpm2_policytemplate: Add tool to enable policy command TPM2_PolicyTemplate

---

CHANGELOG.md

CHANGELOG.md: update changelog

---

.ci/download-deps.sh

travis: bump abrmd version 2.3.0-rc0

---

CHANGELOG.md

CHANGELOG.md: Update information on 4.0.1 and 3.2.1 releases

---

lib/pcr.c
test/unit/test_pcr.c

pcr.c: Fix buffer length issue to support all defined hash algorithm

---

lib/tpm2_util.c

tpm2_util.c: Fix an issue int variable size was checked against uint

---

.ci/download-deps.sh

travis: bump abrmd version 2.3.0

---

CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
test/integration/tests/nv.sh
tools/tpm2_nvreadpublic.c

Get the name hash and output with the index information.

tpm2_nvreadpublic: add name output

---

lib/tpm2_alg_util.h
man/tpm2_pcrextend.1.md

Signed-off-by: Nicolas Oliver <nicolasoliver03@gmail.com>

tpm2_pcrextend,tpm2_alg_util: fix sha1 examples

---

lib/tpm2_hash.c

Fix issue https://github.com/tpm2-software/tpm2-tools/issues/1744

Fix compile issue #1744.

---

lib/pcr.c

the "sizeof" get the BYTES of the "pcrs->pcr_values". but it just need the COUNT(or LENGTH) of the "pcrs->pcr_values" to determine whether the result's count is too much or not.

modify lib/pcr.c, replace sizeof with ARRAY_LEN

---

man/tpm2_createak.1.md

Signed-off-by: a.lieb@peak-system.com <a.lieb@peak-system.com>

corrected man page

---

man/tpm2_createek.1.md
tools/tpm2_createek.c

tpm2_createek: fixed tool option "template" to indicate no arguments are needed

---

tools/tpm2_hierarchycontrol.c

tpm2_hierarchycontrol: Fixed bug where hierarchycontrol operation failed silently

---

lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_policyauthorizenv.1.md
man/tpm2_policysecret.1.md
test/integration/tests/abrmd_policycphash.sh
test/integration/tests/abrmd_policysecret.sh
tools/tpm2_policyauthorizenv.c
tools/tpm2_policynv.c
tools/tpm2_policysecret.c

TPM2_CC_PolicyCpHash

---

man/tpm2_checkquote.1.md

Signed-off-by: Toru Tomita <toru.tomita@gmail.com>

Fix option typo

---

lib/tpm2.c
lib/tpm2.h
man/tpm2_clearcontrol.1.md
man/tpm2_clockrateadjust.1.md
man/tpm2_dictionarylockout.1.md
man/tpm2_evictcontrol.1.md
man/tpm2_setclock.1.md
test/integration/tests/abrmd_policycphash.sh
tools/tpm2_clearcontrol.c
tools/tpm2_clockrateadjust.c
tools/tpm2_dictionarylockout.c
tools/tpm2_evictcontrol.c
tools/tpm2_setclock.c

Add an option to output cpHash for the command

---

lib/tpm2.c
lib/tpm2.h
man/tpm2_clear.1.md
test/integration/tests/abrmd_policycphash.sh
tools/tpm2_clear.c

TPM2_CC_PolicyCpHash for tpm2_clear

---

lib/tpm2.c
lib/tpm2.h
man/tpm2_encryptdecrypt.1.md
man/tpm2_hmac.1.md
man/tpm2_nvread.1.md
man/tpm2_nvwrite.1.md
test/integration/tests/abrmd_policycphash.sh
tools/tpm2_encryptdecrypt.c
tools/tpm2_hmac.c
tools/tpm2_nvwrite.c

Add cphash

---

lib/tpm2_policy.c

tpm2_policy.c: restrict policy digest size

---

configure.ac

Configure: Add test dependency expect

---

test/integration/tests/getekcertificate.sh

getekcertificate.sh: Add a test for ECC based endorsement certificate

---

doc/CHANGELOG.md

doc/CHANGELOG.md: CHANGELOG: Update to 4.2-RC1

---

doc/CHANGELOG.md

* Fix various issues reported by static analysis tools.
* Add integration test for ECC based getekcertificate.
* Fix for issue #1959 where ARM builds were failing.
* Add a check in autotools to add "expect" as a package dependency for fapi tools.
* tpm2_createek: Drop the unused -p or --ek-auth option
* tpm2_policyor: List of policy files should be specified as an argument
instead of -l option. The -l option is still retained for backwards
compatibility. See issue#1894.
* tpm2\_eventlog: add a tool for parsing and displaying the event log.
* tpm2_createek: Fix an issue where the `template` option looked for args
* tpm2_hierarchycontrol: Fixed bug where tool operation failed silently
* tpm2_nvdefine: Fixed an issue where text output suggested failures as passes
* tpm2_certify: Add an …

doc/CHANGELOG.md: Update to tpm2-tools v4.2

---

.ci/travis.run

ci: update coverity run conditions

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
man/tpm2_getcommandauditdigest.1.md
man/tpm2_setcommandauditstatus.1.md
test/integration/tests/commandaudit.sh
tools/tpm2_getcommandauditdigest.c
tools/tpm2_setcommandauditstatus.c

Command Audit Tools

---

Makefile.am
lib/tpm2.c
lib/tpm2.h
man/tpm2_getrandom.1.md
man/tpm2_getsessionauditdigest.1.md
man/tpm2_startauthsession.1.md
test/integration/tests/sessionaudit.sh
tools/tpm2_getrandom.c
tools/tpm2_getsessionauditdigest.c
tools/tpm2_startauthsession.c

GetSessionAuditDigest

---

man/tpm2_pcrread.1.md
tools/tpm2_pcrread.c

Reverts tpm2-software/tpm2-tools#1991

Revert "Remove PCR Padding"

---

.cirrus.yml
README.md
configure.ac
lib/tpm2_eventlog_yaml.c
lib/tpm2_options.c
test/integration/helpers.sh
test/integration/tests/getekcertificate.sh
test/integration/tests/nv.sh
test/unit/test_options.c

Enable CI on FreeBSD

---

.ci/docker.run
configure.ac
doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
test/integration/fapi/fapi-encrypt-decrypt.sh
test/integration/fapi/fapi-key-change-auth.sh
tools/fapi/tss2_template.c
tools/tpm2_loadexternal.c

- Esys handle mapping fixes
- CI fix for shallow travis clones
- Changelog update
- Fapi TSS3.0 Configure flags update

[BACKPORT] Backports for 4.2.X

---

tools/tpm2_create.c

tpm2_create.c: Fix an issue where userwithauth attr cleared if policy specified

---

Makefile.am
lib/files.c
lib/files.h
lib/tpm2.c
lib/tpm2.h
man/tpm2_commit.1.md
man/tpm2_ecdhkeygen.1.md
man/tpm2_ecdhzgen.1.md
man/tpm2_ecephermal.1.md
man/tpm2_geteccparameters.1.md
man/tpm2_zgen2phase.1.md
test/integration/tests/ecc.sh
tools/tpm2_commit.c
tools/tpm2_ecdhkeygen.c
tools/tpm2_ecdhzgen.c
tools/tpm2_ecephermal.c
tools/tpm2_geteccparameters.c
tools/tpm2_zgen2phase.c

Fixes #835 
Fixes #834
Fixes #829 
Fixes #2026 
Fixes #2028 
Fixes #877 

Add ECC tools

---

man/tpm2_createak.1.md
man/tpm2_createek.1.md
man/tpm2_readpublic.1.md

Linking to the common/pubkey.md document,  the -f format specifiers files

---

README.md
doc/INSTALL.md
doc/RELEASE.md

Part of the process to de-feature the wiki pages to avoid stale
information remaining posted.
After this PR is merged, the wiki section will be deleted.

doc: Migrate necessary information from wiki

---

tools/tpm2_tool.c

tpm2_tool_register didn't make sure it was staying in bounds, so bad or missing CFLAGS could cause a wonky build.

Enforce tool size and a few cleanups

---

lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
tools/tpm2_create.c
tools/tpm2_createprimary.c

Fix: Incorrect return code for unsupported algorithms.

---

man/tpm2_nvread.1.md

man/tpm2_nvread: fix manpage example

---

test/integration/tests/rsadecrypt.sh
test/integration/tests/rsaencrypt.sh
tools/tpm2_rsadecrypt.c
tools/tpm2_rsaencrypt.c

Fix rsa oaep encryption/ decryption

---

lib/tpm2_convert.c

lib/tpm2_convert.c: Fix for RSA-PSS signature verification failure

---

.ci/travis.run
.travis.yml

Udate the travis.run file and pull out some of the magic values
and assign to global statics.

ci: update travis run

---

man/tpm2_unseal.1.md

tpm2_unseal.1.md: Update example section with an end-to-end example

---

.cirrus.yml

Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>

cirrus: remove gcrypt library

---

tools/fapi/tss2_template.c

FAPI>=3.0 introduces a new callback API for auth and branch selection that includes the object being authenticated. Add this information to the user-facing interaction on all tss2_* tools.
Change the password callback for new passwords to show a better string.
Addresses: #2101
This is the 2nd iteration of this PR and also supports FAPI 2.4.x with a (degraded) callback dialog.

tss2: Use FAPI new-style callback information

---

lib/tpm2_auth_util.c
lib/tpm2_policy.c
lib/tpm2_policy.h
man/tpm2_policypcr.1.md
test/integration/tests/abrmd_policypcr.sh
test/unit/test_tpm2_policy.c
tools/tpm2_createpolicy.c
tools/tpm2_policypcr.c

tpm2_policypcr: Add an option to directly specify digest of PCR values

---

man/tpm2_activatecredential.1.md
man/tpm2_nvdefine.1.md
test/integration/tests/activecredential.sh
test/integration/tests/attestation.sh
test/integration/tests/nv.sh
test/integration/tests/nvinc.sh

Replace constant values with 'o'/'p'/'e'

---

.cirrus.yml

cirrus: disable swtpm tcti on cirrus

---

.cirrus.yml

The version 1637 build fails.
https://cirrus-ci.com/task/5980103681245184?command=install#L2164

cirrus: build mssim in a single job

---

tools/fapi/tss2_template.c
tools/tpm2_tool.c

Don't create world readable files.... make them only group readable and fully controllable by owner.

set umask to 0117 (drop owner execute, group execute and all for other)

---

man/tpm2_nvincrement.1.md

tpm2_nvincrement.1.md: Fix for incorrect commands in example

---

tools/tpm2_nvdefine.c

Please refer to
https://github.com/tpm2-software/tpm2-tools/issues/2171

Structure is the wrong size(0x2d5) issue with tpm2_nvdefine without specifying the size

---

lib/tpm2_options.c

tpm2-tools help/ man: Fixed issue of arg=param wasn't working

---

tools/fapi/tss2_template.c

Do not initialize TSS API when options --help or --version
are invoked

tss2 *: Avoid unnecessary API initialization

---

scripts/utils/v4X_compatibility_test.sh

scripts: Add utility to check for backwards compatibility with 4.X

---

.ci/download-deps.sh

dependency update: Update to tpm2-tss v3.0.1 and tpm2-abrmd v2.3.3

---

test/integration/fapi/fapi-nv-write-read-policy-or.sh
test/integration/fapi/fapi-nv-write-read-policy-or2.sh
test/integration/helpers.sh

* A test with different policies in or branches was added.
* A test with two nested or policies was added.

fapi: add integration tests for policy or.

---

man/tpm2_hmac.1.md

man/tpm2_hmac.1.md: Fix the example section

---

tools/tpm2_import.c

tpm2_import: attribute parser doesn't handle nice names

---

lib/tpm2_session.c
lib/tpm2_util.c
lib/tpm2_util.h
test/unit/test_tpm2_session.c

tpm2_util_esys_handle_to_sys_handle: Remove unused routine

---

lib/tpm2_options.c
test/integration/tests/symlink.sh
tools/tpm2_tool.c

Help man pages for commandlet style

---

test/integration/tests/createprimary.sh

createprimary.sh: Test adding unique for ECC key type.

---

lib/files.c
lib/files.h
man/tpm2_createprimary.1.md
test/integration/tests/createprimary.sh
tools/tpm2_createprimary.c

Add unique data to the object via stdin

---

lib/tpm2_kdfa.c

This patch fixes an issue with tpm2_makeidentity when run on a big
endian system and the result is used by a little endian system, as
may be the case with keylime. The byte swapping must only be done
on little endian systems.
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

Fix tpm2_kdfa for big endian systems

---

tools/tpm2_getrandom.c

The buffers allocated for cp_hash and rp_hash weren't freed on
some error paths.

tpm2_getrandom: Fix resource leaks

---

tools/misc/tpm2_checkquote.c

Signed-off-by: ramonssarmento <ramon.sarmento@ccc.ufcg.edu.br>

Including inttypes.h on tpm2_checkquote

---

Makefile.am
dist/bash-completion/tpm2-tools/tpm2_completion.bash
lib/tpm2.c
lib/tpm2.h
man/tpm2.1.md
man/tpm2_ecephemeral.1.md
man/tpm2_policyauthvalue.1.md
man/tpm2_policypassword.1.md
man/tpm2_zgen2phase.1.md
test/integration/tests/ecc.sh
tools/tpm2_commit.c
tools/tpm2_ecephemeral.c

tpm2_ecephemeral: Fix typo in tool name

---

doc/CHANGELOG.md

doc/CHANGELOG.md: Update changelog.

---

doc/CHANGELOG.md

doc/CHANGELOG.md: tpm2-tools release version 5.0

---

lib/tpm2_session.c

1. Declare/ define variables closes to their scope of use
2. Set rc to tool_rc_general error explicitly on error paths
3. Do not use temporary return from function calls directly
as function arguments.

lib/tpm2_session.c: Update tpm2_session_close

---

lib/tpm2_eventlog_yaml.c

EV_IPL is an event type extensively used by the Shim and Grub on a wide varieties of Linux distributions to measure grub and kernel command line parameters and the loading of grub, kernel, and initrd images. Parsing its payload is useful to understand what happened during the boot process, e.g., from `test/integration/fixture/event-bootorder.bin`:
```
- EventNum: 27
PCRIndex: 8
EventType: EV_IPL
DigestCount: 2
Digests:
Digest: "5bb3e7b9b843fa3bf11e7a85877c095031f6242f"
Digest: "b2166ffbf190a9bb3809a5a1dcb44bb5f3de6b44c2c27f1e4220a83f92d0c06a"
EventSize: 69
Event:
String: 'grub_cmd: [ -z (hd0,gpt15)/boot/grub -o ! -e (hd0,gpt15)/boot/grub ]'
```

tpm2_eventlog: add EV_IPL parsing

---

lib/tpm2_eventlog.c

This PR attempts to verify eventlog entries by comparing digest values against payload, to thwart possible forgeries.
Relevant issues: Issue #2252, Issue #2247 
As I addressed in Issue #2252, verifying all event types is currently impossible from the eventlog alone. There are certain event types, e.g., EV_EFI_BOOT_SERVICES_APPLICATION, EV_EFI_BOOT_SERVICES_DRIVER, that are used to load driver, kernel, shim, grub code into the memory during the boot process, where their digest is calculated based on the loaded code, which is not included in the eventlog. There needs to be an out-of-band process to verify these events along with the in-band eventlog digest verification that we're doing here. Moreover, ambiguities in the spec could lead to vendor specific way of determining what data is used …

tpm2_eventlog: verifies digest matches event payload for certain event types

---

.ci/docker.run

ci: fix fetch and checkout for remote repo

---

tools/tpm2_startauthsession.c

tpm2_startauthsession: Move audit-attr setting at option specification.

---

tools/tpm2_sessionconfig.c

tpm2_sessionconfig.c: Fix segfault due to missing input session file

---

lib/tpm2_eventlog.c

Redhat Grub2 that produces EV_IPL events has 2 ways to output an event and calculate its digest.
Method 1 example:
```
- EventNum: 21
PCRIndex: 8
EventType: EV_IPL
DigestCount: 2
Digests:
Digest: "714c8a0d8016cf3a55618a3349203867be7569ff"
Digest: "8669c965de1e7cabd1ed2a8f119b7dca326b97223fd8f8bf2fc661973a41a13b"
EventSize: 23
Event:
String: |-
grub_cmd set timeout=5
```
The digest is calculated from the string `set timeout=5\0'. 
Method 2 example:
```
- EventNum: 26
PCRIndex: 8
EventType: EV_IPL
DigestCount: 2
Digests:
Digest: "732c713a6f4c3a388ee1b46624b7c3fe34d59d50"
Digest: "71a5b3b21ac3862f40fabb745a9649c3a1d34249b9706524c90b2480c298beb0"
EventSize: 24
Event:
String: |-
grub_cmd: set timeout=5
```
Note …

tpm_eventlog: fix EV_IPL verification

---

test/integration/fapi/fapi-policy_signed_delegation.sh

A bugfix in TPM2 TSS regarding the inclusion of PolicyRef
revealed an error in the policy_signed_delegation test.
The PolicyRef values are adjusted accordingly in this commit.

tss2 *: Fix policy signed delegation test

---

lib/tpm2.c
lib/tpm2.h
lib/tpm2_util.c
lib/tpm2_util.h
man/tpm2_getrandom.1.md
test/integration/tests/getrandom.sh
tools/tpm2_getrandom.c

tpm2_getrandom: Add support for specifying multiple aux sessions

---

lib/tpm2.c
lib/tpm2.h
man/tpm2_create.1.md
test/integration/tests/create.sh
tools/tpm2_create.c

tpm2_create: Add support for specifying multiple aux sessions

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvextend.1.md
test/integration/tests/nv.sh
tools/tpm2_nvextend.c

tpm2_nvextend: Add support for specifying multiple aux sessions

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_unseal.1.md
test/integration/tests/unseal.sh
tools/tpm2_unseal.c

tpm2_unseal: Add support for specifying aux sessions for audit/enc

---

.lgtm.yml

lgtm.yml: Add the missing dependency - acl

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_nvdefine.c

tpm2_nvdefine: Restructure tools code layout to a standard or common format

---

tools/tpm2_nvextend.c

tpm2_nvdefine: Enable rpHash for session-audit support

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_nvextend.c

tpm2_nvextend: Use pHash_alg by parsing sessions input

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvextend.1.md
test/integration/tests/sessionaudit.sh
tools/tpm2_nvextend.c

tpm2_nvextend: Enable rpHash for session-audit support

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_unseal.1.md
test/integration/tests/sessionaudit.sh
tools/tpm2_nvdefine.c
tools/tpm2_nvextend.c
tools/tpm2_unseal.c

tpm2_unseal: Restructure tools code layout to a standard format

---

doc/CHANGELOG.md
tools/misc/tpm2_eventlog.c

tpm2_eventlog: Support logs longer than 64KB

---

tools/tpm2_dictionarylockout.c

tpm2_dictionarylockout: Fix issue where setting value reset others

---

Makefile.am
doc/CHANGELOG.md
man/tpm2_getpolicydigest.1.md
test/integration/tests/getpolicydigest.sh
tools/tpm2_getpolicydigest.c

tpm2_getpolicydigest: Add new tool to enable TPM2_CC_PolicyGetDigest

---

man/tpm2_sessionconfig.1.md
test/integration/tests/sessionconfig.sh
tools/tpm2_sessionconfig.c

tpm2_sessionconfig: Process only setting/ displaying session attributes

---

.ci/coverity.run

.ci/coverity.run: Fix broken links and references

---

lib/tpm2_convert.c
lib/tpm2_eventlog.c
lib/tpm2_util.c
tools/misc/tpm2_checkquote.c

Fix coverity reported issues

---

lib/tpm2_util.c

lib/tpm2_util.c: Fix potential buffer over-run

---

.ci/download-deps.sh

.ci/download-deps.sh: Bump tpm2-tss version to 3.0.3

---

man/tpm2.1.md

man/tpm2.1.md: Add sessioncofig to the list of available tools

---

doc/CHANGELOG.md

CHANGELOG: update for 4.3.1

---

.ci/download-deps.sh

.ci/download-deps.sh: Bump tpm2-tss version to 3.1.0

---

tools/tpm2_rsadecrypt.c
tools/tpm2_rsaencrypt.c

tpm2_rsa(enc/dec)rypt: Report error message on invalid scheme

---

tools/tpm2_import.c

tpm2_import used a fixed AES key for the inner wrapper, which means that
a MITM attack would be able to unwrap the imported key. Even the
use of an encrypted session will not prevent this. The TPM only
encrypts the first parameter which is the fixed symmetric key.
To fix this, ensure the key size is 16 bytes or bigger and use
OpenSSL to generate a secure random AES key.
Fixes: #2738

tpm2_import: fix fixed AES key CVE-2021-3565

---

doc/CHANGELOG.md

doc/CHANGELOG.md: update changelog for 4.3.2-rc0 CVE-2021-3565 fix

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvsetbits.1.md
test/integration/tests/sessionaudit.sh
tools/tpm2_nvsetbits.c

tpm2_nvsetbits: Restructure tools code layout to a standard or common format

---

lib/efi_event.h
lib/tpm2_eventlog_yaml.c

Signed-off-by: Mike Spreitzer <mspreitz@us.ibm.com>

Add decoding of StartupLocality

---

man/tpm2_policyauthorize.1.md

The example was bad explained because in the trial session the authorization policy is being created, it is not authorizing anything (you don't need to include -i pcr.policy in the trial session)
So I changed that, restructured the example, and changed the example variables names to make this command more understandable

Update example tpm2_policyauthorize.1.md

---

tools/tpm2_nvread.c

tools/tpm2_nvread: Redo tool layout to standard format

---

tools/tpm2_sign.c

tools/tpm2_sign: Fix segfaults when hash validation fails

---

tools/tpm2_loadexternal.c

Fixes #2779
This should now work
loadexternal -G rsa2048:aes128cfb -C n -u public.pem -c key.ctx \
-a 'fixedtpm|fixedparent|sensitivedataorigin|adminwithpolicy|restricted|decrypt'

tpm2_loadexternal: Fix issue where a restricted attr couldn't be set

---

lib/tpm2_nv_util.h
tools/tpm2_nvdefine.c
tools/tpm2_nvwrite.c

tpm2_nvdefine: clarify messaging when TPM properties can't be read

---

test/integration/tests/getekcertificate.sh
tools/tpm2_getekcertificate.c

tpm2_getekcertificate: Don't post-process DER INTC EK cert on NV

---

.cirrus.yml

.cirrus.yml: update py yaml version

---

lib/tpm2_kdfa.c

The HMAC_Update is deprecated in OpenSSL 3.0, but the replacement EVP_MAC_update was added in OpenSSL 3.0, so version specific code is needed.

openssl: Use EVP_MAC_update instead of HMAC_Update on OpenSSL >= 3.0.0

---

tools/misc/tpm2_certifyX509certutil.c

The `tpm2_certifyX509certutil.c`:`generate_partial_X509()` creates a partial (in fact, an incomplete) certificate, see Part 3, 18.8.1. The OpenSSL team decided that starting from 3.0 the i2d should not create invalid encodings, so we need to create an own ASN.1 structure for this.
This PR:
* Switches from `X509 *` to `TPM2_PARTIAL_CERT *`, which is adapted from https://github.com/openssl/openssl/issues/16257#issuecomment-895448370.
* Removes unnecessary `X509_get_XX` - `X509_set_XX` pairs. (The pointer was retrieved and then put back, which is not necessary as the pointer was already set when retrieved.)
* Removes the `fixup_cert` which I believe is not necessary now.
Fixes: #2813

Generate partial X.509 certificate using own struct

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvextend.1.md
test/integration/tests/abrmd_policycphash.sh
tools/tpm2_nvextend.c

tpm2_nvextend: Add support to calculate cpHash with --tcti=none

---

doc/CHANGELOG.md

doc/CHANGELOG.md: Update to version 5.2-rc0

---

tools/tpm2_getcap.c

tpm2_getcap: Fix for a typo when printing TPM2_PT_PERMANENT info

---

tools/tpm2_evictcontrol.c

tools/tpm2_evictconrol: fix for call to Esys_TR_Close on bad handle

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvwrite.1.md
test/integration/tests/abrmd_policycphash.sh
test/integration/tests/sessionaudit.sh
tools/tpm2_nvwrite.c

Fixes #2424
Fixes #2520 
Fixes #2615

tools/tpm2_nvwrite.c: Redo tools layout

---

tools/tpm2_nvwrite.c

tools/tpm2_nvwrite: Fix auth errors when writing NV data > 1024

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvwritelock.1.md
test/integration/tests/abrmd_policycphash.sh
test/integration/tests/sessionaudit.sh
tools/tpm2_nvwritelock.c

Fixes #2425
Fixes #2616 
Fixes #2521 

tools/tpm2_nvwritelock: Redo tools layout

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvreadlock.1.md
test/integration/tests/abrmd_policycphash.sh
test/integration/tests/sessionaudit.sh
tools/tpm2_nvreadlock.c

Fixes #2420
Fixes #2611
Fixes #2516 

tools/tpm2_nvreadlock: Redo tool layout

---

doc/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_nvundefine.1.md
test/integration/tests/abrmd_policycphash.sh
test/integration/tests/sessionaudit.sh
tools/tpm2_nvundefine.c

Fixes #2423
Fixes #2614 
Fixes #2519 

tools/tpm2_nvundefine: Redo tools layout

---

tools/tpm2_nvundefine.c

tools/tpm2_nvundefine.c: Fix typo

---

docs/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
lib/tpm2_nv_util.h
man/tpm2_nvreadpublic.1.md
test/integration/tests/nv.sh
test/integration/tests/sessionaudit.sh
tools/tpm2_nvcertify.c
tools/tpm2_nvreadpublic.c
tools/tpm2_nvundefine.c
tools/tpm2_nvwrite.c
tools/tpm2_policynv.c

Fixes #2421 
Fixes #2612 
Fixes #2517 

tpm2_nvreadpublic: Add option to output cpHash

---

man/tpm2_nvwrite.1.md

man/tpm2_nvwrite.1.md: Clarify that the file/ stdin input is a must

---

tools/tpm2_pcrevent.c

tools/tpm2_pcrevent: Improve handling of procfs (0 byte) files

---

tools/tpm2_create.c

Signed-off-by: 杨明君 <yangmingjun@uniontech.com>

fix: a CLang compile error!

---

lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
tools/tpm2_sign.c
tools/tpm2_verifysignature.c

Signed-off-by: 杨明君 <yangmingjun@uniontech.com>

feat: support to sign and verify of the sm2 algorithms.

---

tools/tpm2_flushcontext.c

Support the -t/-l/-s options all at once so folks don't have to call it
multiple times.

tpm2_flushcontext: support all options at a time

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_clear.c

Issue 2387

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_dictionarylockout.c

Issue 2395

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_clearcontrol.c

Issue 2388

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_sign.c

Issue 2460

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_setprimarypolicy.c

Issue 2458

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_setclock.c

Issue 2456

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_rsadecrypt.c

Issue 2452

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_duplicate.c

Issue 2396

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_clockrateadjust.c

Issue 2389

---

lib/tpm2.c
lib/tpm2.h
lib/tpm2_hierarchy.c
lib/tpm2_hierarchy.h
tools/tpm2_createek.c
tools/tpm2_createprimary.c

Issue 2394

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_quote.c

Issue 2449

---

lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
lib/tpm2_policy.h
tools/tpm2_policysecret.c

Issue 2445

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_import.c

Issue 2412

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_hmac.c

Issue 2411

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_hierarchycontrol.c

Issue 2410

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_load.c

Issue 2414

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_gettime.c

Issue 2408

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_evictcontrol.c

Issue 2401

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_encryptdecrypt.c

Issue 2400

---

tools/misc/tpm2_checkquote.c

tools/tpm2_checkquote: Fix compilation failures  with openSSL 3

---

tools/tpm2_clear.c
tools/tpm2_clearcontrol.c
tools/tpm2_clockrateadjust.c

tools: fix a spurious TPM-clear warning message

---

.ci/download-deps.sh
.github/workflows/main.yml
docs/CHANGELOG.md

ci: add ubuntu-22.04

---

lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
lib/tpm2_policy.h
test/integration/tests/getpolicydigest.sh
test/unit/test_tpm2_policy.c
tools/tpm2_createpolicy.c
tools/tpm2_getpolicydigest.c

tools/tpm2_getpolicydigest: Add support for cpHash

---

lib/tpm2.c
lib/tpm2.h
test/integration/tests/loadexternal.sh
tools/tpm2_loadexternal.c
tools/tpm2_makecredential.c

Issue 2415

---

docs/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_commit.1.md
test/integration/tests/ecc.sh
tools/tpm2_commit.c

Issue 2390

---

tools/tpm2_ecdhkeygen.c

Issue_2397

---

lib/tpm2_alg_util.c
lib/tpm2_openssl.c
test/integration/tests/import.sh

Fix import ext algs

---

lib/tpm2_alg_util.c
lib/tpm2_alg_util.h
lib/tpm2_hash.c
lib/tpm2_hash.h
scripts/utils/sm_algorithm_test.sh
tools/tpm2_sign.c
tools/tpm2_verifysignature.c

bugfix: sm2 sign and verifysignature

sm2 sign and verifysignature

---

tools/tpm2_ecephemeral.c

tools/tpm2_ecephemeral: redo tools layout

---

tools/tpm2_geteccparameters.c

tools/tpm2_geteccparameters: redo tools layout

---

lib/tpm2_session.c
lib/tpm2_session.h
tools/tpm2_flushcontext.c

tools/tpm2_fluscontext.c: Redo tools layout and fix segfault

---

docs/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_ecdhkeygen.1.md
test/integration/tests/ecc.sh
tools/tpm2_ecdhkeygen.c

tools/tpm2_ecdhkeygen: Add support for calculating cpHash

---

docs/CHANGELOG.md
lib/object.c
lib/object.h
man/tpm2_load.1.md
test/integration/tests/load.sh
tools/misc/tpm2_encodeobject.c
tools/tpm2_load.c

Signed-off-by: malikabhi05 <abhishek.malik@intel.com>

Adding PEM support to tpm2 tools

---

docs/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_ecdhzgen.1.md
test/integration/tests/ecc.sh
tools/tpm2_ecdhzgen.c

tools/tpm2_ecdhzgen: add support for calculating cpHash

---

tools/tpm2_pcrallocate.c

tools/tpm2_pcrallocate: redo tools layout

---

.cirrus.yml

.cirrus.yml: update py yaml package

---

tools/tpm2_pcrevent.c

tools/tpm2_pcrevent.c: redo tools layout

---

docs/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_ecephemeral.1.md
test/integration/tests/ecc.sh
tools/tpm2_ecephemeral.c

tools/tpm2_ecephemeral: add support for calculating cpHash

---

docs/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
lib/tpm2_alg_util.c
man/tpm2_geteccparameters.1.md
test/integration/tests/ecc.sh
tools/tpm2_geteccparameters.c

tools/tpm2_geteccparameters: add support for calculating cpHash

---

docs/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
lib/tpm2_session.c
man/tpm2_flushcontext.1.md
test/integration/tests/flushcontext.sh
tools/tpm2_createek.c
tools/tpm2_flushcontext.c
tools/tpm2_makecredential.c

tools/tpm2_flushcontext: add support for calculating cpHash

---

tools/tpm2_pcrreset.c

tools/tpm2_pcrreset: redo tool's layout

---

tools/tpm2_pcrread.c

tools/tpm2_pcrread.c: redo tool's layout

---

docs/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_pcrallocate.1.md
test/integration/tests/pcrallocate.sh
tools/tpm2_pcrallocate.c

tools/tpm2_pcrallocate: add support for calculating cpHash

---

lib/tpm2.c
lib/tpm2.h
tools/tpm2_pcrextend.c

tools/tpm2_pcrextend.c: redo tool's layout

---

docs/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_pcrevent.1.md
test/integration/tests/pcrevent.sh
tools/tpm2_pcrevent.c

tools/tpm2_pcrevent: add support for calculating cpHash

---

docs/CHANGELOG.md
lib/tpm2.c
lib/tpm2.h
man/tpm2_pcrreset.1.md
test/integration/tests/pcrreset.sh
tools/tpm2_pcrreset.c

tools/tpm2_pcrreset: add support for calculating cpHash

---

test/integration/tests/certify.sh

test/certify.sh: add test verifying cerifyinfo signature with openssl

---

tools/tpm2_pcrevent.c

tools/tpm2_pcrevent.c: remove unreachable dead code

---

lib/tpm2_hash.c

lib/tpm2_hash.c: Fix buffer overrun in sm2 messaged digest calc

---

docs/CHANGELOG.md
lib/pcr.c
lib/pcr.h
lib/tpm2.c
lib/tpm2.h
lib/tpm2_policy.c
man/tpm2_pcrread.1.md
test/integration/tests/pcrlist.sh
tools/tpm2_pcrread.c
tools/tpm2_quote.c

tools/tpm2_pcrread: add support for calculating cpHash

---

tools/tpm2_policyauthorize.c

tools/tpm2_policyauthorize.c: redo tools layout

---

tools/tpm2_policyauthvalue.c

tools/tpm2_policyauthvalue: redo tool layout

---

tools/tpm2_policypassword.c

tools/tpm2_policypassword.c: redo tool layout

---

docs/CHANGELOG.md

docs/CHANGELOG.md: add missing updates since 5.2 release

---

docs/CHANGELOG.md

doc/CHANGELOG.md: Update to version 5.3-rc0

---

test/integration/tests/pcrevent.sh
test/integration/tests/pcrreset.sh

fixing typod to match the test headers with the tests

---

docs/CHANGELOG.md

docs/CHANGELOG.md: update to version 5.3-rc1

---

.cirrus.yml

.cirrus.yml: update to freebsd version 13.1

---

.github/workflows/cron.yml
.github/workflows/main.yml

Signed-off-by: malikabhi05 <abhishek.malik@intel.com>

CI: moving multiarch job to cron

---

tools/tpm2_sessionconfig.c

When the session context is that of a non policy session, an attempt to read the policy digest results in an error.

tools/tpm2_sessionconfig: fix error with the policy digest output

---

docs/README.md
docs/RELEASE.md
man/common/footer.md

update mailing list

---

README.md
doc/RELEASE.md
man/common/footer.md

update mailing list (5.1.X)

---

.ci/docker.run
docs/CHANGELOG.md
test/unit/vendor_tests.sh

CHANGELOG: update for 5.4-rc0

---

lib/tpm2_convert.c
tools/tpm2_createek.c

1. sm2 public key in openssl3
2. add sm2 ek template support

bugfix: sm2 public key in openssl3

---

tools/tpm2_sessionconfig.c

tpm2_sessionconfig: remove dead code

---

docs/CONTRIBUTING.md
docs/SECURITY.md
lib/tpm2_attr_util.c

SECURITY.md: initial commit

---

docs/MAINTAINERS.md

MAINTAINERS: add Juergen and Andreas

---

test/integration/tests/abrmd_policynv.sh

The tests whch use sign comparison operators will be skipped. After a CI
update these tests did produce strange error(0x126) which did not occur
outside the new docker images. Downgrade to the version of swtpm where
this error did not occur did not change this behaviour.

abrmd_policynv.sh Skip test which uses sign operator for comparison

---

test/integration/helpers.sh

Also add "dbus-run-session" in the example code that explain how to run the test.

tests: defaut to Python 3 in helpers code

---

lib/tpm2_eventlog.c

tpm2_eventlog.c: some minor formatting fixes.

---

test/integration/tests/encryptdecrypt.sh
tools/tpm2_encryptdecrypt.c

First, the padding was read from the first block within the buffer, while it is always on the final block.
Second, if padding is malformed in any way (e.g. decrypt with a different IV), the out_data.size could overflow, resulting in access to memory outside of out_data.buffer.
To address the second case, do not strip padding if pad_data is larger than the block length. As an additional check, verify that pad_data is consistent, which also leaves data as is should the check fail.

tpm2_encryptdecrypt: Fix pkcs7 padding stripping

---

lib/files.c

Originally the unique data was only loadable from a file, and it had to contain the full TPMU_PUBLIC_ID contents.
When the code was refactored to allow loading from stdin, the data was was changed:
```
commit 8540e7f0edcfcccf6097f0e453fd6c08657a0577
Author: Imran Desai <imran.desai@intel.com>
Date:   Tue Oct 13 16:21:08 2020 -0700
tpm2_createprimary: Add option to input unique from stdin
Fixes #2091
```
In this change the size of the buffer used was altered from sizeof(TPMU_PUBLIC_ID) to TPM2_MAX_RSA_KEY_BYTES. This is incorrect as sizeof(TPMU_PUBLIC_ID) is 2 bytes larger than TPM2_MAX_RSA_KEY_BYTES, as it has the UINT16 size field.
This change caused a regression in the ability to load unique data from a file for a 512 byte RSA key, …

files: fix upper bound on unique data size

---

tools/tpm2_createek.c

The current TCG EK Credential Profile [0] in section "2.2.1.6 TPMT_PUBLIC Calculation" states:
"If the EK Template is Populated and the EK Nonce is Absent, the EK Template is used unmodified as the TPMT_PUBLIC." Currently the command did produce an error if there is a template but no nonce.
Now the template is used but it's checked whether the nonce exists. Fixes #3278.

tpm2_createek: Fix usage of nonce.

---

docs/MAINTAINERS.md

Ajay Kishore is added to the maintainers file.

maintainers: Add Ajay

---

man/tpm2_create.1.md

An example with an appropriate algorithm parameter was added.

tpm2_create.md Add example for a restricted signing key

---

docs/RELEASE.md

Fixes #3360 
Adding @ajaykish to the list

RELEASE.md: Updating maintainer's list

---

docs/RELEASE.md
test/integration/tests/certify.sh
test/integration/tests/certifycreation.sh
test/integration/tests/commandaudit.sh
test/integration/tests/gettime.sh
test/integration/tests/nvcertify.sh
test/integration/tests/sessionaudit.sh
tools/misc/tpm2_print.c

Coverity scan

---

.github/workflows/main.yml
docs/RELEASE.md

* Add Andreas and Juergen to maintainer list in RELEASE.md
* Remove ubuntu 18.04 build tests.
* Fix get stuck in a AddressSanitizer:DEADLYSIGNAL loop in the CI.

Update maintainer list and fix CI problems.

---

.cirrus.yml
test/integration/helpers.sh

13.2 is apparently no longer available

cirrus-ci update image-family to freebsd-14-0

---

man/tpm2_duplicate.1.md

fixes https://github.com/tpm2-software/tpm2-tools/issues/3391
@AndreasFuchsTPM

Add policyduplicationselect example to duplicate docs

---

test/integration/tests/pcrevent.sh
test/integration/tests/symlink.sh

See https://lwn.net/Articles/874049/

tests: Eliminate dependency on 'which'

---

man/tpm2_policynv.1.md

The examples did not work as expected.
Fixes: #3418

tpm2_policynv.md Fix examples.

---

.cirrus.yml

cirrus-ci: update py39

---

man/tpm2_getcap.1.md

Closes https://github.com/tpm2-software/tpm2-tools/issues/3226

man/tpm2_getcap: don't mention non-existing -c flag

---

.ci/download-deps.sh
.github/workflows/main.yml
lib/files.c
lib/log.c
lib/tpm2_policy.c
tools/fapi/tss2_gettpm2object.c
tools/tpm2_commit.c
tools/tpm2_ecephemeral.c

* scan-build errors which did occur on arch-linux are fixed.
* workarounds for scan-build false positives are added.
* arch-linux and ubuntu24.04 are added to the ci.

scanbuild: Several scan-build errors are fixed.
